### ISSUE TITLE
Invalid XML

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#121]
This is the XML generated when scanning a host that Nikto thinks isn't up. I remember having trouble a few years ago with the XML not validating but haven't looked at it for a while.

<?xml version="1.0" ?>
<!DOCTYPE niktoscan SYSTEM "docs/nikto.dtd">

</niktoscan>

</niktoscan>

</niktoscan>

</niktoscan>

**Comment by sullo** [comment]
Not sure this is still valid. Also see #28
