### ISSUE TITLE
Add severities to checks  

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#13]
Add severity levels (.e.g, High/Med/Low/Info?) for all checks. Notate/color-code them in reports.

**Comment by tautology0** [comment]
Bearing in mind what a terrible job other tools do of this (e.g. Nessus) I think we should just report the findings.

**Comment by digininja** [comment]
Fully agree with this. One person's severe is another's low. You report it,
let the tester decide if it's a problem or not.
