### ISSUE TITLE
False positive from nikto_auth.plugin on crappy server

### ISSUE THREAD

**Issue by RealRancor** [sullo/nikto#135]
Hi,

noticed an false positive from the nikto_auth.plugin using the current master branch of nikto:

```
Default account found for 'Access to /logs' at /logs/str_err.log (ID '', PW '_Cisco'). Cisco device.
```

This server is replying with a "500 Internal Server Error" when entering any credentials which seems to be identified by nikto as a valid login. No idea if this can be handled by nikto at all.

**Comment by DanMcInerney** [comment]
I got a similar one for an old frontpage site.

"Default account found for 'ntlm' at /nikto-test-9Dvf3Df9.html (ID '', PW '_Cisco'). Cisco device."

I see the nikto-test file on the server but the server also allowed unauthenticated PUT so I'm not sure if that's actually how it uploaded the file.

**Comment by tautology0** [comment]
Looking at the code, it checks for a 40[13] and counts that as a fail (which is technically correct). But, the 500 case is important - I'll add that as a fail condition too.
