### ISSUE TITLE
apacheusers doesn't work properly

### ISSUE THREAD

**Issue by tautology0** [sullo/nikto#143]
I brushed the dust off apacheusers for my first real world use in about 4 years in the middle of an exam and... It didn't work! I had to use metasploit instead (for shame).

Needs a bit of debugging which I couldn't do at the time to work out what's wrong (I think it was Nikto being overly picky on the response codes).

**Comment by sullo** [comment]
I don't think this rewrite is going to happen at this point. I _do_ see the apacheusers plugin no longer looks for /~root but for /~bin as the first test.
