### ISSUE TITLE
manually specify a 404 string

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#169]
I'm scanning a site where the 404 page returns a 200 but the built in detection isn't able to recognise the page and so I've got a load of false positives, it would be good to pass a string on the command line which only appears in the 404 page to use instead of the automated detection.

**Comment by ethicalhack3r** [comment]
Just came across this as needed similar functionality. Noticed the option is not mentioned in Nikto's output (that I could see). Not sure if this is intentional or not.

For example, I wasn't sure if the option was ```404string "some string"```, ```-404string "some string"``` or ```-404string="some string"```, etc...

Correct one seems to be ```404string="some string"```

**Comment by sullo** [comment]
It works like most perl options... "-no404 string" or "-no404=string".

I also added it to the doc xml as it was missing.
