### ISSUE TITLE
Allow better support for external dictionaries  

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#20]
There are several web projects which have dictionaries of common files/directories. These are partially supported by the nikto_dictionary_attack plugin, although this was built around the dirbuster dictionaries.

Allow support for other common types of dictionaries, such as fuzzdb.

Also allow support for variables defined in nikto.conf/db_variables to be used to define the path, e.g. @FUZZDB or @DIRBUSTER.

**Comment by q2dg** [comment]
It's a real pity this request hasn't been taken into account

**Comment by sullo** [comment]
This can be done with a udb_tests file. 
https://cirt.net/nikto2-docs/expanding.html#id2792589
