### ISSUE TITLE
Improvements for path traversals

### ISSUE THREAD

**Issue by RealRancor** [sullo/nikto#201]
Hi,

while working on https://github.com/sullo/nikto/pull/199 i've noticed that most of the path traversals are using either boot.ini OR /etc/passwd.

But especially in the case of TYPO3 or most of other PHP applications those could be also hosted on windows and then the check is failing.

Is there any way to improve this? Some ideas how to do this can be found in OpenVAS's http_keepalive:

http://wald.intevation.org/scm/viewvco.php/scripts/http_keepalive.inc?revision=750&root=openvas-nvts&view=markup#l582

What happens if something like:

```
"000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e@LFITARGET%00","GET","@LFIPATTERN","","","","","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""
```

is used and the different target files (@LFITARGET) and the matching patterns (@LFIPATTERN) in the db_variables are used?

Are there any other possibilities to use different target files and pattern?

**Comment by RealRancor** [comment]
So had a look at this today and its seems the db_variables could be only used in the URI field?

Any hints how to implement an LFI test for windows and linux without adding duplicated tests to the db_tests? (Pointers to code parts of niktos are welcome). Would love to see this in nikto.

**Comment by sullo** [comment]
What other field(s) would need variables in them? Trying to think of a
use-case for that...

On Tue, Feb 17, 2015 at 8:40 AM, RealRancor <notifications@github.com>
wrote:

> So had a look at this today and its seems the db_variables could be only
> used in the URI field?
>
> Any hints how to implement an LFI test for windows and linux without
> adding duplicated tests to the db_tests? (Pointers to code parts of niktos
> are welcome). Would love to see this in nikto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/issues/201#issuecomment-74668696>.
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by RealRancor** [comment]
A use case for this is the shown typo3 test above. Normally Nikto should check four variants of it:

``"000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00","GET","root:.*:0:[01]:","","","","","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""``

``"000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/boot.ini%00","GET","\[boot loader\]","","","","","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""``

``"000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/winnt/win.ini%00","GET","; for 16-bit app support","","","","","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""``

``"000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/winnt/win.ini%00","GET","windows/win.ini","","","","","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""``

to be able to detect the vulnerability on Windows and Linux systems. With the current test Nikto is missing this vulnerability on Windows systems. This is also valid for many other tests were only /etc/passwd or boot.ini is tested.

I'm trying to find a solution for this without duplicating the tests for all four possibilities.

**Comment by sullo** [comment]
But I'm not sure why a variable in something other than the URI is needed?
If you did something like @TRAVERSALTARGET (boot.ini/passwd) you would just
use the *OR* match fields to look for [boot loader] OR root:0.

The traversal path/method could get murkier, but you can do something like
@TRAVERSAL which could have %2e%2e... and ../ and... whatever seems
appropriate.

Could get ugly but seems like you could do this with 2 variables and no
code changes?

On Tue, Feb 17, 2015 at 9:49 AM, RealRancor <notifications@github.com>
wrote:

> A use case for this is the shown typo3 test above. Normally Nikto should
> check four variants of it:
>
> "000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00","GET","root:.*:0:[01]:","","","","","TYPO3
> allows any file to be retrieved remotely. Upgrade to the latest
> version.","",""
>
> "000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/boot.ini%00","GET","\[boot
> loader\]","","","","","TYPO3 allows any file to be retrieved remotely.
> Upgrade to the latest version.","",""
>
> "000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/winnt/win.ini%00","GET",";
> for 16-bit app support","","","","","TYPO3 allows any file to be retrieved
> remotely. Upgrade to the latest version.","",""
>
> "000552","54058","5","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/winnt/win.ini%00","GET","windows/win.ini","","","","","TYPO3
> allows any file to be retrieved remotely. Upgrade to the latest
> version.","",""
>
> to be able to detect the vulnerability on Windows and Linux systems. With
> the current test Nikto is missing this vulnerability on Windows systems.
> This is also valid for many other tests were only /etc/passwd or boot.ini
> is tested.
>
> I'm trying to find a solution for this without duplicating the tests for
> all four possibilities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/issues/201#issuecomment-74678746>.
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by RealRancor** [comment]
> If you did something like @TRAVERSALTARGET (boot.ini/passwd) you would just use the *OR* match fields to look for [boot loader] OR root:0.

Overall we need three pattern for the match:

root:.*:0:[01]:
; for 16-bit app support
\[boot loader\]

I have already done something like:

"GET","root:.*:0:[01]:","(; for 16-bit app support|\[boot loader\])",

which works but then this needs to be specified for all tests. If this is fine for you i will create a PR for this tomorrow.

But the main reason of my request was that the match part is picked up depending what is specified like:

@TRAVERSALWIN=/boot.ini /winnt/win.ini /windows/win.ini
-> Match: ; for 16-bit app support, \[boot loader\]

@TRAVERSALLIN=/etc/passwd
-> Match: root:.*:0:[01]:

@TRAVERSALALL=/etc/passwd /boot.ini /winnt/win.ini /windows/win.ini
-> Match: ; for 16-bit app support, \[boot loader\], root:.*:0:[01]:

> The traversal path/method could get murkier, but you can do something like @TRAVERSAL which could have %2e%2e... and ../ and... whatever seems appropriate.

I think that would be only a cosmetic/nice to have change so i skip this for now.

**Comment by tautology0** [comment]
At the moment change_variables will only affect the URI. So we'd need 3 matches to check. We'd have to update change_variables or do a new function. It would be useful though.

Also, checking for boot.ini and c:\winnt\win.ini won't match Windows with a greater version than 6 (i.e. Win2k8, 2k12, vista, 7, 8, 10). We should add c:\windows\win.ini to the mix and possibly remove boot.ini

**Comment by RealRancor** [comment]
Some Nikto internal functions is probably the cleanest way of doing this to avoid having duplicated match pattern all over the db_tests file.

So maybe something like the variables described in https://github.com/sullo/nikto/issues/201#issuecomment-74750212 could be used in the nikto_tests.plugin and then the test is picking up the right matches for them?

Unfortunately i don't have that much insight into Nikto and also Perl itself so any pointers are welcome how to implement this.

**Comment by RealRancor** [comment]
Hey, i would love to get this implemented so will have a look at this in the next few days. Maybe its easier to implement this within an own plugin.

I think it should be possible to move all traversal tests from db_tests into db_traversal and then use a syntax like within that:

```
# ID, OSVDB, URI, Method, LIN/WIN/BOTH, Description, HTTP Data, Headers
"000552","54058","@TYPO3typo3/dev/translations.php?ONLY=%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/","GET","LIN","TYPO3 allows any file to be retrieved remotely. Upgrade to the latest version.","",""
```

Then i just can use:

``@WIN=/boot.ini /winnt/win.ini /windows/win.ini``
-> Match: ; for 16-bit app support, [boot loader]

``@LIN=/etc/passwd``
-> Match: root:.*:0:[01]:

``@BOTH=/etc/passwd /boot.ini /winnt/win.ini /windows/win.ini``
-> Match: ; for 16-bit app support, [boot loader], root:.*:0:[01]:

internally within the plugin without touching the nikto core functions/methods.

However i don't know if there are any drawbacks when moving the existing tests out of the db_tests into an own plugin?

**Comment by RealRancor** [comment]
First proposal in https://github.com/sullo/nikto/pull/335
