### ISSUE TITLE
Set Arbitrary Headers  

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#23]
Create a method to allow arbitrary headers to be set with every request.
**
Technically this is easy enough, as most stuff routes through nfetch and setup_hash. The only difficult bit is the UI variant, a couple of suggestions:

In nikto.conf:
HEADERS=X-Debug:true X-RevealSource:true

and on the CLI:
-headers X-Debug:true,X-RevealSource:true

**Comment by wrycu** [comment]
Was this accepted or declined? I see that it's quite old and AFAIK still has not been implemented.

**Comment by RealRancor** [comment]
@wrycu The issue here is open and has no commit / pull request reference so its unlikely that it was implemented.

**Comment by tautology0** [comment]
This was copied over from the old assembla bug system and yes it's still open. It should be quite simple to implement - just need an idea of which user interface is preferred (e.g. CLI or conf file).

**Comment by wrycu** [comment]
@RealRancor understood, but the lack of commits / pull requests are not an indication of if the team has accepted it and just hasn't done work on it or not.

@tautology0 I see your point.  At the same time, certainly it's better to have it somewhere than nowhere...  but that's just my two cents.

**Comment by RealRancor** [comment]
@wrycu But a "tag" as enhancement is a indication that its planned or was accepted.
