### ISSUE TITLE
404 False Positives

### ISSUE THREAD

**Issue by ethicalhack3r** [sullo/nikto#246]
I'm having trouble telling Nikto to match 404 pages. The 404 error is a bit of a tricky one.

The page responds with a 200 status and the following body:

```
ERR:/this_is_sent_within_the_url
```

The `ERR:` string is the only static content, the `this_is_sent_within_the_url` string comes from the URL path (reflected xss here).

For example, the following URL would cause the above response:

```
http://www.example.com/this_is_sent_within_the_url
```

I've tried adding `ERR:` to the `db_404_strings` file and the `udb_404_strings` file but Nikto still doesn't flag the pages as 404.

Is there anything else I can do to help Nikto identify these pages as 404?

Running latest Github master code.

**Comment by sullo** [comment]
Hard to say without seeing it. Can you capture a response with -D D and post the actual snippet with the ERR bit? if that doesn't clear it up... then something might be borked in the logic, which would be bad and harder to diagnose!

**Comment by ethicalhack3r** [comment]
Here's one false positive example:

```
D:Wed Apr 22 11:14:29 2015 'Request Hash' = {
  'whisker' => {
    'protocol' => 'HTTP',
    'require_newline_after_headers' => 0,
    'lowercase_incoming_headers' => 1,
    'uri_prefix' => '',
    'ssl_save_info' => 1,
    'http_space2' => ' ',
    'ssl_rsacertfile' => undef,
    'uri_param_sep' => '?',
    'timeout' => 10,
    'http_space1' => ' ',
    'method' => 'GET',
    'force_open' => 0,
    'include_host_in_uri' => 0,
    'ignore_duplicate_headers' => 1,
    'uri_postfix' => '',
    'keep-alive' => 1,
    'ssl' => 1,
    'version' => '1.1',
    'ssl_certfile' => undef,
    'port' => 443,
    'uri' => '/pma/db_details_importdocsql.php?submit_show=true&do=import&docpath=../',
    'host' => 'REDACTED.com',
    'retry' => 0,
    'normalize_incoming_headers' => 1,
    'invalid_protocol_return_value' => 1,
    'force_bodysnatch' => 0,
    'MAGIC' => 31339,
    'max_size' => 0,
    'trailing_slurp' => 0,
    'force_close' => 0,
    'http_eol' => "\r\n"
  },
  'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36',
  'Connection' => 'Keep-Alive',
  'Host' => 'REDACTED.com:443'
};
D:Wed Apr 22 11:14:29 2015 'Result Hash' = {
  'connection' => 'Keep-Alive',
  'whisker' => {
    'protocol' => 'HTTP',
    'lowercase_incoming_headers' => 1,
    'http_space2' => ' ',
    'stats_reqs' => 2938,
    'http_space1' => ' ',
    'code' => 200,
    'ssl_cert_issuer' => '/O=AlphaSSL/CN=AlphaSSL CA - G2',
    'stats_syns' => 2938,
    'ssl_cert_subject' => '/OU=Domain Control Validated/CN=*.REDACTED.com',
    'cookies' => [
      'PHPSESSID=512t48s3292jclhip3llc9kmv7; path=/'
    ],
    'version' => '1.1',
    'data' => 'ERR:/pma/db_details_importdocsql.php?submit_show=true&do=import&docpath=../',
    'uri' => '/pma/db_details_importdocsql.php?submit_show=true&do=import&docpath=../',
    'message' => 'OK',
    'header_order' => [
      'date',
      'server',
      'set-cookie',
      'expires',
      'cache-control',
      'pragma',
        'vary',
      'content-length',
      'keep-alive',
      'connection',
      'content-type'
    ],
    'http_data_sent' => 1,
    'socket_state' => 0,
    'ssl_cipher' => 'DHE-RSA-AES256-GCM-SHA384',
    'MAGIC' => 31340,
    'http_eol' => "\r\n"
  },
  'set-cookie' => 'PHPSESSID=512t48s3292jclhip3llc9kmv7; path=/',
  'cache-control' => 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
  'keep-alive' => 'timeout=5, max=100',
  'date' => 'Wed, 22 Apr 2015 10:17:58 GMT',
  'vary' => 'Accept-Encoding',
  'content-length' => 75,
  'pragma' => 'no-cache',
  'content-type' => 'text/html',
  'server' => 'Apache/2.2.22 (Debian)',
  'expires' => 'Thu, 19 Nov 1981 08:52:00 GMT'
};
+ OSVDB-8450: /pma/db_details_importdocsql.php?submit_show=true&do=import&docpath=../: phpMyAdmin allows directory listings remotely. Upgrade to version 2.5.3 or higher. http://www.securityfocus.com/bid/7963.
```

**Comment by sullo** [comment]
Can you run again with this nikto_core.plugin file? It adds some debug output to the 404 matching. No need for the -D D. 

https://gist.github.com/sullo/3f146e08b43d834ff53b

thanks for your help!

**Comment by ethicalhack3r** [comment]
Hmmm... I just seem to get the same output as using the previous nikto_core.plugin

**Comment by sullo** [comment]
huh. can you confirm is_404 has this (and more) in it? 
sub is_404 {
    my ($uri, $content, $rescode, $loc_header) = @_;
    $ext = get_ext($uri);
    my $debugmode=1;
    print "is_404: \$FoF{\$ext}{'mode'}:$FoF{$ext}{'mode'}\n" if $debugmode;
...

**Comment by ethicalhack3r** [comment]
Yea, it has that in it, here's a quick grep showing some of the lines:

```
$ cat nikto/program/plugins/nikto_core.plugin | grep "print \"is_404:"
    print "is_404: \$FoF{\$ext}{'mode'}:$FoF{$ext}{'mode'}\n" if $debugmode;
    print "is_404: \$rescode:$rescode\n" if $debugmode;
    print "is_404: \$ext:$ext\n" if $debugmode;
    print "is_404: \$loc_header:$loc_header\n" if $debugmode;
    print "is_404: \$uri:$uri\n" if $debugmode;
    print "is_404: \$content:$content\n" if $debugmode;
        print "is_404: return at 1\n";
            print "is_404: return at 2\n";
        print "is_404: return at 3\n";
            print "is_404: return at 4\n";
            print "is_404: return at 5\n";
    print "is_404: return at 5\n$VARIABLES{'DIV'}\n";
```

**Comment by sullo** [comment]
Alright, that was not the right place to debug i guess. Try this, use "-S ." and you'll get a directory auto-named with a file for each finding inside. In each file will be all the important things... but most important is a line that says "Reason". That'll tell us what bit of code is causing it to FP at least.

**Comment by ethicalhack3r** [comment]
Output from one of the -S files is here - https://gist.github.com/ethicalhack3r/4fc129bc761c1d143c8b

Couldn't see anything that mentioned "reason" though.

**Comment by sullo** [comment]
So, I think the lack of a 'reason' pointed to a potential bit of a logic error in the positive handling. I suspect some things were 'falling through' to a positive response when they shouldn't. 

I just committed an update which does an explicit additional check for a positive response. Give it a whirl? Otherwise I'm running out of ideas other than trying to setup a server which responds exactly the same, as the error string should still override.

**Comment by ethicalhack3r** [comment]
That didn't work unfortunately but thanks for all your help!

My testing window has now passed so won't be able to do any more testing to try to identify the problem.

Not sure if you want to leave this issue open or close it?

Thanks again!

**Comment by sullo** [comment]
I'm going to leave it open for now... need to figure out how to recreate this condition if possible. Thanks!

**Comment by rsmith31415** [comment]
@sullo Did you figure this out? I'm having the same issue. I can share an additional log based on the output of "-S .". [This](https://gist.github.com/anonymous/6ed27bb2a293923c408b6152fd2ab5cd) is the gist. I also included a file `udb_404_strings`  inside the databases folder and nikto seems to be reading that file correctly, but there are many false positives.

**Comment by k20stitch** [comment]
Same here, custom 404 pages reported for xss vulnerability

**Comment by sullo** [comment]
@k20stitch can you post some output? been many changes since the original problem posted. Thanks.
