### ISSUE TITLE
new update and git tags

### ISSUE THREAD

**Issue by anthraxx** [sullo/nikto#251]
Hey team,

It would be awesome if you can create a new release. Nikto 2.1.5 was released 2012-09-16, which is kind of ancient if you compare it to the git repository. I would like to package your software for Arch Linux, but it feels kind of bad to have a version thats nearly 3 years only while this project is still active.

Also you would do me a favor if you can tag your releases like 2.1.5 (and the new releases in the future) via a git tag, so github provides source tarballs pointing to a specific commit.

Would really appreciate this to move your package into the repos :smile: 

cheers
Levente

**Comment by sullo** [comment]
I certainly understand your concern. I'm curious though why you can't pull latest git for your release? I ask because I have been thinking of doing away with "releases" entirely and moving to a different model where a stable branch is "it". There are some problems with this I'm aware, but they seem trivial compared to never actually releasing a new version because it's giant pain.

**Comment by anthraxx** [comment]
not sure what you consider 'giant pain' :smile: I mean you don't need to upload tarballs anyware all I'm asking for is a "frequent" kind of releasing via git tags so github has a tarball.
We do not package git HEADS as distribution level of packaging as its unmaintainable because we are not that much aware of the current state of the software for a particular commit then you as devs are, it would be too much work to determine when and which commit should be considered worth for a release.
Please understand that its not possible to package your great software via git HEAD.
To be honest I don't even care about that you greate a website, news entries, changeslogs... the focus i *do* care about is that you know when its in a stable state and then you simply git tag that version so we can pull that tarball from github and create an update for your package.
It would be sad if this will keep us from packaging your great software on a distribution level :cry: 
cheers :smile:

**Comment by sullo** [comment]
The giant pain is on our end and web site, not really git tags :)

So HEAD won't work--I can get that. I confess I'm not a git expert so I'll read about release tags to see how we can implement. I dislike the process we have so I am very willing to find a better way. Appreciate the info and will look into it and update this thread!

**Comment by anthraxx** [comment]
Sure but why do you feel forced to update your website? :yum: 
Summary: all I need to publish your software would be to always have a git tag to all your new stable branches (or also if one "stable" branch got updated).
To sum it up logically: We just need static non-changing tarballs that link a static version string to a particular commit.

If you care about your website, just write there something like: Go to github and look at the release tab/lnik to get your current tarball :yum:

**Comment by anthraxx** [comment]
Oh sorry, half of your mail reply was hidden behind an 'expand' button thingie on the github page.

In case you didn't know: for every git tag, github will create automatically a tarball of that content and publish it on the github page as download. Those tarballs will be available under https://github.com/sullo/nikto/releases

creating tags is pretty easy.

1. If you just want to tag the current head of the current branch (f.e. master or a stable branch):
> git tag 2.1.6

2. If you want to tag a specific (older) commit which is not the current HEAD of the current checked out branch just append the commit hash:
> git tag 2.1.6 228fffa6b178

3. If you want to push the tags to github, you have to add the --tags option (after pushing github magically creates release tarballs on the github page):
> git push --tags

If I can answer you any questions or if there is any way I can support you, just tell me about :smiley: 
cheers

**Comment by anthraxx** [comment]
ping, any news on pushing tags? I really want to ship nikto for Arch Linux :wink:

**Comment by tautology0** [comment]
Give us a few days. We've both been busy with other things over the past couple of weeks so we'll have a look when one of use has had a chance to look at the options.

**Comment by anthraxx** [comment]
I don't want to annoy you... but can you invest some time in this simple topic please? I mean its about your software that someone (me) wants to ship officially for a distribution.... i would have expected that this is something in your interest

**Comment by sbrun** [comment]
Hello
I'm also interested by tagged releases for kali linux distro
Thanks!

**Comment by tautology0** [comment]
I was just looking into this, when I noticed that Sullo did one yesterday! Let us know if this meets your requirements!

**Comment by anthraxx** [comment]
looks perfectly fine for me :+1: 
will use that tag / tarball and release a version for Arch Linux :smile: 

Thanks a lot and don't forget to sometimes create a new tag :stuck_out_tongue_winking_eye: 
have a nice weekend...

**Comment by sbrun** [comment]
yes it's perfect. Thanks!

**Comment by RealRancor** [comment]
Btw. the 2.1.6 tag is probably more a 2.1.7 :grinning:

**Comment by anthraxx** [comment]
think we can close this issue, update is released and homefully there will be more tags in the future :yum:

**Comment by weberhofer** [comment]
An additional question: The changelog file ended in January 2014 - is there a list of at least the release highlights somewhere?

**Comment by RealRancor** [comment]
Mhhhh, seems the Changelog wasn't updated since then. But github provides some sort of "changelog" by comparing commits and tags:

https://github.com/sullo/nikto/compare/6c9fc978e3a1d55a1b30b0bdc3ac1a8545f374fb...2.1.6
