### ISSUE TITLE
Question regarding version 2.1.6

### ISSUE THREAD

**Issue by weberhofer** [sullo/nikto#273]
I have seen a new version tagged on github. Is this a official version? There is no changelog, the public website still shows version 2.1.5 and there is still a open milestone 2.1.6 available. 
Please keep me up to date, as we would like to package it for openSUSE.

**Comment by RealRancor** [comment]
Hi,

the request here: https://github.com/sullo/nikto/issues/251 has lead to the new tag so i think it should be fine to package 2.1.6

**Comment by weberhofer** [comment]
Thank you for the info!
