### ISSUE TITLE
contradiction on Apache version info

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#278]
I've just done a scan and got this message:

```
+ Apache/2.2.29 appears to be outdated (current is at least Apache/2.4.12). Apache 2.0.65 (final release) and 2.2.29 are also current.
```

which says that 2.2.29 is outdated and current at the same time.

**Comment by sullo** [comment]
Yeah that is a bit of a confusing statement, but at the moment I can only compare "Apache" to one version so I have to go with the highest. I committed a change (https://github.com/sullo/nikto/commit/b0cd3f4cf4abc901b63ba2766b0499f729c5c487)  to try and make it a bit more clear, and also updated the versions to current levels.
