### ISSUE TITLE
broken http header entry in save file

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#286]
Not sure if its just for these findings (999960 and 999961) but in the save file the response headers look like this:

```
HTTP/1.1 200 OK
date: Mon, 05 Oct 2015 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
set-cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:11:14 GMT
keep-alive: timeout=10, max=20
```

when they should look like this:

```
HTTP/1.1 200 OK
Date: Mon, 05 Oct 2015 09:47:06 GMT
Set-Cookie: APSCOOKIE_111=“0%260”; path=/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: log_filters=“111”; path=/log/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: log_type=“111”; path=/log/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: just_logged_in=“111”; path=/system/status/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: opmode=“111”; path=/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: csrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Set-Cookie: ccsrftoken=“111”; path=/; expires=Sun, 17-Oct-1965 09:47:06 GMT
Content-Type: text/html
X-Frame-Options: SAMEORIGIN
```

Looks like you've forgotten to increment the string that is being saved.

**Comment by tautology0** [comment]
This is worrying me as the -Save file just dumps what's in the whisker hash; which means that there may be a bug upstream. Can you reproduce this? Try doing a:

./nikto.pl -host <target> -Save -Plugins "cookies(debug)" -no404

To minimise requests.

Also 999960 and 61 (cookie flags) really oughtn't be alerting on expired cookies. I guess I'd better raise a separate bug for that.

**Comment by digininja** [comment]
That command resulted in 2 requests and nothing found. I don't normally run individual plugins so don't know if that format is correct or not.

And the expired cookies, I wrote a new issue after this one then deleted it as pedantic gut feeling was that even when clearing cookies the flags should be set. Still not sure about it though.

**Comment by wireghoul** [comment]
Looks like there is a hash key collision in LW2 unless you set the save_cookie option, LW2.pl line 907 onwards.

**Comment by sullo** [comment]
@wireghoul I don't think that's it--that's in the crawl() function and we don't use the crawler at all. 

@digininja I tried to recreate this with this code:
`<?php
setcookie("a","b");
setcookie("c","d");
print "PHP Version";
?>
`

However, the save file looks like this:
`-----------------------------------------------------------------------
			  Response
-----------------------------------------------------------------------
HTTP/1.1 200 OK
date: Mon, 08 Feb 2016 05:45:31 GMT
server: Apache/2.4.7 (Ubuntu)
x-powered-by: PHP/5.5.9-1ubuntu4.14
set-cookie: c=d
set-cookie: c=d
content-length: 12
...
`

Are you able to reproduce this or have you seen it agian?

**Comment by wireghoul** [comment]
@sullo Your example reproduced it, it's repeating `c=d` twice instead of `a=b` and `c=d` which is what's set by the server:
```
Connection: close
Date: Mon, 08 Feb 2016 07:00:57 GMT
Server: Apache
Vary: Accept-Encoding
Content-Length: 11
Content-Type: text/html
Client-Date: Mon, 08 Feb 2016 07:00:57 GMT
Client-Peer: 127.0.0.1:80
Client-Response-Num: 1
Set-Cookie: a=b
Set-Cookie: c=d
```

**Comment by sullo** [comment]
Whoops--not paying enough attention and too tired. Thanks!
