### ISSUE TITLE
Cookie flag issues raise when the cookie is expired

### ISSUE THREAD

**Issue by tautology0** [sullo/nikto#287]
If a cookie has been issued with a date in the past, then cookie flag issues, such as the cookie lacking httponly or secure are still being raised, when they're pretty toothless.

**Comment by digininja** [comment]
How far into the past are you going to allow?

My head says I agree with this, pedantic gut says no, it is still setting
the cookie and missing the flags. If the server was set up to use secure
and httponly flags then they would be set here as well as when setting them
for real. In this app I can't log in so I'm raising this as a concern and
telling the client to check what happens after a login when the cookies are
set real values.

**Comment by tautology0** [comment]
I've just tried it in all three browsers that I've got installed (Chrome, Firefox and Internet Exploder). All three remove the cookie from document.cookie as soon as the cookie expires. So there is no impact from having a cookie expiration header even without httponly or secure.

(I haven't tested an Edge based browser, or Safari but I suspect that'll be the same as Chrome.)

**Comment by digininja** [comment]
But doesn't it suggest that the server hasn't been configured to set the
flags which means it is worth highlighting for the times that the cookies
are set with real values?

I agree that these cookies are not problems

**Comment by tautology0** [comment]
You have a good point. Now I'm confused as what to think ;-)

**Comment by digininja** [comment]
Exactly the same here. I've written it up as a low with a note to the
client to check what happens when the real cookies are set and to increase
the risk if the flags are still missing.

I think it is worth leaving in as a check, would you be able to flag
they've expired in some way?
