### ISSUE TITLE
Multiple basic auth failures

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#300]
I'm scanning a bunch of sites and I've hit one that requires basic auth, the Nikto output is a stream of:

```
+ / - Requires Authentication for realm 'x'
+ / - Requires Authentication for realm 'x'
+ / - Requires Authentication for realm 'x'
```

Would it would make sense that if one test finds authentication required for a directory then it assumes all other tests for that directory will and so skips them? Or is there a chance that certain files in a directory do not require auth?

**Comment by tautology0** [comment]
On Mon, 16 Nov 2015 22:10:51 -0000, Robin Wood <notifications@github.com>  
wrote:
>
> I'm scanning a bunch of sites and I've hit one that requires basic auth,  
> the Nikto output is a stream of:
> + / - Requires Authentication for realm 'x'
> + / - Requires Authentication for realm 'x'
> + / - Requires Authentication for realm 'x'
>
> Would it would make sense that if one test finds authentication required  
> for a directory then it assumes all other tests for that directory will  
> and so skips >them? Or is there a chance that certain files in a  
> directory do not require auth?
It's meant to do that! Any chance of seeing why this is happening on that  
site, the easiest way to do this is to switch on verbose mode for the auth  
module by adding a -Plugins switch:

-Plugins '+;auth(verbose)'

**Comment by digininja** [comment]
Just tried that and didn't get any extra output

```
$ ./nikto.pl -host https://site.com   -Save nikto/https_site.save2 -Plugins '+;auth(verbose)'
```

just the string of auth message again. Looking in the save folder I get 6 files which tallies with this from the end of the report:

```
+ 7794 requests: 0 error(s) and 6 item(s) reported on remote host
+ End Time:           2015-11-18 21:45:10 (GMT0) (2836 seconds)
```

5 are about host headers, the last about the cert not matching.




On 17 November 2015 at 00:09, David Lodge <notifications@github.com> wrote:

    On Mon, 16 Nov 2015 22:10:51 -0000, Robin Wood <notifications@github.com>
    wrote:
    >
    > I'm scanning a bunch of sites and I've hit one that requires basic auth,
    > the Nikto output is a stream of:
    > + / - Requires Authentication for realm 'x'
    > + / - Requires Authentication for realm 'x'
    > + / - Requires Authentication for realm 'x'
    >
    > Would it would make sense that if one test finds authentication required
    > for a directory then it assumes all other tests for that directory will
    > and so skips >them? Or is there a chance that certain files in a
    > directory do not require auth?
    It's meant to do that! Any chance of seeing why this is happening on that
    site, the easiest way to do this is to switch on verbose mode for the auth
    module by adding a -Plugins switch:

    -Plugins '+;auth(verbose)'

**Comment by NemosDemos** [comment]
If it helps at all, this error (in my case) was caused by requests with unsupported/unprivileged HTTP verbs (e.g. TRACK/TRACE/PROPFIND).
