### ISSUE TITLE
Sync db_favicon with OWASP favicon database

### ISSUE THREAD

**Issue by RealRancor** [sullo/nikto#304]
Hi,

currently consider the sync of the db_favicon against the https://www.owasp.org/index.php/OWASP_favicon_database.

That DB currently contains 248 favicon md5s which are also partly available in the 118 entries of the nikto db_favicon.

To create a db_favicon compatible list we can easily do:

```
awk -F':' '{if (id == 0) id = 500500; id++; $3=id} {print "\""id"\",\""$1"\",\""$2"\""}' favicons.txt
```

and filter out duplicate entries with #303 .

To sync both databases i could do the following:

1. Import OWASP favicon db into db_favicon of Nikto
2. Kickout duplicate entries of db_favicon (The older ones starting with 5000xx - 5001xx)
3. Submit the rest of the missing favicons to the OWASP db
4. Sync both databases again

@sullo Is that o.k. for you or are there any licence problems concerning the sync between both databases?

**Comment by tautology0** [comment]
We did do this about 4 years ago and talked to the OWASP people (I think I even got granted commit rights to the OWASP project over this), but we haven't actually resynced for a while. I'd have to check my email archives for the details (as it was on an old email account).

The licence is CC, which does allow us to reuse their data, so, I'd say go ahead and do it. Sullo and I can work out the details and accept or reject the commit as appropriate.

**Comment by RealRancor** [comment]
Ah, thanks for the background info. Have created #305 which has now the same order as the OWASP wiki.

Seems they have one duplicate md5sum "389a8816c5b87685de7d8d5fec96c85b"  and 11 md5s from the db_favicon not included:

```
"500017","4987120f4fb1dc454f889e8c92f6dabe","Google Web Server"
"500108","c0dc2e457e05c2ce0a99886ec1048d77","Platform Computing Corporation Platform Management Console Version v2.0"
"500109","92d0841188d40b6fef294cf53a8addd7","cPanel cpsrvd webmail server"
"500110","9afa5d60e5ef15dc75d7662e418cac72","QNAP TurboNAS"
"500111","5f09cded07bb864fd9b3d2dd72b5418e","TwonkyServer Premium 7.0.x"
"500112","773669c6c97d65ac5ede9e8ea6b47116","Plex Media Server 0.9.x"
"500113","46b742e6ba5d7ac03f13b312601c113f","XBMC Media Center 12.x (Web Interface)"
"500114","88733ee53676a47fc354a61c32516e82","Magento Go CMS"
"500115","6d2adf39ca320265830403dfc030033a","Liferay Portal"
"500117","297d726681297cbf839f43a125e5c9b4","ZNC IRC Bouncer (Web Interface)"
"500118","d577e9569381685b30feae22484c8344","ZNC IRC Bouncer (Web Interface)"
```

Can we submit this somehow to them without creating a wiki account?
