### ISSUE TITLE
Feature request OWA

### ISSUE THREAD

**Issue by drwetter** [sullo/nikto#307]
Hi,

http://foofus.net/?p=758

manually;

```
openssl s_client -host TARGETIP -port TARGETPORT

GET /autodiscover/autodiscover.xml HTTP/1.0
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
Accept-Language: en
Connection: Keep-Alive
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Pragma: no-cache
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*
```

To parse is then the value of "WWW-Authenticate: Basic realm="

Cheers, Dirk

**Comment by RealRancor** [comment]
@sullo

Is it even possible to use HTTP/1.0 and set no host header within the db_tests?

**Comment by sullo** [comment]
@RealRancor you are right; you can't set the http version except globally when using db_tests (might be able to override the Host header but i think it'd just send a blank one). This would need a custom call to craft a request by hand, and that can only be done inside a plugin unfortunately.

**Comment by RealRancor** [comment]
Mhhh, so the main question if it makes sense to put effort into a plugin for such a information disclosure?

**Comment by tautology0** [comment]
I looked at OWA a while back, but never went anywhere with it.

I suppose it depends on what information we get from the autodiscover.xml  
file, I tried it with a couple and all I got back was the (Internet)  
domain name in the authenticate header.

**Comment by RealRancor** [comment]
According to the article http://foofus.net/?p=758 its an internal IP info disclosure. Personally i'm rating something like this as "low" so from my PoV its not worth to put any effort into this.

**Comment by tautology0** [comment]
I'll have a look tomorrow when I've got my nikto laptop switched on and  
see what I can see.

**Comment by drwetter** [comment]
Am 12/28/2015 um 05:21 AM schrieb sullo:
> @RealRancor <https://github.com/RealRancor> you are right; you can't set the http version
> except globally when using db_tests (might be able to override the Host header but i think it'd
> just send a blank one). This would need a custom call to craft a request by hand, and that can
> only be done inside a plugin unfortunately.

wouldn't it generally make sense to have a  HTTP/1.0 functionality, i.e. without "Host:" header?

Cheers, Dirk

**Comment by RealRancor** [comment]
@drwetter Just remembered that i have seen something like this in the last few weeks during an audit. But that wasn't an IIS/OWA but an nginx which exposed the internal ip within the Location redirect:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 29 Dec 2015 14:03:01 GMT
Content-Type: text/html
Content-Length: 178
Location: https://10.8.0.1/abc
Connection: close

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

As this is not only IIS/OWA specific it indeed would make sense to have an plugin for this like Nessus for example:

https://www.tenable.com/plugins/index.php?view=single&id=10759

**Comment by RealRancor** [comment]
Example for IIS: http://www.securityfocus.com/bid/1499/discuss

**Comment by tautology0** [comment]
There is - it's in headers ;-)

**Comment by RealRancor** [comment]
Yes, the internal IP is disclosed within the header if no host header and an HTTP/1.0 is specified. Up to now i have seend three different locations where the IP was included:

1. WWW-Authenticate: Basic realm=”10.1.1.10″
2. Location: https://10.8.0.1/abc
3. Content-Location: http://10.1.1.1/Default.htm

**Comment by tautology0** [comment]
All three of those cases are already looked for in nikto_headers.plugin,  
and there's a general one that looks for an IP address in various other  
headers.

The OWA is a special case which will need to be coded., which we can  
probably do by adding another GET request to the nikto_headers sub around  
lines 251 - 273 of nikto_headers.plugin (I'd be tempted to change this to  
a foreach as well to reduce code size).

**Comment by RealRancor** [comment]
Mhhh, but the three cases are not checked for this special HTTP/1.0 / No host header within the headers plugin or am i wrong?

**Comment by tautology0** [comment]
They do through some mangling of the LW API. They basic call is:

nfetch($mark, '/', "GET", "", \%locheaders, \%flags, "headers: IIS  
internal IP", "1.0")

Where %locheaders is the hash of custom headers, as %flags contains the  
noclean flag this means that the Libwhisker cleanup call is never called,  
so results in a request with no host header.

That "1.0" at the end of nfetch is the HTTP version.

(So yes you could probably add stuff through HTTP/2.0 as well, though LW  
hasn't been tested with HTTP/2.0 yet).

nfetch is documented (albeit, briefly) at  
https://cirt.net/nikto2-docs/expanding.html#id2794198 although this seems  
to miss out the $httpver parameter - I must have added it after I  
documented nfetch.

**Comment by tautology0** [comment]
It looks like this check had been messed up at some point. I've made some  
changes to try and fix it, although I don't have anything to test it  
against at the moment.

The only OWA box I can use does not appear to be vulnerable.

**Comment by RealRancor** [comment]
Hey, will test that later. But from what i can see the headers plugin is not checking case 1.?

**Comment by drwetter** [comment]
@tautology0 

https://www.google.com/search?q='outlook+web+app'
https://www.shodan.io/search?query=%27outlook+web+access%27

**Comment by drwetter** [comment]
Am 12/29/2015 um 03:10 PM schrieb RealRancor:
> @drwetter <https://github.com/drwetter> Just remembered that i have seen something like this in
> the last few weeks during an audit. But that wasn't an IIS/OWA but an nginx which exposed the
> internal ip within the Location redirect:
> 
> |HTTP/1.1 301 Moved Permanently Server: nginx Date: Tue, 29 Dec 2015 14:03:01 GMT Content-Type:
> text/html Content-Length: 178 Location: https://10.8.0.1/abc Connection: close <html>
> <head><title>301 Moved Permanently</title></head> <body bgcolor="white"> <center><h1>301 Moved
> Permanently</h1></center> <hr><center>nginx</center> </body> </html> |
> 

For my child I am fostering (https://github.com/drwetter/testssl.sh) I am looking at the header and
report any IPv4 addresses. If you need a server for testing feel free to use https://dev.testssl.sh
(the IPv4 vhost, IPv6 is different).

Cheers, Dirk

**Comment by RealRancor** [comment]
Check for WWW-Authenticate in https://github.com/sullo/nikto/pull/312

**Comment by tautology0** [comment]
This may be superflous as it does it earlier in  nikto_headers_postfetch  
as a generic test for RFC1918 addresses (postfetch hooks are executed  
after every call to nfetch).

We should probably keep the code consistent - and only have it in the main  
nikto_headers function if and only if it requires HTTP/1.0.


On Wed, 30 Dec 2015 14:28:33 -0000, RealRancor <notifications@github.com>  
wrote:

>
> Check for WWW-Authenticate in #312
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by RealRancor** [comment]
The www-authenticate ip disclosure requires HTTP/1.0 as described in the initial advisory http://foofus.net/?p=758
