### ISSUE TITLE
Cant set cookie that has semi-colon char

### ISSUE THREAD

**Issue by chppppp** [sullo/nikto#325]
I want to set a cookie like:

``````
```STATIC-COOKIE="blablaID=dq938d98nf89f; super=1"```
``````

but this doesnt work! it thinks the semi colon is separating cookies. 

Also, the cookie doesnt send without sending
`STATIC-COOKIE="cookie1"="blablaID=dq938d98nf89f; super=1"`
but if course, it sends the cookie1= part as well! 

Would love to be able to pass the first static-above above successfully. 

Thanks!!! Love Nikto!

**Comment by sullo** [comment]
Sorry this got skipped for a long time, however I think recent changes actually fix this.
