### ISSUE TITLE
nikto_favicon.plugin: Some issues within <link check

### ISSUE THREAD

**Issue by ghost** [sullo/nikto#333]
While checking nikto_favicon.plugin for https://github.com/sullo/nikto/issues/330 i've noticed three problems in the <link check:

`<link rel="shortcut icon" href="http://example.com/myicon.ico" />`
-> The plugin will call `http://example.com/myicon.ico` in the GET request which very likely will fail

`<link rel="shortcut icon" href="/foo/myicon.ico" />`
-> The plugin will call `/foo/foo/myicon.ico` if nikto is started with the `-r /foo` parameter

 `<link rel="shortcut icon" href="/foo/myicon.ico" />` and
 `<link rel="icon" href="/foo/myicon.ico" />` together
-> The plugin will only pick the second link/icon

**Comment by sullo** [comment]
i don't think checking for /foo/foo is invalid, since -r should be prepended to every test... it may not be what a user wants but it is what they asked for. I think?

**Comment by RealRancor** [comment]
Hey,

will test the first issue in the next few days. The last issue is tested and i can confirm that it is fixed. 

The second issue is still there. I'm not quite sure how this can be avoided at all. Maybe if -r /foo is specified and the href contains /foo it will be removed from it?

**Comment by sullo** [comment]
Were you able to retest this one?

**Comment by RealRancor** [comment]
Ah, sorry. Yes, just forgot to give feedback here. :-)

``<link rel="shortcut icon" href="http://example.com/myicon.ico" />`` -> Works

``<link rel="shortcut icon" href="/foo/myicon.ico" />`` with -r /bar -> Still get "/bar/foo/myicon.ico" and is failing

``<link rel="shortcut icon" href="/foo/myicon.ico" />`` and
``<link rel="icon" href="/foo/myicon.ico" />`` together -> Works

**Comment by wireghoul** [comment]
I would argue that `-r /bar` works as intended, nikto should not scan outside the specified scope. This issue can probably be closed

**Comment by sullo** [comment]
Agree; works as intended.
