### ISSUE TITLE
Common uncommon header - public key pinning

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#345]
Nikto doesn't know about public key pinning:

```
+ Uncommon header 'public-key-pins' found, with contents: pin-sha256="PC8YX6AoWmO89PL+fzdUHehVtyswgWd9/TKORapTh+M="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys="; pin-sha256="c9GlBoanJem0NjIBFIwG+BiqH2HkjC5xyS5e+knKSeg=" ; report-uri="https://report-uri.io/report/digininja"; max-age=5184000;
```

It might be nice to have something pull out the report-uri field as an interesting field. And if you are going to do that, may as well get the report uri from the CSP header as well.

**Comment by tautology0** [comment]
Oops, missed this header. I'll try and remember to add it tomorrow.

Is it me or are HTTP headers getting very heavy now. I think I'd like to see a generic HTTP-Security-Options header to replace a lot of the others...

**Comment by digininja** [comment]
You mean a new standard to replace all the other standards? :)

**Comment by tautology0** [comment]
CLosed as PKPs is considered harmful
