### ISSUE TITLE
Reissue requests through proxy

### ISSUE THREAD

**Issue by strawp** [sullo/nikto#349]
It would be cool to be able to specify a proxy which Nikto would send a request through if it thinks it had found something. I've made the mistake of proxying a whole scan through Burp before and ended up with a huge site map of false positives. This way it would make Nikto's findings easier to verify and map out.

**Comment by sullo** [comment]
Interesting idea--I did that exact thing in cms-explorer, but never thought
to move that idea over here.

Right now you can do -Savefile (like "-S ." ) and this will create files
with text and json output of findings. You can then use the included
replay.pl to send them through a proxy to capture in burp. It will also
save you full request/response which most of the reports don't include.

-Sullo


On Wed, Mar 30, 2016 at 8:34 AM, Iain Wallace <notifications@github.com>
wrote:

> It would be cool to be able to specify a proxy which Nikto would send a
> request through if it thinks it had found something. I've made the mistake
> of proxying a whole scan through Burp before and ended up with a huge site
> map of false positives. This way it would make Nikto's findings easier to
> verify and map out.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/issues/349>
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by strawp** [comment]
Oh nice, didn't know about replay. Was half way through doing some bash-fu to parse the savefiles. That certainly works as a nice intermediary solution

**Comment by tautology0** [comment]
It's a good idea and one that could be easy to implement by adding a new report plugin. It would have been easier if I'd actually got around to making the change to reporting/logging I've been meaning to for about four years.

I'll have a think about it. Until now, replay.pl makes a good part time solution.

**Comment by sullo** [comment]
Closing because -Savefile and replay.pl exist. Not changing this in perl version.
