### ISSUE TITLE
Consolidate db_tests pass/fail fields  

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#37]
Regular expressions invalidate the need for multiple pass/fail match fields in db_tests. We should consolidate them to a single match field and a single fail field. A single field for each will let us do easy alternation for pass or fail matching, but keep us from having to use fairly expensive lookarounds for negative matching and both pass/fail conditions.

**Comment by iasdeoupxe** [comment]
Noticed this while getting familiar with the syntax of the db_tests as well.

I think this could be a good improvement for the db_tests because e.g. the "Match 1 Or" is mostly unused.

**Comment by sullo** [comment]
Won't do.
