### ISSUE TITLE
Error Hash Iterator

### ISSUE THREAD

**Issue by darioajr** [sullo/nikto#373]
Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x17d6010 at /root/nikto-2.1.5/plugins/LW2.pm line 1013.

Command: shell_exec("perl /root/nikto-2.1.5/nikto.pl -host ".$servidor." -Format htm -output /var/www/site/public_html/nikto/".$servidor.".html");
Environment: Ubuntu 14.04 64bits
Memory: 2GB

**Comment by opt9** [comment]
It's #142

**Comment by darioajr** [comment]
Error on 2.2.0 version

 perl nikto.pl update
Can't locate /root/nikto/plugins/JSON-PP.pm in @INC (you may need to install the ::root::nikto::plugins::JSON-PP module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at nikto.pl line 60.

**Comment by darioajr** [comment]
this version is 2.1.6 not 2.2.0

**Comment by darioajr** [comment]
+ ERROR (404): Unable to get cirt.net/nikto/UPDATES/2.1.6/versions.txt

**Comment by opt9** [comment]
Sorry for your inconvenience.
Please don't use -update option.

Please download [Nikto 2.2.0](https://github.com/sullo/nikto/archive/2.2.0.zip), unzip and use it.
Version number is not changed, so it prints you are using 2.1.6.

FYI, 
1. Version number mismatch is the well known problem.
2. Update problem is the well known problem.

IMHO, we must change our workflow, and automate something.

p.s. I'm not a maintainer or an official project member, just a voluntary contributor and a normal user like you ;-)

**Comment by sullo** [comment]
2.2.0 is needed desperately... beyond the massive changes from 2.1.5 -> now, I've highlighted only a few more open bugs to solve for 2.2.0, the most important two being the removal of OSVDB references (already done) and the updater (not done).

**Comment by sullo** [comment]
So I'm still not sure if this is a problem and in which version? @darioajr can you clarify the original each() issue's version?
