### ISSUE TITLE
"lines"

### ISSUE THREAD

**Issue by mubix** [sullo/nikto#385]
Not sure where this finding came from but I got this:
```
+ lines
```

**Comment by mubix** [comment]
If it helps its against a Lotus Domino server, and it's between "No CGI Directories found" and "Uncommon header" findings

**Comment by tautology0** [comment]
A quick grep shows me that its coming from the clientaccesspolicy plugin, not certain how its happening, but I'll have a look when I can find some free time. I'm guessing an errant line feed somewhere.

Is there any chance you can replay this using the -Save option which should save the details about where it is been raised.

**Comment by sullo** [comment]
http://img.memecdn.com/thats-my-line_o_290428.jpg

Rob you sure you're up to date? I think I fixed this recently when I saw it, with this commit:
https://github.com/sullo/nikto/commit/47ddb29d690db806f5cd6170362a7d8fe984b58c

If you are up to date I clearly didn't fix it all/right, so the req/res with -S or debug out would be quite helpful.

**Comment by mubix** [comment]
Sorry, I was in fact running an outdated version when I didn't think I was

**Comment by sullo** [comment]
No worries. thanks!
