### ISSUE TITLE
RFC1918 check

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#399]
Just had this come up and was wondering if it would be possible to add a check to see if the value really was an RFC1918 address rather than just say "may reveal"

```
+ OSVDB-5737: WebLogic may reveal its internal IP or hostname in the Location header. The value is "http://213.1.2.3/default/400.html".

**Comment by sullo** [comment]
It's supposed to check it vs the host's name and ip. Does it resolve to multiple values or a different value?

**Comment by digininja** [comment]
The IP it reports matches what you detect as the IP here:

```
+ Target IP:          213.1.2.3.4

**Comment by sullo** [comment]
Can you see if https://github.com/sullo/nikto/commit/260778b291027b91af2a1890b6f1cb7fd82ffb82 fixes it? I think it should. It was a different bit that checked for an internal vs same IP, which this should have done as well.

**Comment by digininja** [comment]
That fixed it.
