### ISSUE TITLE
nikto Authenticated scan is not working with id and password

### ISSUE THREAD

**Issue by jitendriya09** [sullo/nikto#404]
Hello
I was trying to do an authenticated scan using nikto, using below command
nikto -output output.xml -host demo.testfire.net –p 80 –id admin:admin
but it seems it is not working, because i tried with 2 more option
1)without authenticated scan
nikto -output output.xml -host demo.testfire.net –p 80
2)authenticated scan with random(illegal) id and password
nikto -output output.xml -host demo.testfire.net –p 80 –id abcde:12345

All the options gave same output. Moreover illegal id and password also did not give any problem.
So i think the authenticated scan is not working for nikto.

Please help me if i am doing anything wrong to do authenticated scan.
Thanks in advance

Regards
jitendriya

**Comment by sullo** [comment]
I don't see that demo.testfire.net is requiring or requesting authentication.

**Comment by jitendriya09** [comment]
Hello
The home page does not require any authentication but there is signin option which can be done using admin:admin

**Comment by sullo** [comment]
The site uses form based authentication and you are trying to use header based authentication (basic, ntlm, etc). To use this type of auth you would need to capture the cookies or values set by the server post auth and put them in nikto.conf.
