### ISSUE TITLE
CAS internal IP reported twice

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#407]
Just had this from a scan:

```
+ OSVDB-630: Microsoft Exchange Systems (CAS and OWA) may reveal the internal or real IP in the WWW-Authenticate header via a request over HTTP/1.0. The value is "10.1.123.10".
+ OSVDB-630: Microsoft Exchange Systems (CAS and OWA) may reveal the internal or real IP in the WWW-Authenticate header via a request over HTTP/1.0. The value is "10.1.123.10".
```

The two lines are next to each other.

Checking the save file, the contents are duplicated so looks like the plugin has been ran twice for some reason. I can only see one instance of this in the plugins directory so not sure what is going on

**Comment by digininja** [comment]
Just spotted the difference, one of the requests has basic auth added to it. Needs deduplication in reporting.

**Comment by sullo** [comment]
I don't understand why the path wasn't reported. It should be no matter what the request. 

The whole thing is a loop with multiple request files--but each potential spot leaking an internal IP should be reported only once. There was a bug in that the www-auth one could be reported multiple times. I think that will fix the double report, but not sure why you don't have a path for each one.

**Comment by digininja** [comment]
Double reporting was fixed but still no directory in there:

```
+ OSVDB-630: GET Microsoft Exchange Systems (CAS and OWA) may reveal the internal or real IP in the WWW-Authenticate header via a request over HTTP/1.0. The value is "10.1.123.10".

**Comment by wireghoul** [comment]
Pull request #476 was just merged and fixes the missing uri
