### ISSUE TITLE
not quite xss

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#408]
This is reported as XSS and while the querystring is echo'd back the response code is 302 so it won't trigger in most browsers. Need to add a response code check as well as content.

```
HTTP/1.1 302 Object Moved
location: https://citrix.xxx.co.uk/catinfo?<u><b>TESTING
content-type: text/html
cache-control: private
connection: close

<head><body> This object may be found <a HREF="https://citrix.xxx.co.uk/catinfo?<u><b>TESTING">here</a> </body>

**Comment by sullo** [comment]
I updated the test... no reason it can't check for "> and be a real xss. I can't find any info on this catinfo XSS so the usefulness of the test is in question.

Regarding not being a vuln if it's a 302...  I can't control the client side, so I'd report it to a client (maybe lower severity or mitigating factors, but I'd still report it!). We could argue that over a beer.

**Comment by digininja** [comment]
I was debating putting it in regardless, might add it.
