### ISSUE TITLE
Web Hosting Question

### ISSUE THREAD

**Issue by BinaryResolved** [sullo/nikto#409]
So I am trying to scan a target that is hosted by a semi big web hosting company. However when I scan the target it scans the web hosts nameserver, so I get all the info from every website pointed to that nameserver. Also I can not tell which one is my target or some other company since I can't connect to the nameserver by IP. Is there a workaround for this?

**Comment by BinaryResolved** [comment]
Accidentally hit enter not tab, whoops.

**Comment by sullo** [comment]
Not sure exactly what you mean here... and without the command we can't really help. Please supply that.

**Comment by BinaryResolved** [comment]
Sorry I was a bit vague. So say I run command `172.227.98.172` it would scan every website pointed to that DNS server(not nameserver as I said before). And if I add a `-output C:\Users\Phillip\Desktop\ExampleScan.html` and say I clicked on the link it gave me vulnerability. Then I will get something related to "Invalid URL". I'm not sure if there's a way to get a different URL that points to the nameserver not the DNS server?

**Comment by sullo** [comment]
Still need your commands. Change ips if you need to put out the exact command.

**Comment by BinaryResolved** [comment]
Commands are `perl nikto.pl -h 172.227.98.172  -output C:\Users\SomeUser\Desktop\ExampleScan.html`

**Comment by tautology0** [comment]
They're using virtual hosting on the server. You need to supply the virtual host name by using -vhost.

IIRC if you use the hostname in the -host switch it should just target that virtual host.

**Comment by BinaryResolved** [comment]
@tautology0 Thanks.
