### ISSUE TITLE
No webserver found

### ISSUE THREAD

**Issue by dolevf** [sullo/nikto#410]
hi there,
attempting to run a regular scan against a wordpress website. nikto is unable to proceed, throwing an error of: No web server found.

I've looked up this issue but couldn't identify a possible workaround. tried using a regular ip, tried with the -nossl flag and without it. tried setting vhost as well.

below is a DEBUG of nikto runtime.

root@kali1:~# nikto -Display D -h redacted.com -nossl
D:Mon Aug  8 15:34:26 2016 - Loading DB: /var/lib//nikto/databases/db_parked_strings
D:Mon Aug  8 15:34:26 2016 - Loading DB: /var/lib//nikto/databases/db_404_strings
D:Mon Aug  8 15:34:26 2016 - Loading DB: /var/lib//nikto/databases/db_outdated
D:Mon Aug  8 15:34:26 2016 - Loading DB: /var/lib//nikto/databases/db_variables
D:Mon Aug  8 15:34:26 2016 - Loading DB: /var/lib//nikto/databases/db_tests
- Nikto v2.1.6
---------------------------------------------------------------------------
D:Mon Aug  8 15:34:26 2016 WARNING: No init found for nikto_core

D:Mon Aug  8 15:34:46 2016 'Request Hash' = {
        'Host' => 'redacted.com',
        'whisker' => {
                'protocol' => 'HTTP',
                'ssl_rsacertfile' => undef,
                'retry' => 0,
                'invalid_protocol_return_value' => 1,
                'uri_param_sep' => '?',
                'normalize_incoming_headers' => 1,
                'keep-alive' => 1,
                'http_space1' => ' ',
                'force_bodysnatch' => 0,
                'force_open' => 0,
                'host' => 'redacted.com',
                'ssl_certfile' => undef,
                'MAGIC' => 31339,
                'method' => 'HEAD',
                'force_close' => 0,
                'ignore_duplicate_headers' => 1,
                'uri' => '/',
                'ssl_save_info' => 1,
                'lowercase_incoming_headers' => 1,
                'timeout' => 10,
                'version' => '1.1',
                'include_host_in_uri' => 0,
                'ssl' => 0,
                'require_newline_after_headers' => 0,
                'port' => 80,
                'uri_postfix' => '',
                'http_eol' => "\r\n",
                'trailing_slurp' => 0,
                'uri_prefix' => '',
                'max_size' => 0,
                'http_space2' => ' '
        },
        'Connection' => 'Keep-Alive',
        'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)'
};
D:Mon Aug  8 15:34:46 2016 'Result Hash' = {
        'whisker' => {
                'lowercase_incoming_headers' => 1,
                'data' => '',
                'error' => 'error reading HTTP response',
                'MAGIC' => 31340,
                'uri' => '/',
                'http_data_sent' => 1
        }
};
D:Mon Aug  8 15:35:06 2016 'Request Hash' = {
        'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)',
        'Connection' => 'Keep-Alive',
        'whisker' => {
                'normalize_incoming_headers' => 1,
                'http_space1' => ' ',
                'keep-alive' => 1,
                'protocol' => 'HTTP',
                'invalid_protocol_return_value' => 1,
                'ssl_rsacertfile' => undef,
                'retry' => 0,
                'uri_param_sep' => '?',
                'force_close' => 0,
                'ignore_duplicate_headers' => 1,
                'uri' => '/',
                'ssl_save_info' => 1,
                'force_bodysnatch' => 0,
                'force_open' => 0,
                'method' => 'GET',
                'ssl_certfile' => undef,
                'MAGIC' => 31339,
                'host' => 'redacted.com',
                'timeout' => 10,
                'version' => '1.1',
                'include_host_in_uri' => 0,
                'require_newline_after_headers' => 0,
                'ssl' => 0,
                'lowercase_incoming_headers' => 1,
                'uri_prefix' => '',
                'max_size' => 0,
                'http_space2' => ' ',
                'port' => 80,
                'uri_postfix' => '',
                'http_eol' => "\r\n",
                'trailing_slurp' => 0
        },
        'Host' => 'redacted.com'
};
D:Mon Aug  8 15:35:06 2016 'Result Hash' = {
        'whisker' => {
                'lowercase_incoming_headers' => 1,
                'data' => '',
                'MAGIC' => 31340,
                'error' => 'error reading HTTP response',
                'uri' => '/',
                'http_data_sent' => 1
        }
};
+ No web server found on redacted.com:80
---------------------------------------------------------------------------
+ 0 host(s) tested
D:Mon Aug  8 15:35:07 2016 T:Mon Aug  8 15:35:07 2016: Ending

**Comment by sullo** [comment]
Can you connect via command line or a proxy and grab the results of a simple GET request, e.g.
GET / HTTP/1.1
Host: redacted.com

and paste them here? this is going to be tough to debug w/o direct access but that may trigger something.

**Comment by digininja** [comment]
Worth trying curl as well.

**Comment by dolevf** [comment]
@sullo:
**with netcat:**
DNS fwd/rev mismatch: redicated.com != ip-redicated.com
redicated.com [re.da.c.ted] 80 (http) open
**GET / HTTP/1.1**

HTTP/1.1 400 Bad Request
Date: Mon, 08 Aug 2016 23:26:19 GMT
Server: Apache/2.4.18
Accept-Ranges: bytes
Vary: Accept-Encoding,User-Agent
Connection: close
Content-Type: text/html

so HTTP/1.1 gets a Bad Request, but 1.0 is OK which is something I had already noticed. 
DNS fwd/rev mismatch: redacted.com != ip-redacted.com.ip.secureserver.net
redacted.com [107.180.41.158] 80 (http) open
**GET / HTTP/1.0**

HTTP/1.1 200 OK
Date: Mon, 08 Aug 2016 23:28:08 GMT
Server: Apache/2.4.18
Last-Modified: Thu, 14 Jul 2016 03:14:13 GMT
ETag: "e1db6-7ab-5378fe57995d8"
Accept-Ranges: bytes
Content-Length: 1963
Vary: Accept-Encoding,User-Agent
Connection: close
Content-Type: text/html

---
I thought nikto.conf entry of 'DEFAULTHTTPVER=1.0' should take care of it, or am I wrong?

**with curl:**
* Rebuilt URL to: redacted.com/
*   Trying redacted.com/...
* Connected to redacted.com (redacted.com) port 80 (#0)
> GET / HTTP/1.1
> Host: redacted.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 08 Aug 2016 23:29:42 GMT
< Server: Apache/2.4.18
< X-Powered-By: PHP/5.4.45
< X-Pingback: http://www.redacted.com/xmlrpc.php
< Location: http://www.redacted.com
< Vary: User-Agent
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host redacted.com left intact

**Comment by digininja** [comment]
It seems to be accepting a 1.1 connection from curl but not from netcat.
Did you pass the host header?

I'd guess the problem is header based, Try curl but pass in one of the user
agent headers that nikto sends. Maybe a WAF in place.

**Comment by dolevf** [comment]
hey digininja.

changing the default user agent configured in Nikto fixed it.

Thanks

**Comment by sullo** [comment]
I forgot to follow-up on this, but glad you figured it out. There are several WAF products that will block based on UA. Not much good except for drive-by scanning.
