### ISSUE TITLE
SNI support?

### ISSUE THREAD

**Issue by lfrancis** [sullo/nikto#413]
Ran into an issue on one of our dev sites today where Nikto 2.1.5 can't find the server -- said server is using HTTPS-SNI, the first time we've used such for our clients.

Unfortunately I can't share the url; site is hosted on Heroku and gets an A+ on ssllabs. My machine's OpenSSL version (MacOS El Capitan) appears to be compatible. Do I need something newer than SSL Module: Net::SSLeay version 1.58?

---
## Nikto Versions

File                               Version      Last Mod

---

Nikto main                         2.1.5
LibWhisker                         2.5
JSON-PP.pm  
db_404_strings                     2.003  
db_content_search                  2.000  
db_dictionary                      1.0
         2012-07-04
db_embedded                        2.004  
db_favicon                         2.010  
db_headers                         2.008  
db_httpoptions                     2.002  
db_multiple_index                  2.005  
db_outdated                        2.017  
db_parked_strings                  2.001  
db_realms                          2.002  
db_server_msgs                     2.006  
db_subdomains                      2.006  
db_tests                           2.021        2012-09-26
db_variables                       2.004  
nikto_apache_expect_xss.plugin     2.04  
nikto_apacheusers.plugin           2.06  
nikto_auth.plugin                  2.04  
nikto_cgi.plugin                   2.06         2008-05-06
nikto_clientaccesspolicy.plugin    1.00  
nikto_content_search.plugin        2.05  
nikto_cookies.plugin               2.05         2012-11-23
nikto_core.plugin                  2.1.5  
nikto_dictionary_attack.plugin     2.04  
nikto_embedded.plugin              2.07  
nikto_favicon.plugin               2.09  
nikto_fileops.plugin               1.00  
nikto_headers.plugin               2.11         2012-09-10
nikto_httpoptions.plugin           2.10  
nikto_msgs.plugin                  2.07  
nikto_multiple_index.plugin        2.03  
nikto_outdated.plugin              2.09  
nikto_parked.plugin                2.00  
nikto_paths.plugin                 2.00  
nikto_put_del_test.plugin          2.04  
nikto_report_csv.plugin            2.07         2008-11-11
nikto_report_html.plugin           2.05         2009-07-20
nikto_report_msf.plugin            1.00  
nikto_report_nbe.plugin            2.01  
nikto_report_text.plugin           2.05         2008-11-11
nikto_report_xml.plugin            2.05         2009-07-20
nikto_robots.plugin                2.06  
nikto_siebel.plugin                1.00         2011-01-03
nikto_ssl.plugin                   2.01  
nikto_subdomain.plugin             2.01         
## nikto_tests.plugin                 2.04         2008-09-21

Module RPC::XML missing. Logging to Metasploit is disabled.
Module RPC::XML::Client missing. Logging to Metasploit is disabled.
SSL Module: Net::SSLeay version 1.58

**Comment by tautology0** [comment]
I suspect that this is going to be an upstream problem in libwhisker or Net::SSLeay. I'm sorry there's going to be no easy answer to this, unless you put Nikto through a proxy.

**Comment by tautology0** [comment]
Quick dig - it's because libwhisker doesn't support it. I need to look at the RFCs to see how easy it would be to add it to LW.

**Comment by Herugrim** [comment]
Is there any updates to this issue? I ran into this today as well and bypassed it by using socat for the TLS SNI part. However Nikto then assumes it is HTTP and certain checks such as HSTS and Secure attribute on cookies are not checked. Would it be perhaps be an idea/quickfix to implement an 'ssl-checks' option that checks for these things over HTTP?

**Comment by sullo** [comment]
@Herugrim this works in my testing against an Apache setup I contrived, but some real-world testing is in order. Note that that this is in the 2.2.0 branch.

**Comment by matthijsmelissen** [comment]
This still does not work (for me) on the v2.2.0 branch.


```./nikto.pl -host analytics.usa.gov -port 443 -ssl -C all -o nikto_port443.flow.txt
- Nikto v2.2.0
---------------------------------------------------------------------------
+ No web server found on analytics.usa.gov:443
---------------------------------------------------------------------------
+ 0 host(s) tested
```

**Comment by lfrancis** [comment]
@sullo 

Same here, no love for v2.2.0:

`- Nikto v2.2.0
---------------------------------------------------------------------------
+ No web server found on www.npca.org:443
---------------------------------------------------------------------------
+ 0 host(s) tested`
