### ISSUE TITLE
Nikto not scanning for backup-files / .git - Repos? 

### ISSUE THREAD

**Issue by rogerthat** [sullo/nikto#414]
there is an article, stating that nikto isnt scanning for obvious stuff like
.git/ - repos in docroot or backup-files like index.php~
oder index.php.bak / index.php.old etc. 

http://blog.mazinahmed.net/2016/08/backup-file-artifacts.html

is that correct? i always thought it would, at least for those
obvious stuff ( file.php~ is a leftover from some console-editor)

**Comment by tautology0** [comment]
He's using a really old version of Nikto (2.4.6), but most versions check for a lot of stuff that he's mentioned (I've even got domain admin through this in the past - thanks to an /.svn directory).

I suspect he may be exaggerating for general effect. Although he does allow a general file list to be used to look for backup files on that list.

I'm tempted to knock out a quick module just because ;-)

**Comment by RealRancor** [comment]
Agree with that, nikto is already doing a lot of the mentioned checks (e.g. for SVN, Mercurial, Git etc.). Sure, there is always space for improvement like having a list of "live files" existing on the server and then append known backup file endings like .bak, .old, .swp and similar. But as @tautology0 already mentioned Nikto is already checking for a few of those.

> He's using a really old version of Nikto (2.4.6)

Probably just a typo as there never was Nikto 2.4.6 but only 2.1.6 :-)

I think that guy is also mixing a lot of stuff there or don't know how to handle the mentioned tools. Especially with Burp you can create a small wordlist to test for such stuff in a few seconds.

**Comment by tautology0** [comment]
There is a possible to export a list of URIs from burp and pass them through a check for backup files (which is what his tool does - and not efficiently). Now I could expand the dictionary plugin to do this, or write a burp extender (but that requires me to write Java, something I only do on 'droid apps).

I think there is something worth doing and we may have dropped the ball slightly, but I need to think on the best way of doing it.

To the OA: thanks for letting us know!

**Comment by superhedgy** [comment]
I've just tested nikto against a vulnerable target which has a /.git directory exposed. Nikto doesn't seem to pick it up.

It will be nice to see that feature incorporated in Nikto.

**Comment by tautology0** [comment]
It should do - I've got domain admin through that route. IIRC it checks for /.git/HEAD and /.git/config

**Comment by superhedgy** [comment]
Thanks for the quick reply. Oddly enough, in this particular case it didn't discover them :/ although both files you mentioned exist on the target web server.

**Comment by digininja** [comment]
Are you able to proxy the network traffic to see if it makes the requests
and what comes back?

**Comment by tautology0** [comment]
All I can think is that it somehow got caught in the 404 detection. I've checked the database and it does check for .git/HEAD, .git/config and .git/index - the last is the most important one as that can allow you to reconstruct the archive.

Any chance of more information on your specific case? You should be able to switch debugging on for just that case by doing something like:

./nikto.pl -host host:port -Plugins 'tests(debug,tids:6530)' -no404

**Comment by tautology0** [comment]
Closed due to age and lack of response
