### ISSUE TITLE
Shouldn't this be encoded?

### ISSUE THREAD

**Issue by dnet** [sullo/nikto#417]
Test ID `001055` in `program/databases/db_tests` has the following URI:

    "@CGIDIRSscripts/slxweb.dll/getfile?type=Library&file=[invalid filename]"

since such URIs won't get any further encoding, depending on the configuration (such as proxies involved) this can result in an HTTP request like this

    GET /slxweb.dll/getfile?type=Library&file=[invalid filename] HTTP/1.1
    ...

and since the first line of HTTP requests are delimited by spaces, some servers might return problematic answers, which leads to false positives. Now I'm not familiar with the actual issue being tested by 1055, but **are you sure this detection requires a literal space in the `file` parameter** or could it be just encoded like `invalid%20filename` or `invalid+filename`?

**Comment by sullo** [comment]
I think this was a too-literal read of the advisory, where "[invalid filename]" was meant to be anything invalid and didn't need brackets or spaces. I changed the test & added a link to the original advisory; thanks for pointing this out.
