### ISSUE TITLE
incorrect comment on x-frame-options

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#421]
I've just had this reported

```
+ X-Frame-Options header is set to allow framing from a.co.uk. This is only supported in Internet Explorer and may lead to the header being ignored.
```
But doing some research I found this:

https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

Which says that Firefox 18+ also supports the header. Just needs an update to the warning text to add FF.

**Comment by tautology0** [comment]
Fixed in last commit - thanks for noticing!
