### ISSUE TITLE
"No web server found" on every IP / HOST

### ISSUE THREAD

**Issue by pedrodj** [sullo/nikto#427]
C:\nikto-master>nikto.pl -h 52.208.95.6:81

Nikto v2.1.6
No web server found on 52.208.95.6:81
0 host(s) tested
Every IP i try to scan for testing tool, I get "No Web Server found"

Using Nikto 2.1.6 + Strawberry Perl x64

Any help ?

**Comment by tautology0** [comment]
Could you add a -D v which should show where it is failing.

FWIW, if I try the IP and port above then it just drops the connection.

**Comment by pedrodj** [comment]
C:\nikto-master>nikto.pl -h 52.208.95.6 -D v
- Nikto v2.1.6
---------------------------------------------------------------------------
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_apacheusers
V:Mon Nov 21 18:47:03 2016 - Loaded "Apache Users" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_apache_expect_xss
V:Mon Nov 21 18:47:03 2016 - Loaded "Apache Expect XSS" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_auth
V:Mon Nov 21 18:47:03 2016 - Loaded "Guess authentication" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_cgi
V:Mon Nov 21 18:47:03 2016 - Loaded "CGI" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_clientaccesspolicy
V:Mon Nov 21 18:47:03 2016 - Loaded "clientaccesspolicy.xml" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_content_search
V:Mon Nov 21 18:47:03 2016 - Loaded "Content Search" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_cookies
V:Mon Nov 21 18:47:03 2016 - Loaded "HTTP Cookie Internal IP" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_core
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_dictionary_attack
V:Mon Nov 21 18:47:03 2016 - Loaded "Dictionary attack" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_dir_traversal
V:Mon Nov 21 18:47:03 2016 - Loaded "Directory Traversal" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_domino
V:Mon Nov 21 18:47:03 2016 - Loaded "IBM/Lotus Domino Specific Tests" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_drupal
V:Mon Nov 21 18:47:03 2016 - Loaded "Drupal Specific Tests" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_embedded
V:Mon Nov 21 18:47:03 2016 - Loaded "Embedded Detection" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_favicon
V:Mon Nov 21 18:47:03 2016 - Loaded "Favicon" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_fileops
V:Mon Nov 21 18:47:03 2016 - Loaded "File Operations" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_headers
V:Mon Nov 21 18:47:03 2016 - Loaded "HTTP Headers" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_httpoptions
V:Mon Nov 21 18:47:03 2016 - Loaded "HTTP Options" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_ms10_070
V:Mon Nov 21 18:47:03 2016 - Loaded "ms10-070 Check" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_msgs
V:Mon Nov 21 18:47:03 2016 - Loaded "Server Messages" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_multiple_index
V:Mon Nov 21 18:47:03 2016 - Loaded "Multiple Index" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_negotiate
V:Mon Nov 21 18:47:03 2016 - Loaded "Negotiate" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_outdated
V:Mon Nov 21 18:47:03 2016 - Loaded "Outdated" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_parked
V:Mon Nov 21 18:47:03 2016 - Loaded "Parked Detection" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_paths
V:Mon Nov 21 18:47:03 2016 - Loaded "Path Search" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_put_del_test
V:Mon Nov 21 18:47:03 2016 - Loaded "Put/Delete test" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_csv
V:Mon Nov 21 18:47:03 2016 - Loaded "CSV reports" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_html
V:Mon Nov 21 18:47:03 2016 - Loaded "Report as HTML" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_json
V:Mon Nov 21 18:47:03 2016 - Loaded "JSON reports" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_nbe
V:Mon Nov 21 18:47:03 2016 - Loaded "NBE reports" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_sqlg
V:Mon Nov 21 18:47:03 2016 - Loaded "Generic SQL reports" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_text
V:Mon Nov 21 18:47:03 2016 - Loaded "Text reports" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_report_xml
V:Mon Nov 21 18:47:03 2016 - Loaded "Report as XML" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_robots
V:Mon Nov 21 18:47:03 2016 - Loaded "Robots" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_shellshock
V:Mon Nov 21 18:47:03 2016 - Loaded "shellshock" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_siebel
V:Mon Nov 21 18:47:03 2016 - Loaded "Siebel Checks" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_sitefiles
V:Mon Nov 21 18:47:03 2016 - Loaded "Site Files" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_ssl
V:Mon Nov 21 18:47:03 2016 - Loaded "SSL and cert checks" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_subdomain
V:Mon Nov 21 18:47:03 2016 - Loaded "Sub-domain forcer" plugin.
V:Mon Nov 21 18:47:03 2016 - Initialising plugin nikto_tests
V:Mon Nov 21 18:47:03 2016 - Loaded "Nikto Tests" plugin.
V:Mon Nov 21 18:47:03 2016 - Getting targets
V:Mon Nov 21 18:47:03 2016 - Target:52.208.95.6 port:80
V:Mon Nov 21 18:47:03 2016 - Opening reports (none, )
V:Mon Nov 21 18:47:03 2016 - Checking for HTTP on port 52.208.95.6:80, using HEA
D
V:Mon Nov 21 18:47:03 2016 -  for HEAD:
V:Mon Nov 21 18:47:03 2016 - Checking for HTTPS on port 52.208.95.6:80, using HE
AD
V:Mon Nov 21 18:47:06 2016 -  for HEAD:
V:Mon Nov 21 18:47:06 2016 - Checking for HTTP on port 52.208.95.6:80, using GET

V:Mon Nov 21 18:47:06 2016 -  for GET:
V:Mon Nov 21 18:47:06 2016 - Checking for HTTPS on port 52.208.95.6:80, using GE
T
V:Mon Nov 21 18:47:07 2016 -  for GET:
+ No web server found on 52.208.95.6:80
---------------------------------------------------------------------------
V:Mon Nov 21 18:47:07 2016 - 6807 server checks loaded
V:Mon Nov 21 18:47:07 2016 - Running start for "Directory Traversal" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "IBM/Lotus Domino Specific Tests"
 plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "Drupal Specific Tests" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "Embedded Detection" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "Favicon" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "HTTP Headers" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "Guess authentication" plugin
V:Mon Nov 21 18:47:07 2016 - Running start for "Content Search" plugin
+ 0 host(s) tested
V:Mon Nov 21 18:47:07 2016 + 8 requests made in 4 seconds

**Comment by barzoj** [comment]
the same problem here 

- Nikto v2.1.6
---------------------------------------------------------------------------
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_auth
V:Fri Feb 10 17:22:57 2017 - Loaded "Guess authentication" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_fileops
V:Fri Feb 10 17:22:57 2017 - Loaded "File Operations" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_subdomain
V:Fri Feb 10 17:22:57 2017 - Loaded "Sub-domain forcer" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_nbe
V:Fri Feb 10 17:22:57 2017 - Loaded "NBE reports" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_cookies
V:Fri Feb 10 17:22:57 2017 - Loaded "HTTP Cookie Internal IP" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_sitefiles
V:Fri Feb 10 17:22:57 2017 - Loaded "Site Files" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_httpoptions
V:Fri Feb 10 17:22:57 2017 - Loaded "HTTP Options" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_csv
V:Fri Feb 10 17:22:57 2017 - Loaded "CSV reports" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_shellshock
V:Fri Feb 10 17:22:57 2017 - Loaded "shellshock" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_clientaccesspolicy
V:Fri Feb 10 17:22:57 2017 - Loaded "clientaccesspolicy.xml" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_dictionary_attack
V:Fri Feb 10 17:22:57 2017 - Loaded "Dictionary attack" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_apacheusers
V:Fri Feb 10 17:22:57 2017 - Loaded "Apache Users" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_tests
V:Fri Feb 10 17:22:57 2017 - Loaded "Nikto Tests" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_favicon
V:Fri Feb 10 17:22:57 2017 - Loaded "Favicon" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_siebel
V:Fri Feb 10 17:22:57 2017 - Loaded "Siebel Checks" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_headers
V:Fri Feb 10 17:22:57 2017 - Loaded "HTTP Headers" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_core
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_negotiate
V:Fri Feb 10 17:22:57 2017 - Loaded "Negotiate" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_msgs
V:Fri Feb 10 17:22:57 2017 - Loaded "Server Messages" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_content_search
V:Fri Feb 10 17:22:57 2017 - Loaded "Content Search" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_apache_expect_xss
V:Fri Feb 10 17:22:57 2017 - Loaded "Apache Expect XSS" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_robots
V:Fri Feb 10 17:22:57 2017 - Loaded "Robots" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_parked
V:Fri Feb 10 17:22:57 2017 - Loaded "Parked Detection" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_put_del_test
V:Fri Feb 10 17:22:57 2017 - Loaded "Put/Delete test" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_embedded
V:Fri Feb 10 17:22:57 2017 - Loaded "Embedded Detection" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_text
V:Fri Feb 10 17:22:57 2017 - Loaded "Text reports" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_ms10_070
V:Fri Feb 10 17:22:57 2017 - Loaded "ms10-070 Check" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_sqlg
V:Fri Feb 10 17:22:57 2017 - Loaded "Generic SQL reports" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_outdated
V:Fri Feb 10 17:22:57 2017 - Loaded "Outdated" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_paths
V:Fri Feb 10 17:22:57 2017 - Loaded "Path Search" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_multiple_index
V:Fri Feb 10 17:22:57 2017 - Loaded "Multiple Index" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_drupal
V:Fri Feb 10 17:22:57 2017 - Loaded "Drupal Specific Tests" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_html
V:Fri Feb 10 17:22:57 2017 - Loaded "Report as HTML" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_report_xml
V:Fri Feb 10 17:22:57 2017 - Loaded "Report as XML" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_ssl
V:Fri Feb 10 17:22:57 2017 - Loaded "SSL and cert checks" plugin.
V:Fri Feb 10 17:22:57 2017 - Initialising plugin nikto_cgi
V:Fri Feb 10 17:22:57 2017 - Loaded "CGI" plugin.
V:Fri Feb 10 17:22:57 2017 - Getting targets
V:Fri Feb 10 17:22:57 2017 - Checking for HTTP on port 10.12.10.207:80, using HEAD
V:Fri Feb 10 17:23:17 2017 -  for HEAD:	
V:Fri Feb 10 17:23:17 2017 - Checking for HTTPS on port 10.12.10.207:80, using HEAD
V:Fri Feb 10 17:23:18 2017 -  for HEAD:	
V:Fri Feb 10 17:23:18 2017 - Checking for HTTP on port 10.12.10.207:80, using GET
V:Fri Feb 10 17:23:39 2017 -  for GET:	
V:Fri Feb 10 17:23:39 2017 - Checking for HTTPS on port 10.12.10.207:80, using GET
V:Fri Feb 10 17:23:40 2017 -  for GET:	
+ No web server found on 10.12.10.207:80
---------------------------------------------------------------------------
V:Fri Feb 10 17:23:40 2017 - Opening reports (none, )
V:Fri Feb 10 17:23:40 2017 - 6927 server checks loaded
V:Fri Feb 10 17:23:40 2017 - Running start for "Favicon" plugin
V:Fri Feb 10 17:23:40 2017 - Running start for "HTTP Headers" plugin
V:Fri Feb 10 17:23:40 2017 - Running start for "Embedded Detection" plugin
V:Fri Feb 10 17:23:40 2017 - Running start for "Drupal Specific Tests" plugin
V:Fri Feb 10 17:23:40 2017 - Running start for "Guess authentication" plugin
V:Fri Feb 10 17:23:40 2017 - Running start for "Content Search" plugin
+ 0 host(s) tested
V:Fri Feb 10 17:23:40 2017 + 8 requests made in 43 seconds

**Comment by tautology0** [comment]
The top IP address (52.*) is Amazon AWS which performs User-Agent HTTP header filtering, if you change the user agent via the -useragent flag it should magically start working again.

i.e.
nikto.pl -host hostname -useragent Bob

For the second one, try using the -useragent flag, if not, can you connect to it directly through telnet or netcat?

**Comment by barzoj** [comment]
everything is fine with -useragent flag, thank you

**Comment by tautology0** [comment]
Suspect it was due to useragent filtering. Closing.
