### ISSUE TITLE
false positive on IBM Webshpere

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#429]
I just got this false positive when scanning a site:

```
-----------------------------------------------------------------------
              Information
-----------------------------------------------------------------------
Test ID:    007044
OSVDB ID:   0
Message:    /wps/portal/Home/Welcome/!ut/: IBM Websphere default portal found. May allow users to create accounts.
Reason:     Content Match
-----------------------------------------------------------------------
              Request
-----------------------------------------------------------------------
GET /wps/portal/Home/Welcome/!ut/ HTTP/1.1
Connection: Keep-Alive
User-Agent: Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:007044)
Host: abc.com

-----------------------------------------------------------------------
              Response
-----------------------------------------------------------------------
HTTP/1.1 404 Not Found
```
Not sure what it is matching in the page as there isn't a flood of false positives like there can be when the 404 page does something special.

**Comment by RealRancor** [comment]
> Not sure what it is matching in the page as there isn't a flood

The check is doing a ``Sign\sUp`` so it seems that 404 is containing this response

**Comment by digininja** [comment]
It does contain that string, looks like you've found it.

**Comment by RealRancor** [comment]
If you have such custom build 404s on pages (which is probably also the case in #430) then have a look at the -404string command line options of nikto to mark these 404 pages as a 404.

**Comment by sullo** [comment]
I poked at a bunch of these via inurl, and don't see anything better or more unique to match on, really.
