### ISSUE TITLE
log where server type changes

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#432]
I got this on a scan I just did: 

```
+ Server banner has changed from '' to 'nginx' which may suggest a WAF, load balancer or proxy is in place
```

I looked in the save directory (-Save) but couldn't find any reference to nginx so couldn't work out what had caused the message.

It would be good to log this when changes.

**Comment by wireghoul** [comment]
I've done some testing for this, -Display D will capture the request/response, but it usually occur from a 400 bad request error or a similar parsing flaw. This makes it hard to display reproduction steps in in a meaningful way in the terminal. I'd recommend running a waf/lb detector like lbd, halberd or lbmap if you see this.

**Comment by sullo** [comment]
It only took three years to make a simple change, but it's done :)
