### ISSUE TITLE
odd "+ lines"

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#454]
There is a bug in ./plugins/nikto_clientaccesspolicy.plugin which results in a result string coming out wrong.

These lines mess up in some way and $msg just gets the string "lines" rather than the full content.

```
 62         $msg =  $mark->{'root'} . "$file contains $DISCTR " . ($DISCTR > 1)?"lines":"line" . \
 63                 " which should be manually viewed for improper domains or wildcards.";
```

I think it is something to do with the type of $DISCTR but don't know enough Perl to dig in more than that.

**Comment by tautology0** [comment]
Fixed in trunk; it was due to perl weirdness in tertiary assignment and backslashes. I'm not certain I understand why it was like that; but fixed now.

There's a reason why I avoid perl now ;-)
