### ISSUE TITLE
Array reported as a string in findings

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#471]
Just had this finding:

```
Test ID:        999100
OSVDB ID:       0
Message:        Uncommon header 'x-server-name' found, with contents: ARRAY(0xfbb77c0)
Reason:
```

But looking at the headers, the x-server-name is a string:

```
HTTP/1.1 200 OK
cache-control: private
content-type: text/html; charset=utf-8
vary: Accept-Encoding,Accept-Encoding
server: Microsoft-IIS/7.5
x-aspnetmvc-version: 4.0
x-server-name: AA-55-02
x-server-name: AA-55-02
access-control-expose-headers: X-Server-Name
access-control-expose-headers: X-Server-Name
x-server-name: AA-55-02
x-server-name: AA-55-02
access-control-expose-headers: X-Server-Name
access-control-expose-headers: X-Server-Name
```
My guess would be, because it is repeated, you are creating an array rather than a string and the check is then treating the array as a string when doing the reporting.

**Comment by sullo** [comment]
#394 fixed this for server-headers, but I guess we need to extend that to all issues/headers and handle it more cleanly.

**Comment by digininja** [comment]
Glad it is a known problems, want to close this or leave it open to remind you to do it?

**Comment by sullo** [comment]
This all stems back to 
nikto_core.plugin:    $reqhash->{'whisker'}->{'ignore_duplicate_headers'}   = 0;

LW will happily ignore duplicate headers for us, but for good or bad we've explicitly turned it off.

**Comment by sullo** [comment]
the nikto_headers.plugin file should trigger an alert if a duplicate header is seen (ref() is ARRAY) because the various browsers may behave differently. I did some testing of this years ago and don't recall the exact results, but some browsers would keep the first value, and some would keep the last, for any particular which was sent twice.

**Comment by digininja** [comment]
I always report on it for that reason, would be nice to have it picked out
as an issue.

**Comment by sullo** [comment]
Confirmed working in 2.2.0 (see below). Now we just need to finish this release!
`+ The HTTP header "chris" was sent multiple times. Browser behavior may be erratic depending on which header is used. This should be manually examined.`
