### ISSUE TITLE
Nikto ignoring config file in the current directory

### ISSUE THREAD

**Issue by dkasak** [sullo/nikto#475]
Nikto is seemingly ignoring the `nikto.conf` configuration file inside the current working directory. I've tested this by `cd`-ing to a directory and creating a `nikto.conf` inside with the following contents:

    CLIOPTS=-Display v

Then, when running `nikto -h <host>`, the scan begins but verbose information is not written to the terminal. Doing a `cp nikto.conf ~/nikto.conf` and rerunning the scan makes it output verbose information as expected.

I'm using the latest git master on Arch Linux.

**Comment by sullo** [comment]
The config loading system was recently revamped.

Also, Closing due to age.
