### ISSUE TITLE
+ Scan terminated:  2 error(s) and 5 item(s) reported on remote host

### ISSUE THREAD

**Issue by janarthananjana** [sullo/nikto#478]
+ Scan terminated:  2 error(s) and 5 item(s) reported on remote host

Where these log files is located

**Comment by sullo** [comment]
There are no log files unless you enable them. You can run in debug mode (lots of output) with -D D or in verbose mode with -D V. 

https://cirt.net/nikto2-docs/troubleshooting.html#id2795360
