### ISSUE TITLE
NIkto reporting uncommon headers in scan

### ISSUE THREAD

**Issue by ashishmishraw** [sullo/nikto#479]
Version  2.1.5 

After running REST API vulnerability scan on ports 80, 443 and 8443, I am getting the following warnings:

1. Uncommon header 'x-content-type-options' found, with contents: nosniff
2. Uncommon header 'x-frame-options' found, with contents: SAMEORIGIN

Not sure what is uncommon header in x-content-type and x-frame-options ? They are very valid headers used in HTTP requests

Any insight into what could have this warnings possibly mean ?

**Comment by sullo** [comment]
Try running from the git version. It has a lot of updates since 2.1.5.
