### ISSUE TITLE
Uncommon header 'referrer-policy' found

### ISSUE THREAD

**Issue by gemal** [sullo/nikto#485]
got this when scanning
`Uncommon header 'referrer-policy' found, with contents: same-origin`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by tautology0** [comment]
To be fair it's not an official header yet; Mozilla and Chrome jumped the gun a bit.

That said, I'm tempted to add it to the list of security headers that we advise servers have.

**Comment by sullo** [comment]
not sure i'd want to recommend this for all servers all the time. The number of instances I see 'sensitive' information in a query string is pretty small, so the overhead of sending the header all the time seems like overkill to me.

**Comment by tautology0** [comment]
You committed just before me. I blame VMware having a tizzy and not letting me talking to my testing VM ;-)
