### ISSUE TITLE
-ssl and -host / -vhost doesn't play nice together

### ISSUE THREAD

**Issue by drwetter** [sullo/nikto#487]
Hi,

I noticed an odd behaviour.  

* ``./nikto.pl  -port 443 -ssl -host <somehost> -root /`` doesn't work -- it hits the default vhost on the IP.  
* ``./nikto.pl -host <IP> -port 443 -ssl -vhost <somehost> -root /`` does the same and also 
* ``./nikto.pl -host <IP> -port 443 -vhost <somehost> -root /``  (``-ssl`` omitted)

whereas ``./nikto.pl  -port 443 -host <somehost> -root /`` works.

Thx, Dirk

**Comment by tautology0** [comment]
That's really an artefact of the command line syntax. "-host" is a bit of a misnomer; it should be really be "-url", but has been kept the same really to not muck about with the command line.

In most cases, something like:

`nikto.pl -host https://www.somehost.com/`

Should be enough for most people. Nikto will automatically test of http and https on the port provided and select which one it tests. It does this by testing first http and then https. Adding -ssl (or -nossl) alters this by dropping http or https testing.

The -vhost options should work; but I may need to do some delving to work out why it doesn't in your case; but that's really legacy command line format and should (mostly) be avoided. (It's still in there to allow for when DNS hasn't been set up properly to avoid having to do /etc/hosts type frigs.)

**Comment by drwetter** [comment]
ok thanks! In the meantime I'll avoid that

**Comment by drwetter** [comment]
As you declared this as a legacy and its works with different args, it's fine with me. Thus I am closing this.
