### ISSUE TITLE
postnuke false positive

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#493]
Just got this false positive on a Postnuke issue. Repeating the request in Burp gets a "400 Bad Request" so don't know what this is matching on.

No other issues were picked up on the server.

```
-----------------------------------------------------------------------
                          Information
-----------------------------------------------------------------------
Test ID:        000804
OSVDB ID:       0
Message:        /postnuke/modules.php?op=modload&name=Web_Links&file=index&req=viewlinkdetails&lid=666&ttitle=Mocosoft Utilities\"%3<script>alert('Vulnerable')</script>: Postnuke Phoenix 0.7.2.3 is vulnerable to Cross Site Scripting (XSS). CA-2000-02.
Reason:         Content Match
-----------------------------------------------------------------------
                          Request
-----------------------------------------------------------------------
GET /postnuke/modules.php?op=modload&name=Web_Links&file=index&req=viewlinkdetails&lid=666&ttitle=Mocosoft Utilities\"%3<script>alert('Vulnerable')</script> HTTP/1.1
Host: xxxx
Connection: Keep-Alive
User-Agent: Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:000804)

-----------------------------------------------------------------------
                          Response
-----------------------------------------------------------------------
Not Applicable
-----------------------------------------------------------------------
                          Data Objects
-----------------------------------------------------------------------
REQUEST:{"Host":"xxx","Connection":"Keep-Alive","whisker":{"ssl":0,"max_size":750000,"retry":0,"method":"GET","keep-alive":1,"http_space1":" ","protocol":"HTTP","invalid_protocol_return_value":1,"ssl_rsacertfile":null,"http_eol":"\r\n","uri_postfix":"","ssl_save_info":1,"uri":"/postnuke/modules.php?op=modload&name=Web_Links&file=index&req=viewlinkdetails&lid=666&ttitle=Mocosoft Utilities\\\"%3<script>alert('Vulnerable')</script>","ignore_duplicate_headers":0,"host":"xxx","version":"1.1","require_newline_after_headers":0,"force_bodysnatch":0,"port":"80","uri_param_sep":"?","MAGIC":31339,"include_host_in_uri":0,"timeout":10,"lowercase_incoming_headers":1,"trailing_slurp":0,"force_close":0,"http_space2":" ","normalize_incoming_headers":1,"force_open":0,"uri_prefix":"","ssl_certfile":null},"User-Agent":"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:000804)"}

**Comment by tautology0** [comment]
That's strange, the test is looking for "<script>alert('Vulnerable')</script>" in the response. As the above implies that there is no response this shouldn't have alerted.

Does trying it in burp return a body?

**Comment by digininja** [comment]
No:

```
HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
```

It picked it up for HTTP and HTTPS so wasn't just an oddity on a single scan.

**Comment by digininja** [comment]
Found it. If I copy the exact request from the save I get this:

```
Utilities\"%3<script>alert('Vulnerable')</script> 404 Not Found
Connection: close
Last-Modified: Thu, 16 Feb 2017 14:31:20 GMT
x-frame-options: SAMEORIGIN
Content-Type: text/html
Content-Length: 259
Date: Wed, 02 Aug 2017 15:02:28 GMT

<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html;">
    </head>
    <body>
    </body>
</html>
```

It is the space in the ttitle parameter, get rid of that or encode it and get the 400 error, with it in the web server screws up and gives the malformed response.

**Comment by tautology0** [comment]
Looks like the server is non-compliant - if the spaces don't match up it should return a 400 and then _encode_ the response as stated in RFC 7230:

> Recipients of an invalid request-line SHOULD respond with either a
> 400 (Bad Request) error or a 301 (Moved Permanently) redirect with
> the request-target properly encoded. 

That doesn't help you, or anybody else; and as it's an invalid request (though it would be valid HTTP/0.9), I'll update the test DB to encode the space tomorrow once I've booted my laptop.

I've been trying to think about whether you could get an XSS with the way the server is working; but I can't think of any user agent that would render it that way.

**Comment by digininja** [comment]
I've had a play with it and I've not been able to get anything useful from it. I've tried adding new lines with %0a and %0d but they get rendered out as entered. If I put a second space in it is the characters after that space that get returned so I can't do anything like this:

```
?x=sp 200 OK%0ablah
```
Just going to write it up as a broken server with a warning that someone with more time might be able to abuse it.

Is it worth leaving a check in that includes an unencoded space in a parameter? It has shown a fairly useless bug in this case but may come up with something interesting for someone else.

**Comment by wireghoul** [comment]
On the odd chance that a bug relies on unencoded spaces I wouldn't recommend it. I don't have a vulnerable postnuke to test this on, but based on http://seclists.org/bugtraq/2003/Aug/106 it seems like replacing the space with + or %20 would not break the payload in this case. I vote to encode the space in the URI.

**Comment by sullo** [comment]
I think it makes sense to replace the space as this test isn't about a weird response as @digininja found. I wonder if we should have a test for "/some space" and look for oddities though--probably need a bit of code for it to be useful.
