### ISSUE TITLE
Update fails to create CHANGES.txt

### ISSUE THREAD

**Issue by bodhisvaha** [sullo/nikto#498]
Hi, nikto fails to create CHANGES.txt  file during update, manually created then update works.

# nikto -update
+ Retrieving 'nikto_headers.plugin'
+ Retrieving 'db_tests'
+ Retrieving 'db_parked_strings'
+ Retrieving 'nikto_cookies.plugin'
+ Retrieving 'nikto_report_csv.plugin'
+ Retrieving 'CHANGES.txt'
+ ERROR: Unable to open '/usr/share/nikto/docs/CHANGES.txt' for write: 
1 at /usr/share/nikto/plugins/nikto_core.plugin line 1933.

# ll /usr/share/nikto/
total 12
drwxr-xr-x. 2 root root 4096 Sep 28 22:00 databases
drwxr-xr-x. 2 root root 4096 Sep 28 22:00 plugins
drwxr-xr-x. 2 root root 4096 Sep 28 22:00 templates

# mkdir /usr/share/nikto/docs/
# touch /usr/share/nikto/docs/CHANGES.txt
# nikto -update
+ No updates required.
+ CIRT.net message: Please submit Nikto bugs to https://github.com/sullo/nikto

**Comment by tautology0** [comment]
This is due to the way it's been packaged by your distro's packaging team and should be raised to them. We advise cloning Nikto from github; and have deprecated -update in favour of using git.

**Comment by bodhisvaha** [comment]
Thank you for clarification. Distro is Fedora release 26 (Twenty Six).
