### ISSUE TITLE
Remove SVN info in docs

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#50]
The full help documentation references SVN, not git.

**Comment by cmlh** [comment]
@sullo,

Can this be reopened as SVN is also referenced within [Chapter 7. OSS Development](https://cirt.net/nikto2-docs/developing.html) too?

**Comment by natlibfi-arlehiko** [comment]
Yes. I checked that the SVN repo still works. Is the code mirrored or is SVN now obsolete?

**Comment by tautology0** [comment]
We haven't used SVN for several years. @sullo probably ought to shut down the old SVN repo!

**Comment by digininja** [comment]
Wonder how many distros that will break.

**Comment by natlibfi-arlehiko** [comment]
> We haven't used SVN for several years. @sullo probably ought to shut down the old SVN repo!

I'd send a PR to update the repo info to point to Github but you don't seem to have the docs in a version control repo.

**Comment by sullo** [comment]
@digininja if they are still running via SVN i'd consider them broken!

They are not in a separate repo, but here: https://github.com/sullo/nikto/tree/master/documentation

They are in docbook xml format which seemed like a good idea at the time. However, they are partially moved to GH Wiki https://github.com/sullo/nikto/wiki

Help moving them to wiki would be most welcomed. I'd like to remove them entirely from source and cirt.net (with redirect of course). 

Lastly,  thought Assembla folded so I never went back to delete the SVN. I'll figure it out...

**Comment by digininja** [comment]
I bet there is at least one out there.

**Comment by sullo** [comment]
Assembla site taken down. Docs on cirt.net modified. Nothing in git now references SVN/Assembla.
