### ISSUE TITLE
No web server found on host

### ISSUE THREAD

**Issue by baloshes** [sullo/nikto#504]
Any help troubleshooting would be much appreciated 

nikto -D V -host http://posta.co.il/ -nossl
 

- Nikto v2.1.6
---------------------------------------------------------------------------
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_dictionary_attack
V:Mon Nov  6 16:49:32 2017 - Loaded "Dictionary attack" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_sitefiles
V:Mon Nov  6 16:49:32 2017 - Loaded "Site Files" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_core
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_xml
V:Mon Nov  6 16:49:32 2017 - Loaded "Report as XML" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_ms10_070
V:Mon Nov  6 16:49:32 2017 - Loaded "ms10-070 Check" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_msgs
V:Mon Nov  6 16:49:32 2017 - Loaded "Server Messages" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_apache_expect_xss
V:Mon Nov  6 16:49:32 2017 - Loaded "Apache Expect XSS" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_put_del_test
V:Mon Nov  6 16:49:32 2017 - Loaded "Put/Delete test" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_robots
V:Mon Nov  6 16:49:32 2017 - Loaded "Robots" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_nbe
V:Mon Nov  6 16:49:32 2017 - Loaded "NBE reports" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_multiple_index
V:Mon Nov  6 16:49:32 2017 - Loaded "Multiple Index" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_content_search
V:Mon Nov  6 16:49:32 2017 - Loaded "Content Search" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_ssl
V:Mon Nov  6 16:49:32 2017 - Loaded "SSL and cert checks" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_drupal
V:Mon Nov  6 16:49:32 2017 - Loaded "Drupal Specific Tests" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_parked
V:Mon Nov  6 16:49:32 2017 - Loaded "Parked Detection" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_shellshock
V:Mon Nov  6 16:49:32 2017 - Loaded "shellshock" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_siebel
V:Mon Nov  6 16:49:32 2017 - Loaded "Siebel Checks" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_embedded
V:Mon Nov  6 16:49:32 2017 - Loaded "Embedded Detection" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_outdated
V:Mon Nov  6 16:49:32 2017 - Loaded "Outdated" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_apacheusers
V:Mon Nov  6 16:49:32 2017 - Loaded "Apache Users" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_html
V:Mon Nov  6 16:49:32 2017 - Loaded "Report as HTML" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_subdomain
V:Mon Nov  6 16:49:32 2017 - Loaded "Sub-domain forcer" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_cgi
V:Mon Nov  6 16:49:32 2017 - Loaded "CGI" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_paths
V:Mon Nov  6 16:49:32 2017 - Loaded "Path Search" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_csv
V:Mon Nov  6 16:49:32 2017 - Loaded "CSV reports" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_favicon
V:Mon Nov  6 16:49:32 2017 - Loaded "Favicon" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_clientaccesspolicy
V:Mon Nov  6 16:49:32 2017 - Loaded "clientaccesspolicy.xml" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_httpoptions
V:Mon Nov  6 16:49:32 2017 - Loaded "HTTP Options" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_negotiate
V:Mon Nov  6 16:49:32 2017 - Loaded "Negotiate" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_fileops
V:Mon Nov  6 16:49:32 2017 - Loaded "File Operations" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_cookies
V:Mon Nov  6 16:49:32 2017 - Loaded "HTTP Cookie Internal IP" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_sqlg
V:Mon Nov  6 16:49:32 2017 - Loaded "Generic SQL reports" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_auth
V:Mon Nov  6 16:49:32 2017 - Loaded "Guess authentication" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_report_text
V:Mon Nov  6 16:49:32 2017 - Loaded "Text reports" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_tests
V:Mon Nov  6 16:49:32 2017 - Loaded "Nikto Tests" plugin.
V:Mon Nov  6 16:49:32 2017 - Initialising plugin nikto_headers
V:Mon Nov  6 16:49:32 2017 - Loaded "HTTP Headers" plugin.
V:Mon Nov  6 16:49:32 2017 - Getting targets
V:Mon Nov  6 16:49:37 2017 - Checking for HTTP on port posta.co.il:80, using HEAD
V:Mon Nov  6 16:49:38 2017 -  for HEAD:	
V:Mon Nov  6 16:49:38 2017 - Checking for HTTP on port posta.co.il:80, using GET
V:Mon Nov  6 16:49:39 2017 -  for GET:	
+ No web server found on posta.co.il:80
---------------------------------------------------------------------------
V:Mon Nov  6 16:49:39 2017 - Opening reports (none, )
V:Mon Nov  6 16:49:39 2017 - 6934 server checks loaded
V:Mon Nov  6 16:49:39 2017 - Running start for "Drupal Specific Tests" plugin
V:Mon Nov  6 16:49:39 2017 - Running start for "Embedded Detection" plugin
V:Mon Nov  6 16:49:39 2017 - Running start for "Favicon" plugin
V:Mon Nov  6 16:49:39 2017 - Running start for "HTTP Headers" plugin
V:Mon Nov  6 16:49:39 2017 - Running start for "Content Search" plugin
V:Mon Nov  6 16:49:39 2017 - Running start for "Guess authentication" plugin
+ 0 host(s) tested

**Comment by Sjord** [comment]
This server only replies if the request has an `Accept` header. Try this:

```
nl=$'\n'
cr=$'\r'
nikto -host http://posta.co.il/ -nossl -useragent "nikto${cr}${nl}Accept: text/html"
```
