### ISSUE TITLE
OSVDB-877: HTTP TRACE method is never tested with HTTP 1.1

### ISSUE THREAD

**Issue by m-lw** [sullo/nikto#512]
I think the variable $version should be used in https://github.com/sullo/nikto/blob/master/program/plugins/nikto_httpoptions.plugin#L140 instead of "1.0".

A side effect of this is that the TRACE test is never run with a specified host header unless the the vhost argument is supplied.

**Comment by tautology0** [comment]
Good spot; that probably should be fixed, if I can't remember why it's doing that.

**Comment by tautology0** [comment]
Fixed. Thanks for reporting it!
