### ISSUE TITLE
Susceptible to "illegal hexadecimal digit" errors.

### ISSUE THREAD

**Issue by subylan** [sullo/nikto#520]
https://github.com/sullo/nikto/blob/7d19c359466a29fff5aaaef5a5383694fc640da8/program/plugins/nikto_headers.plugin#L115

When mtime contains g, this error can occur on the command line.

**Comment by sullo** [comment]
Can you elaborate a little? Do you have a value for mtime that would trigger this? I'm trying to reproduce but can't seem to. Thanks.

**Comment by wireghoul** [comment]
Presumably when it's a non Apache ETag header, but still meets the parsing criteria...
