### ISSUE TITLE
Nikto IDs create invalid JSON

### ISSUE THREAD

**Issue by zythosec** [sullo/nikto#521]
The line below (I believe) does not make the ID a string or strip the leading zeros, creating invalid JSON when using the JSON output format:
https://github.com/sullo/nikto/blob/master/program/plugins/nikto_report_json.plugin#L86
Note: I've left out many fields for simplicity.

Actual (invalid):
```json
{
  "vulnerabilities": [
    { "id": 00076 },
    { "id": 00077 }
  ]
}
```

Expected (valid):
Either:
```json
{
  "vulnerabilities": [
    { "id": "00076" },
    { "id": "00077" }
  ]
}
```
or
```json
{
  "vulnerabilities": [
    { "id": 76 },
    { "id": 77 }
  ]
}
```

**Comment by rnanopoulos-r7** [comment]
Also, rather than build the JSON manually is there a JSON serializer in perl that could be utilized?
