### ISSUE TITLE
Reducing false positives by preventing multiple reports of the same issue

### ISSUE THREAD

**Issue by codingo** [sullo/nikto#532]
One of the main things I run into regularly is a high number of false positives from nikto when pages are set to return the same content, for example, the following output:

> + /index.php?file=Liens&op=\"><script>alert('Vulnerable');</script>: Output from the phpinfo() function was found.
> + /index.php?catid=&lt;script&gt;alert('Vulnerable')&lt;/script&gt;: Output from the phpinfo() function was found.
> + /index.php?action=storenew&username=<script>alert('Vulnerable')</script>: Output from the phpinfo() function was found.
> + /index.php?action=search&searchFor=\"><script>alert('Vulnerable')</script >: Output from the phpinfo() function was found.
> + /index.php/\"><script><script>alert(document.cookie)</script><: Output from the phpinfo() function was found.
> + /index.php/content/search/?SectionID=3&SearchText=<script>alert(document.cookie)</script>: Output from the phpinfo() function was found.
> + /index.php/content/advancedsearch/?SearchText=<script>alert(document.cookie)</script>&PhraseSearchText=<script>alert(document.cookie)</script>&SearchContentClassID=-1&SearchSectionID=-1&SearchDate=-1&SearchButton=Search: Output from the phpinfo() function was found.
> + /index.php?sql_debug=1: Output from the phpinfo() function was found.
> + /index.php?rep=<script>alert(document.cookie)</script>: Output from the phpinfo() function was found.
> + /index.php?module=ew_filemanager&type=admin&func=manager&pathext=../../../etc: Output from the phpinfo() function was found.
> + /index.php?module=ew_filemanager&type=admin&func=manager&pathext=../../../etc/&view=passwd: Output from the phpinfo() function was found.
> + /index.php?err=3&email=\"><script>alert(document.cookie)</script>: Output from the phpinfo() function was found.
> + /index.php?name=Forums&file=viewtopic&t=2&rush=%64%69%72&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?Nikto=Forums&file=viewtopic&t=2&rush=%64%69%72&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?Nikto=forums&file=viewtopic&t=2&rush=%64%69%72&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?name=forums&file=viewtopic&t=2&rush=%64%69%72&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?name=PNphpBB2&file=viewtopic&t=2&rush=%64%69%72&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?name=Forums&file=viewtopic&t=2&rush=%6c%73%20%2d%61%6c&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?name=forums&file=viewtopic&t=2&rush=%6c%73%20%2d%61%6c&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?Nikto=Forums&file=viewtopic&t=2&rush=%6c%73%20%2d%61%6c&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?Nikto=forums&file=viewtopic&t=2&rush=%6c%73%20%2d%61%6c&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?name=PNphpBB2&file=viewtopic&t=2&rush=%6c%73%20%2d%61%6c&highlight=%2527.%70%61%73%73%74%68%72%75%28%24%48%54%54%50%5f%47%45%54%5f%56%41%52%53%5b%72%75%73%68%5d%29.%2527: Output from the phpinfo() function was found.
> + /index.php?vo=\"><script>alert(document.cookie);</script>: Output from the phpinfo() function was found.
> + /index.php?showforum=1&prune_day=100&sort_by=Z-A&sort_key=[sqlgoeshere]: Output from the phpinfo() function was found.
> + /index.php?offset=[%20Problem%20Here%20]: Output from the phpinfo() function was found.
> 

Because phpinfo() is present on index.php a high number of false positives fill up the terminal/output making reviewing results a pain, and storing them a bit of a cleanup job. It would be great to have a flag to pass to nikto to limit the number of times a single issue could be reported (something like --limit-report x) which would help to limit these false positives in certain use cases, but not get in the way of the regular nikto functionality we all love.

**Comment by sullo** [comment]
This has got to be a bug but I'm not spotting it immediately; I'll have to do some testing. 

The code in question is in nikto_content_search.plugin and is supposed to already do what you're asking. It's possible %CSMATCHED isn't persisted across calls and it's just a scoping thing.  

`    foreach my $testid (@$CONTENTSEARCH) {
        if ($body =~ $testid->{'compiled'}
            && !exists $CSMATCHED{ $mark->{'hostname'} }{$file}) {

            # Check whether we've already matched it
            my $outmessage = "$file: $testid->{'message'}";
            add_vulnerability($mark, $outmessage, $testid->{'nikto_id'}, $testid->{'osvdb'}, $method, $file, $request, $response);
            $CSMATCHED{ $mark->{'hostname'} }{$file} = 1;
        }
`

**Comment by sullo** [comment]
commit e422f74 makes minor changes here but the issue is that the uniqueness is on the full URI, and not just the file. So you shouldn't see multiple "/index.php" but for each one with a distinct query string it would repeat. 

I open it up for discussion on which works best. @tautology0 what do you think? I'm leaning towards making it path/file level and ignore query string.

**Comment by codingo** [comment]
That's good to know, I've definitely faced this in a variety of circumstances so assumed there wasn't already code present to do this. Since this has been updated on master I'll report back if I experience further issues like  this.

Unfortunately I can't re-test the original output since I cleaned it up / anonymised it from a site I know longer have permission to test against.

**Comment by sullo** [comment]
My changes shouldn't impact how it reports yet. I think I will make the
change but had to think about it a little!

On May 5, 2018 3:45 AM, "Michael" <notifications@github.com> wrote:

That's good to know, I've definitely faced this in a variety of
circumstances so assumed there wasn't already code present to do this.
Since this has been updated on master I'll report back if I experience
further issues like this.

Unfortunately I can't re-test the original output since I cleaned it up /
anonymised it from a site I know longer have permission to test against.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sullo/nikto/issues/532#issuecomment-386787425>, or mute
the thread

**Comment by tautology0** [comment]
Removing the query string in the internal hash would be the simplest thing, but, there is the case where the output only happens with some query strings and not others.

TBH I'm not certain there's any "good" solution to this and ultimately it will come down to the judgement of the tester. So... I would say ignore the query string for the match and expect the tester to manually visit the page to verify weirdness.

**Comment by sullo** [comment]
This should work differently now and only match on path/file.
