### ISSUE TITLE
Not possible to start Nikto from other directory

### ISSUE THREAD

**Issue by johndekroon** [sullo/nikto#534]
Hi,

It doesn't seem to be possible to start Nikto from another directory than the directory where Nikto is located. If I cd to ./plugins/nikto it works fine.

`./example/nikto/nikto.pl `
`Can't locate /var/example/nikto_core.plugin in @INC (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./example/nikto/nikto.pl line 55.`

Edit: changed the dir from plugins to example, as this was confusing and not related to Nikto.

**Comment by digininja** [comment]
The nikto.pl file shouldn't be in plugins/nikto, it should be in the program directory. Have you moved the binary by accident?

**Comment by johndekroon** [comment]
That was not the plugins directory of Nikto, it was unrelated to Nikto.
