### ISSUE TITLE
Uncommon header 'x-frame-options' found, with contents: SAMEORIGIN

### ISSUE THREAD

**Issue by arunsolo1984** [sullo/nikto#537]
I am using Nikto 2.1.5

X-Frame-Options is supported in our apache httpd.conf
**Header always set X-Frame-Options: "SAMEORIGIN"**

We ran nikto scan. We are getting **"Uncommon header 'x-frame-options' found, with contents: SAMEORIGIN"** vulnerability. When i debug in your db_headers, i don't see **x-frame-options** present in it. But in your Nikto 2.1.6, I could see the **x-frame-options** present in your db_headers. With Nikto 2.1.6, no issues.

In your website, Nikto Stable release version is Nikto v2.1.5. So, I have taken Nikto v2.1.5. But in your github, Nikto 2.1.6 release is there. 

As we are progressing to production, we need to fix the vulnerability. Which version of Nikto would be best to use?

**Comment by tautology0** [comment]
2.1.5 is getting rather old in the tooth (as it came out before x-frame-options existed). So we advise using the github version (2.1.6) now.

Having X-Frame-Options is a good thing as it offers a basic protection against clickjacking; so believe 2.1.6!

**Comment by tautology0** [comment]
If you look on github and releases you should see the tarball for 2.1.6. @sullo, we should probably update the site to point towards 2.1.6 as the stable release...

**Comment by arunsolo1984** [comment]
Thanks for the information.

**Comment by sullo** [comment]
The web site now shows:
```Install (recommended): Run from a git repo -  https://github.com/sullo/nikto
Download: Latest GitHub Release (zip)```

I've completely removed the 2.1.5 link since it's so old.
