### ISSUE TITLE
IP found in version number

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#540]
I'm sure there was another instance of this recently with a different app, this header:

```
engine: IT Hit WebDAV Server .Net v2.1.1.108
```

Is reported as:
```
Message:        IP address found in the 'engine' header. The IP is "2.1.1.108".
```

**Comment by sullo** [comment]
Since i've seen this with a v### string before I'm excluding that. This might be better checking for a delimiter before the potential IP, but I don't want to false negative more.

Also made sure the octets are 1-3 digits since it was only 1 or more.
