### ISSUE TITLE
Latest CVEs

### ISSUE THREAD

**Issue by commsss** [sullo/nikto#541]
Hello. Forgive me if this is a basic question, but how do the CVEs get updated? Is it manual or ingested automatically? I've scanned a server with an old version of apache (v2.4.17) which is vulnerable to [these ](https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-66/version_id-199590/Apache-Http-Server-2.4.17.html)CVEs. So when scanning with nikto I was expecting a bunch of CVEs to be report, but none are?

Nikto v2.1.5
---------------------------------------------------------------------------
+ Target IP:          127.0.0.1
+ Target Hostname:    localhost
+ Target Port:        8080
+ Start Time:         2018-05-17 11:35:17 (GMT1)
---------------------------------------------------------------------------
+ Server: Apache/2.4.17 (Unix)
+ The anti-clickjacking X-Frame-Options header is not present.
+ No CGI Directories found (use '-C all' to force check all possible dirs)
+ OSVDB-877: HTTP TRACE method is active, suggesting the host is vulnerable to XST
+ 6544 items checked: 0 error(s) and 2 item(s) reported on remote host
+ End Time:           2018-05-17 11:35:27 (GMT1) (10 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested

**Comment by jorgedferreira** [comment]
Hi, has far as i've seen if you clone the repository, then just do a **git pull**in the same folder.
I tried using -update but the script warns not to do that.

**Comment by sullo** [comment]
you should receive an 'outdated' message on that version as the database has 2.4.33 as current. 

Tests are added manually by humans as needed/wanted.

And yes, if you're running 2.1.6 (git) then you should run a git pull to get the latest code.

hope that helps.
