### ISSUE TITLE
Selection of plugins not working

### ISSUE THREAD

**Issue by Horst88** [sullo/nikto#543]
Hi,
I am trying to select plugins for the execution. I was following https://cirt.net/nikto2-docs/options.html#id2791391

Calling:
./nikto.pl -Display V -host https://some-webserver.com -port 443 -Plugins "apache_expect_xss(verbose,debug)"

Leads to:
- Nikto v2.1.6
---------------------------------------------------------------------------
V:Wed Jun 13 03:11:13 2018 - Initialising plugin nikto_ms10_070
V:Wed Jun 13 03:11:13 2018 - Loaded "ms10-070 Check" plugin.
V:Wed Jun 13 03:11:13 2018 - Initialising plugin nikto_paths
V:Wed Jun 13 03:11:13 2018 - Loaded "Path Search" plugin.
V:Wed Jun 13 03:11:13 2018 - Initialising plugin nikto_negotiate
V:Wed Jun 13 03:11:13 2018 - Loaded "Negotiate" plugin.
...
Also all plugins are executed, ...

What am I doing wrong? Is it also possible to use plugins without any options? Listing the plugins I only receive the name of the plugin, ... 
nikto -Display V -Plugins "Path Search" -host https://some.webserver.com

Your help is appreciated!!!

**Comment by tautology0** [comment]
Plugins will always be initialised (i.e. loaded and the initial plug in template read) and loaded (if they support the load hook, normally for initialising plugin variables).

To request only one plugin you should just need to provide the shortname of the Plugin, e.g.:
perl ./nikto.pl -host https://www.evilsite.co.uk -Plugins httpoptions

Some things will always be run, such as 404 detection (unless you use -no404) and a basic check that the server works. E.g.:

```
c:\tools\web\nikto\program>perl ./nikto.pl -host https://www.evilsite.co.uk -Plugins httpoptions(verbose) -no404
- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          81.27.85.11
+ Target Hostname:    www.evilsite.co.uk
+ Target Port:        443
---------------------------------------------------------------------------
+ SSL Info:        Subject:  /CN=evilsite.co.uk
                   Ciphers:  ECDHE-RSA-AES256-GCM-SHA384
                   Issuer:   /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
+ Start Time:         2018-06-19 14:02:12 (GMT1)
---------------------------------------------------------------------------
+ Server: Apache
V:Tue Jun 19 14:02:13 2018 - 200 for OPTIONS:   *
V:Tue Jun 19 14:02:13 2018 - 200 for OPTIONS:   /
+ Allowed HTTP Methods: POST, OPTIONS, HEAD, GET
V:Tue Jun 19 14:02:13 2018 - 501 for JBECSUDS:  /
V:Tue Jun 19 14:02:13 2018 - 501 for DEBUG:     /
V:Tue Jun 19 14:02:13 2018 - 400 for PROPFIND:  /
V:Tue Jun 19 14:02:14 2018 - 400 for TRACE:     /
V:Tue Jun 19 14:02:14 2018 - 405 for TRACE:     /
V:Tue Jun 19 14:02:14 2018 - 400 for TRACK:     /
V:Tue Jun 19 14:02:14 2018 - 501 for TRACK:     /
+ 11 requests: 0 error(s) and 1 item(s) reported on remote host
+ End Time:           2018-06-19 14:02:14 (GMT1) (2 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested
```
The verbose parameter has been added to demonstrate it enabling verbose only during the plugin.

Plugins shortnames are separated by ; It's best to think of them as function calls.
