### ISSUE TITLE
define Interface, feature request

### ISSUE THREAD

**Issue by kaktis** [sullo/nikto#545]
I have been trying to find a way to tell nikto which interface to utilize when i'm scanning from a system with multiple interfaces. If this is already possible please let me know, but a feature similar to nmap's -e or curl's --interface is what i'm suggesting...

**Comment by sullo** [comment]
You can specify it using the IP as the target and setting the vhost to the server name, such as:

> nikto.pl -h 10.10.10.1 -vhost example.com
