### ISSUE TITLE
Malformed csv export

### ISSUE THREAD

**Issue by J12934** [sullo/nikto#547]
Hi!
I'm running into Problems with the CSV Export Format where the csv export is always malformed.

I'm running nikto against a default nginx server and its doesn't correctly terminate the address string but has this `SCALAR(0x557689c70878)` thing instead. (The number changes from scan to scan)
```csv
"Nikto - v2.1.6/2.1.5"
"192.168.178.72","192.168.178.72","80","","","","nginx/1.13.9"
"192.168.178.72","192.168.178.72SCALAR(0x557689c70878)"80","OSVDB-0","GET","/","The anti-clickjacking X-Frame-Options header is not present."
"192.168.178.72","192.168.178.72SCALAR(0x557689c70878)"80","OSVDB-0","GET","/","The X-XSS-Protection header is not defined. This header can hint to the user agent to protect against some forms of XSS"
"192.168.178.72","192.168.178.72SCALAR(0x557689c70878)"80","OSVDB-0","GET","/","The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type"
```

I'm running the latest version of nikto from github with the following arguments:
```sh
nikto -F csv -o /tmp/report.csv -h localhost -p 80
```

**Comment by tautology0** [comment]
Fixed in trunk - there was a double quote missing on that line. How the heck we missed that I don't know!

**Comment by J12934** [comment]
Wow that was quick 😉
Thank you!

**Comment by tautology0** [comment]
It would have been quicker but Strawberry perl's connect function doesn't want to work on Windows 10 anymore so I had to fire up a VM.

**Comment by sullo** [comment]
@tautology0 that was from a recent check-in when I fixed the potential to execute commands via csv->excel, so it hasn't been around long.

Does this resolve the SCALAR issue as well?

**Comment by J12934** [comment]
CSV is now completly valid for me without the SCALAR
