### ISSUE TITLE
db_headers not updated at CIRT

### ISSUE THREAD

**Issue by webtoman** [sullo/nikto#554]
I noticed that nikto 2.1.5 on Ubuntu 18.04 was reporting, among other common security headers

`Uncommon header 'x-xss-protection' found, with contents: 1; mode=block`

so I ran (sudo) nikto -update, and ran it again, only to see the same error. Seems like it has not got the most recent db_headers", which when I look in git are from 2014. When I run 2.1.6 straight from git, it works fine. 

Why isn't db_headers updated when I run nikto -update?

$ nikto -update
+ Retrieving 'nikto_cookies.plugin'
+ Retrieving 'db_tests'
+ Retrieving 'nikto_headers.plugin'
+ Retrieving 'db_parked_strings'
+ Retrieving 'nikto_report_csv.plugin'
+ Retrieving 'CHANGES.txt'
+ CIRT.net message: Please submit Nikto bugs to https://github.com/sullo/nikto

**Comment by sullo** [comment]
You should only run from from the git repo, see:
https://cirt.net/Nikto-Installing_and_Updating
