### ISSUE TITLE
Web Server returns a valid response with junk HTTP methods, this may cause false positives.

### ISSUE THREAD

**Issue by marcoczen** [sullo/nikto#556]
Hi,

With regards to the output;
 
" XAUTSODN Web Server returns a valid response with junk HTTP methods, this may cause false positives" , 

how do we fix this ?

Googling doesnt give anything explicit.
Any ideas/fix suggestions  would be appreciated.

**Comment by sullo** [comment]
This is not so much a security issue but a problem for the scanner. It is likely the server's 5xx error message is sending a 200 for some reason. The fix would be server specific.

**Comment by sullo** [comment]
Nikto is not doing a GET request, which is what curl is doing. You'd have to craft a request by hand or use another tool (e.g., Burp or ZAP) to create one (or even proxy nikto so you can see the request and response).

As I said, this is more an issue for the scanner and not a security issue with the server.

**Comment by marcoczen** [comment]
Ok. Thanks.
