### ISSUE TITLE
Multiple roots for a single target

### ISSUE THREAD

**Issue by RTaschler** [sullo/nikto#56]
To help with scanning multiple roots for a host, allow a file of hosts to have notation like:
http://example.com/root1/
http://example.com/root2/
and/or:
http://example.com/ /root1/ /root2/ /root3/

Alternately, the -root option could be modified to allow multiple values.

Originally suggested here: http://attrition.org/pipermail/nikto-discuss/2008-April/000026.html

**Comment by sullo** [comment]
I think this can be solved by running Nikto multiple times. The code required would mean a lot of changes due to technical debt. This would be better handled in a new version.
