### ISSUE TITLE
Nikto failed to process scan if password has "-" 

### ISSUE THREAD

**Issue by faisalusuf** [sullo/nikto#564]
Hi,
The Nikto version 2.1.6 when trying to scan a URL having password including "-" the command failed to run with error. Below is the reference:
root@kali:~# nikto -id admin:ableEL|-|r -h http://192.168.204.26
bash: r: command not found
bash: -: command not found

Thanks

**Comment by tautology0** [comment]
That's not nikto; that's because you have a | in the command and the shell is picking it up before it's passed to nikto. I.e. it's doing 
```
nikto -id admin:ableEL | 
- |
r -h http://192.168.204.26
```

Use single quotes around the user/password string or backslash it out to stop bash picking it up as a pipe.

**Comment by faisalusuf** [comment]
During a pentest how can u instruct customer to modify it if password has | the nikto cant proceed why its picking up password string while space is the delimiter for next switch. 

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 10, 2018 at 7:39 PM, D L<notifications@github.com> wrote:   
That's not nikto; that's because you have a | in the command and the shell is picking it up before it's passed to nikto. I.e. it's doing
nikto -id admin:ableEL | 
- |
r -h http://192.168.204.26

Use single quotes around the user/password string or backslash it out to stop bash picking it up as a pipe.

**Comment by sullo** [comment]
Again, the shell is interpreting them as commands, so you need to quote them so they are passed to nikto.pl as a single argument:
> nikto -id 'admin:ableEL |- |r' -h http://192.168.204.26

**Comment by faisalusuf** [comment]
Awesome thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 10, 2018 at 11:12 PM, sullo<notifications@github.com> wrote:   
Again, the shell is interpreting them as commands, so you need to quote them so they are passed to nikto.pl as a single argument:


nikto -id 'admin:ableEL |- |r' -h http://192.168.204.26
