### ISSUE TITLE
Typical Websphere root directories

### ISSUE THREAD

**Issue by dsolstad** [sullo/nikto#574]
The following directories should maybe be added when searching for IBM WebSphere installations:

- /ibm/console/
- /console/
- /console/portal/0/Welcome

I have found WebSphere installations in these directories before, without Nikto mentioning it.

**Comment by sullo** [comment]
Added a test for /ibm/console/logon.jsp to catch that. There is a test for /console/ looking for a 200, so not sure why that didn't trip. I can't find a sample of /console/portal/* so I can't add a test (I'm no longer any adding generic 200/OK tests for product specific files/dirs).

If you have a sample from either of the other two I can add checks for them. I just need to see the HTML source or know some unique strings that can be matched upon.
