### ISSUE TITLE
HTTP/2 support in LW?

### ISSUE THREAD

**Issue by defanator** [sullo/nikto#578]
It would be nice to be able to make use of HTTP/2 while doing the testing for particular domains / resources.

Is it something that would be considered for implementing in future?

Alternatively, is there a way of "exporting" requests from nikto databases in a form of curl commands, for example? (i.e. including all the headers, cookies, bodies, etc.)

Appreciate any input.

**Comment by sullo** [comment]
I don't have any plans to implement HTTP/2 in LW any time soon. while it pains me to say it, putting the effort into porting all of it to a different language would be a better use of time.

To answer your second question--are you looking for for every request to be a wget or just the findings? If the latter, I would use -Savedir and get a json version of each request which should be trivial to parse into wget statements.
