### ISSUE TITLE
False Positive for phpLiteAdmin

### ISSUE THREAD

**Issue by allupaku** [sullo/nikto#579]
There is a false positive for phpLiteAdmin detection in a drupal 8 environment.
I believe the reason is that, the db_test is not checking for status code and only checking for "phpliteadmin.php" , which some how is also covering for string which appears as one of the class "phpliteadmin phpLiteAdmin-" .
**Information**
Test ID:  	007127
OSVDB ID: 	0
Message:  	/phpLiteAdmin/: phpLiteAdmin console found.
Reason:   	Content Match
Request
GET /phpLiteAdmin/ HTTP/1.1
Host:..
**Response**
HTTP/1.1 404 Not Found
server: nginx

body tag 
<body class="anonymous path-**phpliteadmin php**LiteAdmin- .."

I tried grep "phpliteadmin.php" in the terminal and i believe that is also returning a match.

**Comment by iasdeoupxe** [comment]
@allupaku Isn't this already fixed in https://github.com/sullo/nikto/pull/580 ? If yes let's close?
