### ISSUE TITLE
take nikto.conf out of repo

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#587]
It is annoying to have to fight with git each time I do an update and I've changed the config file.

With DVWA we renamed the config file in the repo to .conf.dist and told people to copy the file and set it up. Caused some problems initially but calmed down after a while with good error messages.

Another option is to have a default config .conf.default, which is in the repo and let people create .conf if they want to override it but fall back to there if they don't.

**Comment by tautology0** [comment]
Good idea, fixed in 79225c796f533f87f843a3c4968f6680e081ca6b
