### ISSUE TITLE
Write site details to log on connection failure

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#589]
I've just scripted Nikto to run against 50+ sites, some active, some not. I've got all output going to text files.

When Nikto can't connect to a site, all that gets written to the log is:

```
- Nikto v2.1.6/2.1.5
```

But when it connects you get this extra bit of info as well as the results:

```
- Nikto v2.1.6/2.1.5
+ Target Host: abc.com
+ Target Port: 443
```

It would be nice to have that extra bit in all the logs and maybe even an extra line to say that the scan failed with a reason.

I create the log files with the name of the site so I can work out from that which failed, but it would be nice to have it in the file itself to make command line reporting easier.

**Comment by sullo** [comment]
This was a pretty subtle bug thanks for pointing it out. I committed a change which should fix it.

**Comment by digininja** [comment]
You know, you put other devs to shame with the speed you fix things up.

**Comment by sullo** [comment]
hahah... just don't look at all the old unanswered issues :P

**Comment by tautology0** [comment]
I'm sure we have a few that are over 10 years old if you count that we moved them from assembla to here...

**Comment by sullo** [comment]
I should go close them all so I feel better OSS life.
