### ISSUE TITLE
showing error about config file

### ISSUE THREAD

**Issue by bhatumar533** [sullo/nikto#592]
the error its showing is below
Could not find a valid nikto config file. Tried: nikto.pl/nikto.conf.default /etc/nikto.conf /data/data/com.termux/files/home/nikto.conf nikto.pl/nikto.conf nikto.conf

**Comment by digininja** [comment]
It shouldn't have nikto.pl in the path names, looks like something went
wrong on the recent update.

**Comment by sullo** [comment]
Can you confirm you're running the latest from git ? Also your os.

Thanks

**Comment by pple7000** [comment]
change file name    >nikto/program/nikto.conf.default to 
nikto/program/nikto.conf

**Comment by sullo** [comment]
@pple7000 it should still work if there's no .conf file. If yours didn't please let me know. I tested quite a few combos of that and all worked--so there could be a bug if it didn't for you. 

Also as digininja pointed out something is borked with the path in @bhatumar533 output.

**Comment by pple7000** [comment]
Nmm.....I'm not good at Perl.Maybe just wait for next update.(Fixing the path)

**Comment by sullo** [comment]
@pple7000 that is just renaming the file, no code needed!

The path problem is more complex. What OS are you on?

**Comment by Hax0rG1rl** [comment]
Got the same issue here: 

```
perl nikto.pl -h https://<target>
- Could not find a valid nikto config file. Tried: nikto.pl/nikto.conf.default /etc/nikto.conf nikto.pl/program/nikto.conf.default /home/xxxxxxxx/nikto.conf nikto.pl/nikto.conf nikto.conf
```

**OS:** Ubuntu

**Installation:** The repository was cloned with git clone. 

I have tried to change some bits into the config file just to point nikto to the right default config file. No luck. Something is borked. 

You can use for testing this as I am using it: https://console.cloud.google.com/cloudshell/editor?
shellonly=true 

Thanks!

**Comment by sullo** [comment]
I think using Cwd module will help resolve these errors, and it's a core module so should not be an additional installation. 

please confirm?

**Comment by Hax0rG1rl** [comment]
I confirm the issue was resolved. Thanks!

**Comment by chris-camm** [comment]
I get the same issue when installing via brew install nikto on mac osx.

- Could not find a valid nikto config file. Tried: /usr/local/Cellar/nikto/2.1.6/bin/nikto/nikto.conf.default /etc/nikto.conf /Users/xxxxx/nikto.conf /usr/local/Cellar/nikto/2.1.6/bin/nikto/nikto.conf nikto.conf
