### ISSUE TITLE
Termux compatibility

### ISSUE THREAD

**Issue by Escxtt23** [sullo/nikto#594]
Fix netssleay

**Comment by digininja** [comment]
Manners Maketh Man!

https://www.youtube.com/watch?v=HWYLFizhjHs&feature=youtu.be&t=45

**Comment by sullo** [comment]
@Escxtt23 you can change the default SSL config in nikto.conf file. 

`# Choose SSL libs:
# SSLeay        - use Net::SSLeay
# SSL           - use Net::SSL
# auto          - automatically choose what's available
#                 (SSLeay wins if both are available)
LW_SSL_ENGINE=auto`

If Termux doesn't have either of them, you'd need to install or address with the Termux people.

**Comment by Escxtt23** [comment]
Thanks for the feedback Really Helpful🎉
