### ISSUE TITLE
JSON export is not valid json

### ISSUE THREAD

**Issue by NicolasCARPi** [sullo/nikto#599]
Hello,

When exporting in JSON format, the produced .json file is invalid.

The problem is at the end of the file, where extra commas characters appear where they should not: 
![2019-03-28-020322_108x32_scrot](https://user-images.githubusercontent.com/3043706/55122116-ecb8e900-50fd-11e9-880b-dab51cbf57ba.png)

Removing the commas lead to a valid json, as trailing commas are not allowed (unfortunately imho):
![2019-03-28-020330_100x35_scrot](https://user-images.githubusercontent.com/3043706/55122126-f6425100-50fd-11e9-8a07-dcb53c08e3c8.png)

To reproduce, scan a site with `-o out.json` and try to open the file in firefox, the json cannot be parsed. Now remove the commas at the end and json will be correctly parsed.

Cheers,
~Nico

**Comment by Ncoder2** [comment]
Hello, It looks like this issue is still present in 2.1.6 too. But i see it is marked fixed and unverified here. 
Did anything change ?

**Comment by NicolasCARPi** [comment]
@Ncoder2 Looks good to me, but make sure to remove the file from a previous scan, as it will append to it in a nonjson compatible manner.

**Comment by Ncoder2** [comment]
I am running kali 2021.2, Nikto 2.1.6, i ran this output - nikto -h 192.168.0.1 -Format json -o nikto.json 
i still get the trailing commas in the end - },],}

**Comment by Ncoder2** [comment]
Hi Sullo,

I had updated my comment on the ticket, could you please take a look and
let me know if the command is right ?

**Comment by NicolasCARPi** [comment]
But 2.1.6 was tagged back in 2015!!!

Try it from latest master version!

**Comment by tautology0** [comment]
For quite a while we've been saying to run master. @sullo is getting ready to release 2.5.0, until then we're currently only doing patches in master.

**Comment by Ncoder2** [comment]
Ok thank you ! Sorry, some mistake from my end then. Let me try again.
Thank you !

**Comment by Ncoder2** [comment]
It's very interesting, not sure what could be the reason, but i tried in
master, also 2.5.0, when I ran the scan, the version did reflect correctly.
But the comma issue still exists. I am not sure if an existing installation
of the old version in kali would make an impact.

**Comment by digininja** [comment]
I've just used the latest master and the JSON is valid, I've checked it with `jq` which will complain if there are any errors.

**Comment by sullo** [comment]
@Ncoder2 can you post what command line options you're using? one host/port, or more than one, etc.? It may be a combination edge case I didn't test. 

Also, as @tautology0 said we highly recommend using a version installed from Git (either master or nikto-2.5.0 branch) and not from Kali. 2.5.0 is very stable now--I'm just trying to resolve an SSL issue before it can be released.

**Comment by Ncoder2** [comment]
I will brief my steps here:
1. Initially i tried using the default kali installed version  `nikto -h 192.168.0.1 -Format json -o nikto.json`
2. The extra commas in the json popped up
3. I then pulled the code from GIT master and re-ran it using this command  `./nikto.pl -h 192.168.0.1 -Format json -o nikto.json`
4.I check the version its 2.1.6 in the output, the json error is still present.

Could it because the existing installation in kali is causing this trouble ?

**Comment by digininja** [comment]
Working fine for me with the latest from master and from 2.5

[image: image.png]

**Comment by tautology0** [comment]
Kali messes around with the configuration; so it's probably taking the plugins dir from /etc/nikto.conf. Try running
`./nikto.pl -C nikto.conf.default -h 192.168.0.1 -o nikto.json`

**Comment by Ncoder2** [comment]
so that didn't work too for me, but i got where it messed up. I tried the following steps:

1. I removed existing installation in kali `sudo apt-get remove nikto`
2. Then when i ran this `./nikto.pl -C nikto.conf.default -h 192.168.0.1 -o nikto.json `
3. I got this error `Can't locate /var/lib/nikto/plugins/nikto_core.plugin at ./nikto.pl line 54.`
4. I looked at nikto.pl, between lines 262 and 267 i saw multiple places the conf file could be present and removed the one at `rm -rf /etc/nikto.conf`
5. Then re-ran the command just as usual `./nikto.pl -h 192.168.0.1 -o nikto.json`
6. It did not have the additional commas. Thank you all for the help !

**Comment by NicolasCARPi** [comment]
@Ncoder2 also to avoid such issues in the future, feel free to use the Docker image ;) This way you are sure to run the latest version of the software without interference from the system.

**Comment by digininja** [comment]
Apt-get remove doesn't remove config files, you need to add an extra flag
for that, I think is purge but can't be sure.

**Comment by sullo** [comment]
Thanks for the help everyone!

**Comment by Ncoder2** [comment]
Thank you All ! 
i was trying to automate a few tools together, will sure move to the docker version once things get stable. Also, if the host is invalid or not up, the json that is generated has an extra '}', not sure if this is fixed.
But just wanted to check here, this is the response i get 
`{"id": "000029","OSVDB": "0","url":"/","msg":"No web server found on 192.168.0.1:80"}}`

Notice the extra } in the end, sorry all, not trying to bother too much, just thought will inform.

**Comment by digininja** [comment]
I would agree that the JSON is invalid when the host is invalid in both
2.5.0 and master.

[image: image.png]

**Comment by JaneX8** [comment]
I'm running master but this is still an issue. A snippet:

```json
[{
    "id": "999962",
    "method": "GET",
    "url": "/",
    "msg": ": Server banner changed from 'Microsoft-Azure-Application-Gateway/v2' to 'Microsoft-IIS/10.0'."
} {
    "host": "xxx",
    "ip": "xxx",
    "port": "443",
    "banner": "",
    "vulnerabilities": [\, {
        "id": "999986",
        "method": "GET",
        "url": "/",
        "msg": "Retrieved x-powered-by header: ASP.NET."
    }
```

The issue is `}{` and  `:[\,{`.

```bash
git tag -n
2.1.6           Merge pull request #268 from RealRancor/six_cms
2.5.0           Ran tidy for #727

git branch
* master

git show summary
commit b7233c38605b7d95084f661b071bc0cfd233dbc6 (HEAD -> master, origin/master, origin/HEAD)
Author: Sullo <sullo@ranger3.local>
Date:   Fri Nov 15 16:31:52 2024 -0500

    Add some Azure App Service headers
```

I scan with these parameters: 

```
/apps/nikto/program/nikto.pl -host example.com -port 443 -ipv4 -Cgidirs none -maxtime 240 -timeout 3 -ask auto -nointeractive -no404 --Format json -output "/tmp/somefile.json".

Lastly, the target I scanned has two redirects:
1. A HTML-metadata refresh redirect from https://a.example.com to https://b.example.com 
2. A HTTP 302 redirect from https://b.example.com to https://b.example.com/login
```
