### ISSUE TITLE
Screenshots of findings

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#6]
Take "screen shots" of the main page, as well as findings and store/use for HTML report.

**Comment by tautology0** [comment]
I'm not sure we can do this and retain the principle that Nikto will run anywhere that just has perl.

Looks like a good WONTFIX candidate.

**Comment by digininja** [comment]
This would be a cool idea but agree it isn't really a Nikto thing.
Especially as some findings are header based.

If we've got a save file then we've got the request, I might talk to Chris
Truncer to see how hard it would be to modify EyeWitness to be able to fire
a request through that.

**Comment by sullo** [comment]
I was also just wondering if we could send a request to eye/go witness to
capture. That's be hella easier.

**Comment by tautology0** [comment]
The laziest way would be to write a simple script that would take a Nikto HTML/XML report and pass it to EyeWitness and output a new report.

**Comment by digininja** [comment]
The only problem with that would be where you need to set special headers.
There is also no point in taking screenshots of things like internal IP
disclosure through HTTP/1.0 so would need to flag those to avoid

**Comment by sullo** [comment]
The more complicated it is the less likely it is to get done. Since we are
not doing severities there's no way way too filter via that. Could use vuln
class but that's all I can think of.

Also would need a max amount for those servers that don't play nice with
us, to avoid spiraling.

**Comment by digininja** [comment]
I've passed the idea to Chris to have a think about. We have to be able to
think of something, just might not be practical in the end.

**Comment by digininja** [comment]
I talked to Chris, he says the thing he uses for screenshots will only take a URL, it can't accept raw headers so not as easy as I hoped it might be.

Probably best add this to a todo list and leave it for now, come back to it if anyone gets time and wants a project.

**Comment by sullo** [comment]
Closing this as Won't Do. JSON output in -Savedir can be used to see the content. I don't think screenshots should be part of nikto--there are better tools.
