### ISSUE TITLE
Nikto Docker Permissions

### ISSUE THREAD

**Issue by sullo** [sullo/nikto#600]
Nikto runs as root when in run in the Docker.

Tag @mostafahussein

**Comment by drwetter** [comment]
see #602

**Comment by mostafahussein** [comment]
@drwetter , How could i add my PR :D I was working on it with other enhancements :/

**Comment by drwetter** [comment]
Recommend to @sullo to merge mine and then you use that as a base?

**Comment by sullo** [comment]
@drwetter & @mostafahussein I merged #602

**Comment by mostafahussein** [comment]
@drwetter we are good, I will use the updated file to add the other enhancements. Thanks to you and to @sullo

**Comment by felipenazario** [comment]
This should be closed, since it was fixed.
