### ISSUE TITLE
More proxy connection problems

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#604]
I've got Burp listening on localhost:8080, I tried pointing Nikto through it and it failed with this error:

```
$ ./program/nikto.pl  -host https://digi.ninja/ -useproxy http://localhost:8080 
- Nikto v2.1.6
---------------------------------------------------------------------------
+ ERROR: Proxy error: opening stream: can't connect: proxy connect failed: proxy connect to localhost:8080 failed: Invalid argument at /home/robin/tools/web/nikto/program/plugins/LW2.pm line 5157.
; Invalid argument at /home/robin/tools/web/nikto/program/plugins/LW2.pm line 5157.
: Invalid argument
```
Just in case there was a listener problem, I checked curl can use the Burp proxy without any problems:
```
$ curl https://digi.ninja --proxy localhost:8080 -I
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
Date: Wed, 03 Apr 2019 19:37:11 GMT
Server: Apache
X-Powered-By: Rainbows and XSS<script>alert(1)</script>
Strict-Transport-Security: max-age=63072000
```

**Comment by brianwoo** [comment]
I am also having the same issue with Nikto v2.1.6 on Kali.

**Comment by sullo** [comment]
@brianwoo I don't really support the installation on Kali. If you're running from git version let me know.

**Comment by sullo** [comment]
@digininja that line of LW.pm closes out an ssl-stream opening. If you can still test this two quick things:
* does it work if your target is http?
* are you able to switch to using Net::SSLeay over Net::SSL in nikto.conf?
```# Choose SSL libs:
# SSLeay        - use Net::SSLeay
# SSL           - use Net::SSL
# auto          - automatically choose what's available
#                 (SSLeay wins if both are available)
LW_SSL_ENGINE=auto```

**Comment by brianwoo** [comment]
Actually I figured it out.  I have to use -nossl to make it work for some reason:

nikto.pl  -h https://digi.ninja/ -useproxy -nossl -ask no

This works fine.

**Comment by tautology0** [comment]
That would make sense in a perverse way - the connection to the proxy is over HTTP, so Nikto doesn't need to initiate a TLS connection. Not certain the best way to make this usable.

**Comment by digininja** [comment]
Switching to SSLeay works, using the `-nossl` also works but I think that is a red herring and probably not the right solution to go with.

**Comment by tautology0** [comment]
Workaround is to force SSLeay. Closing for now.
