### ISSUE TITLE
Invalid XML with variables

### ISSUE THREAD

**Issue by wheelq** [sullo/nikto#608]
Nikto is lanuched via:
```
/usr/local/bin/nikto -h <url> -Format xml -o /working/output/nikto-report.xml
```

But inside the XML it looks like there are some templating 'leftovers':
![image](https://user-images.githubusercontent.com/1497172/58723368-cf401e00-83d1-11e9-8e68-56831e10c9d9.png)

**Comment by wheelq** [comment]
is there any way I could help?

**Comment by sullo** [comment]
Tested this and it's working. Given your command line I assume this is on Kali, which we do not support because of reasons like this. It is recommend you clone this repo and run the program as intended.

If you're not on Kali, please reopen.
