### ISSUE TITLE
can we get a consistent "interesting" phrase in the output

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#609]
I've just done a scan where the site returned content for every test and while scanning through the output I noticed the following "interesting" messages:

* Might be interesting
* This may be interesting...
* This might be interesting...
* This could be interesting...

It would be good to consolidate them all into one singularly interesting phrase.

**Comment by sullo** [comment]
Happy now? 😄

**Comment by digininja** [comment]
1287 changes, is that all?

And you know I'll never be happy, I'll just keep driving you towards
perfection.

**Comment by sullo** [comment]
Hah! Well then you should be complaining about Perl!

**Comment by digininja** [comment]
How about a rewrite in Go then :)

My Perl skills are none existent so can't offer any help with coding at the
moment. Would happily help if I knew the language.
