### ISSUE TITLE
Using -maxtime option causes ERROR 

### ISSUE THREAD

**Issue by roydavisonline** [sullo/nikto#610]
adding -maxtime 1h to the cmd line causes the following error to be shown immediately in the output:

ERROR: Host maximum execution time of 3600 seconds reached

Value set does not seem to make any difference. An error still occurs.

**Comment by sullo** [comment]
What OS are you using? Are you running from the git current branch?

`./nikto.pl -h cirt.net -maxtime 2h
- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          159.65.167.152
+ Target Hostname:    cirt.net
+ Target Port:        80
+ Start Time:         2019-06-09 22:52:17 (GMT-4)
---------------------------------------------------------------------------
+ Server: Apache/2.4.29 (Ubuntu)
...`

**Comment by sullo** [comment]
Closing due to no reply.
