### ISSUE TITLE
Docker Desktop for Windows - No such file or directory

### ISSUE THREAD

**Issue by sandwich-destroyer** [sullo/nikto#615]
When executing Nikto in docker for windows it produces the error `': No such file or directory`

#### Steps to repeat:
1. Install Docker Desktop for Windows 10
2. Share your drive
3. `docker build -t nikto https://github.com/sullo/nikto.git`
4. `docker run --rm nikto`
```
C:\Users\kevin\Desktop > docker run --rm nikto
': No such file or directory
```

**Comment by sandwich-destroyer** [comment]
Error is reproducible if you clone the project and build locally as well.

**Comment by xfournet** [comment]
A workaround to build the image on Windows

```
git clone https://github.com/sullo/nikto.git
cd nikto

git config core.autocrlf false
git add --renormalize .
git rm -r .
git checkout HEAD -- .

docker build -t sullo/nikto .
docker run --rm sullo/nikto
```
