### ISSUE TITLE
XML export requires DTD

### ISSUE THREAD

**Issue by mario-platt** [sullo/nikto#616]
When running nikto through Docker command line and passing all arguments through the CLI, and trying to export as XML, it doesn't work as the XML export seems to require a config file to be defined. Can't see why that would be a requirement ? Other export formats work fine without it.

    # verify readable dtd
    if ($CLI{'format'} eq 'xml' && !-r $CONFIGFILE{'NIKTODTD'}) {
        nprint("+ ERROR: reading DTD")

**Comment by sullo** [comment]
You should have a defined config file though... it doesn't error when a config file isn't found?

**Comment by dogwynn** [comment]
The default install by homebrew on mac has this issue as well.

**Comment by sullo** [comment]
DTD as a readable file no longer required. DTD must still be defined, though, in nikto.conf.

Commit 3eed26ffa58b06c77e37893f837660ae767847ca
