### ISSUE TITLE
Feature request: Dependency management for db_tests

### ISSUE THREAD

**Issue by iasdeoupxe** [sullo/nikto#623]
While implementing #621 and #622 i have noticed that Nikto seems to not have any dependency management.

We could prevent false positives and / or improve the performance if it would be possible to e.g. specify that 007259 has a dependency to 007258 (IDs from #621) so that 007259 is only running if 007258 was detected.

**Comment by sullo** [comment]
This is a good idea but not something I'm going to implement as it would take a *lot* of rewriting to make this happen. Maybe a future version (non-PERL).
