### ISSUE TITLE
No web server found

### ISSUE THREAD

**Issue by aether0011** [sullo/nikto#627]
I installed nikto on macOS through brew and got the below message when I do a test run.

:Sun Sep  1 23:09:17 2019 - Initialising plugin nikto_multiple_index
V:Sun Sep  1 23:09:17 2019 - Loaded "Multiple Index" plugin.
V:Sun Sep  1 23:09:17 2019 - Getting targets
V:Sun Sep  1 23:09:17 2019 - Target:www.exampleabc.com port:80
V:Sun Sep  1 23:09:17 2019 - Checking for HTTP on port www.exampleabc.com:80, using HEAD
V:Sun Sep  1 23:09:17 2019 -  for HEAD:
V:Sun Sep  1 23:09:17 2019 - Checking for HTTPS on port www.exampleabc.com:80, using HEAD
V:Sun Sep  1 23:09:17 2019 -  for HEAD:
V:Sun Sep  1 23:09:17 2019 - Checking for HTTP on port www.exampleabc.com:80, using GET
V:Sun Sep  1 23:09:17 2019 -  for GET:
V:Sun Sep  1 23:09:17 2019 - Checking for HTTPS on port www.exampleabc.com:80, using GET
V:Sun Sep  1 23:09:17 2019 -  for GET:
+ No web server found on www.exampleabc.com:80

So I tried again with (-D d) and it returned with the message below. Any idea why can't connect? Thanks!

D:Sun Sep  1 23:16:46 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_parked_strings
D:Sun Sep  1 23:16:46 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_404_strings
D:Sun Sep  1 23:16:46 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_outdated
D:Sun Sep  1 23:16:46 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_variables
D:Sun Sep  1 23:16:46 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_tests
- Nikto v2.1.6
---------------------------------------------------------------------------
D:Sun Sep  1 23:16:46 2019 WARNING: No init found for nikto_core
D:Sun Sep  1 23:16:46 2019 'Request Hash' = {
	'Host' => 'www.exampleabc.com',
	'whisker' => {
		'timeout' => 10,
		'force_open' => 0,
		'force_bodysnatch' => 0,
		'ssl' => 0,
		'http_eol' => "\r\n",
		'ssl_rsacertfile' => undef,
		'host' => 'www.exampleabc.com',
		'uri_prefix' => '',
		'ignore_duplicate_headers' => 1,
		'normalize_incoming_headers' => 1,
		'ssl_save_info' => 1,
		'port' => 80,
		'force_close' => 0,
		'uri' => '/',
		'trailing_slurp' => 0,
		'keep-alive' => 1,
		'include_host_in_uri' => 0,
		'lowercase_incoming_headers' => 1,
		'retry' => 0,
		'MAGIC' => 31339,
		'version' => '1.1',
		'method' => 'HEAD',
		'http_space2' => ' ',
		'uri_postfix' => '',
		'require_newline_after_headers' => 0,
		'ssl_certfile' => undef,
		'protocol' => 'HTTP',
		'invalid_protocol_return_value' => 1,
		'uri_param_sep' => '?',
		'http_space1' => ' ',
		'max_size' => 0
	},
	'Connection' => 'Keep-Alive',
	'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)'
};
D:Sun Sep  1 23:16:46 2019 'Result Hash' = {
	'whisker' => {
		'uri' => '/',
		'error' => 'opening stream: can\'t connect (connect error): -536870212',
		'MAGIC' => 31340
	}
};
D:Sun Sep  1 23:16:46 2019 'Request Hash' = {
	'Host' => 'www.exampleabc.com',
	'whisker' => {
		'uri_prefix' => '',
		'ssl_rsacertfile' => undef,
		'host' => 'www.exampleabc.com',
		'normalize_incoming_headers' => 1,
		'ssl_save_info' => 1,
		'ignore_duplicate_headers' => 1,
		'port' => 80,
		'uri' => '/',
		'trailing_slurp' => 0,
		'force_close' => 0,
		'timeout' => 10,
		'force_open' => 0,
		'force_bodysnatch' => 0,
		'http_eol' => "\r\n",
		'ssl' => 1,
		'protocol' => 'HTTP',
		'ssl_certfile' => undef,
		'invalid_protocol_return_value' => 1,
		'max_size' => 0,
		'uri_param_sep' => '?',
		'http_space1' => ' ',
		'lowercase_incoming_headers' => 1,
		'retry' => 0,
		'include_host_in_uri' => 0,
		'keep-alive' => 1,
		'version' => '1.1',
		'MAGIC' => 31339,
		'method' => 'HEAD',
		'uri_postfix' => '',
		'http_space2' => ' ',
		'require_newline_after_headers' => 0
	},
	'Connection' => 'Keep-Alive',
	'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)'
};
D:Sun Sep  1 23:16:46 2019 'Result Hash' = {
	'whisker' => {
		'MAGIC' => 31340,
		'error' => 'opening stream: can\'t connect (connect failed): -536870212',
		'uri' => '/'
	}
};
D:Sun Sep  1 23:16:46 2019 'Request Hash' = {
	'whisker' => {
		'ssl' => 0,
		'http_eol' => "\r\n",
		'force_bodysnatch' => 0,
		'force_open' => 0,
		'timeout' => 10,
		'trailing_slurp' => 0,
		'uri' => '/',
		'force_close' => 0,
		'port' => 80,
		'normalize_incoming_headers' => 1,
		'ssl_save_info' => 1,
		'ignore_duplicate_headers' => 1,
		'uri_prefix' => '',
		'ssl_rsacertfile' => undef,
		'host' => 'www.exampleabc.com',
		'require_newline_after_headers' => 0,
		'uri_postfix' => '',
		'http_space2' => ' ',
		'version' => '1.1',
		'MAGIC' => 31339,
		'method' => 'GET',
		'lowercase_incoming_headers' => 1,
		'retry' => 0,
		'keep-alive' => 1,
		'include_host_in_uri' => 0,
		'max_size' => 0,
		'uri_param_sep' => '?',
		'http_space1' => ' ',
		'invalid_protocol_return_value' => 1,
		'protocol' => 'HTTP',
		'ssl_certfile' => undef
	},
	'Connection' => 'Keep-Alive',
	'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)',
	'Host' => 'www.exampleabc.com'
};
D:Sun Sep  1 23:16:46 2019 'Result Hash' = {
	'whisker' => {
		'MAGIC' => 31340,
		'error' => 'opening stream: can\'t connect (connect error): -536870212',
		'uri' => '/'
	}
};
D:Sun Sep  1 23:16:46 2019 'Request Hash' = {
	'whisker' => {
		'http_space2' => ' ',
		'uri_postfix' => '',
		'require_newline_after_headers' => 0,
		'keep-alive' => 1,
		'include_host_in_uri' => 0,
		'retry' => 0,
		'lowercase_incoming_headers' => 1,
		'MAGIC' => 31339,
		'version' => '1.1',
		'method' => 'GET',
		'http_space1' => ' ',
		'uri_param_sep' => '?',
		'max_size' => 0,
		'ssl_certfile' => undef,
		'protocol' => 'HTTP',
		'invalid_protocol_return_value' => 1,
		'force_bodysnatch' => 0,
		'http_eol' => "\r\n",
		'ssl' => 1,
		'timeout' => 10,
		'force_open' => 0,
		'port' => 80,
		'force_close' => 0,
		'uri' => '/',
		'trailing_slurp' => 0,
		'ssl_rsacertfile' => undef,
		'host' => 'www.exampleabc.com',
		'uri_prefix' => '',
		'ignore_duplicate_headers' => 1,
		'normalize_incoming_headers' => 1,
		'ssl_save_info' => 1
	},
	'Connection' => 'Keep-Alive',
	'User-Agent' => 'Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:Port Check)',
	'Host' => 'www.exampleabc.com'
};
D:Sun Sep  1 23:16:46 2019 'Result Hash' = {
	'whisker' => {
		'uri' => '/',
		'MAGIC' => 31340,
		'error' => 'opening stream: can\'t connect (connect failed): -536870212'
	}
};
+ No web server found on www.exampleabc.com:80
---------------------------------------------------------------------------
+ 0 host(s) tested
D:Sun Sep  1 23:16:46 2019 T:Sun Sep  1 23:16:46 2019: Ending

**Comment by tautology0** [comment]
It can't connect to the host, literally, the server is closing the connection after it sends the headers.

Is this on AWS? Is there a WAF? Try changing the user agent, e.g. -O USERAGENT=Something

**Comment by aether0011** [comment]
hmm I tried on webscantest with useragent flag and I got the same result.

a:opt $ nikto -h http://webscantest.com/ -useragent FireFox -D d
D:Mon Sep  2 08:54:59 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_parked_strings
D:Mon Sep  2 08:54:59 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_404_strings
D:Mon Sep  2 08:54:59 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_outdated
D:Mon Sep  2 08:54:59 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_variables
D:Mon Sep  2 08:54:59 2019 - Loading DB: /usr/local/var/lib/nikto/databases/db_tests
- Nikto v2.1.6
---------------------------------------------------------------------------
D:Mon Sep  2 08:54:59 2019 WARNING: No init found for nikto_core
D:Mon Sep  2 08:54:59 2019 'Request Hash' = {
	'Connection' => 'Keep-Alive',
	'User-Agent' => 'FireFox',
	'Host' => 'webscantest.com',
	'whisker' => {
		'force_bodysnatch' => 0,
		'http_space1' => ' ',
		'force_open' => 0,
		'max_size' => 0,
		'uri_postfix' => '',
		'port' => 80,
		'protocol' => 'HTTP',
		'include_host_in_uri' => 0,
		'invalid_protocol_return_value' => 1,
		'ssl_certfile' => undef,
		'lowercase_incoming_headers' => 1,
		'uri' => '/',
		'retry' => 0,
		'require_newline_after_headers' => 0,
		'force_close' => 0,
		'method' => 'HEAD',
		'ssl_save_info' => 1,
		'normalize_incoming_headers' => 1,
		'ignore_duplicate_headers' => 1,
		'ssl' => 0,
		'MAGIC' => 31339,
		'http_space2' => ' ',
		'uri_prefix' => '',
		'timeout' => 10,
		'ssl_rsacertfile' => undef,
		'uri_param_sep' => '?',
		'http_eol' => "\r\n",
		'host' => 'webscantest.com',
		'keep-alive' => 1,
		'version' => '1.1',
		'trailing_slurp' => 0
	}
};
D:Mon Sep  2 08:54:59 2019 'Result Hash' = {
	'whisker' => {
		'error' => 'opening stream: can\'t connect (connect error): -536870212',
		'MAGIC' => 31340,
		'uri' => '/'
	}
};
D:Mon Sep  2 08:54:59 2019 'Request Hash' = {
	'User-Agent' => 'FireFox',
	'Connection' => 'Keep-Alive',
	'Host' => 'webscantest.com',
	'whisker' => {
		'trailing_slurp' => 0,
		'uri_param_sep' => '?',
		'keep-alive' => 1,
		'version' => '1.1',
		'http_eol' => "\r\n",
		'host' => 'webscantest.com',
		'MAGIC' => 31339,
		'http_space2' => ' ',
		'ssl' => 1,
		'ssl_rsacertfile' => undef,
		'timeout' => 10,
		'uri_prefix' => '',
		'method' => 'HEAD',
		'ignore_duplicate_headers' => 1,
		'ssl_save_info' => 1,
		'normalize_incoming_headers' => 1,
		'require_newline_after_headers' => 0,
		'retry' => 0,
		'uri' => '/',
		'force_close' => 0,
		'invalid_protocol_return_value' => 1,
		'lowercase_incoming_headers' => 1,
		'ssl_certfile' => undef,
		'uri_postfix' => '',
		'protocol' => 'HTTP',
		'include_host_in_uri' => 0,
		'port' => 80,
		'force_open' => 0,
		'http_space1' => ' ',
		'force_bodysnatch' => 0,
		'max_size' => 0
	}
};
D:Mon Sep  2 08:54:59 2019 'Result Hash' = {
	'whisker' => {
		'error' => 'opening stream: can\'t connect (connect failed): -536870212',
		'MAGIC' => 31340,
		'uri' => '/'
	}
};
D:Mon Sep  2 08:54:59 2019 'Request Hash' = {
	'whisker' => {
		'max_size' => 0,
		'force_bodysnatch' => 0,
		'http_space1' => ' ',
		'force_open' => 0,
		'port' => 80,
		'protocol' => 'HTTP',
		'include_host_in_uri' => 0,
		'uri_postfix' => '',
		'ssl_certfile' => undef,
		'lowercase_incoming_headers' => 1,
		'invalid_protocol_return_value' => 1,
		'force_close' => 0,
		'uri' => '/',
		'retry' => 0,
		'require_newline_after_headers' => 0,
		'normalize_incoming_headers' => 1,
		'ssl_save_info' => 1,
		'ignore_duplicate_headers' => 1,
		'method' => 'GET',
		'uri_prefix' => '',
		'timeout' => 10,
		'ssl_rsacertfile' => undef,
		'MAGIC' => 31339,
		'http_space2' => ' ',
		'ssl' => 0,
		'host' => 'webscantest.com',
		'http_eol' => "\r\n",
		'version' => '1.1',
		'keep-alive' => 1,
		'uri_param_sep' => '?',
		'trailing_slurp' => 0
	},
	'Host' => 'webscantest.com',
	'User-Agent' => 'FireFox',
	'Connection' => 'Keep-Alive'
};
D:Mon Sep  2 08:54:59 2019 'Result Hash' = {
	'whisker' => {
		'MAGIC' => 31340,
		'uri' => '/',
		'error' => 'opening stream: can\'t connect (connect error): -536870212'
	}
};
D:Mon Sep  2 08:54:59 2019 'Request Hash' = {
	'User-Agent' => 'FireFox',
	'Connection' => 'Keep-Alive',
	'whisker' => {
		'ssl_certfile' => undef,
		'lowercase_incoming_headers' => 1,
		'invalid_protocol_return_value' => 1,
		'force_close' => 0,
		'uri' => '/',
		'retry' => 0,
		'require_newline_after_headers' => 0,
		'max_size' => 0,
		'http_space1' => ' ',
		'force_bodysnatch' => 0,
		'force_open' => 0,
		'port' => 80,
		'include_host_in_uri' => 0,
		'protocol' => 'HTTP',
		'uri_postfix' => '',
		'host' => 'webscantest.com',
		'http_eol' => "\r\n",
		'keep-alive' => 1,
		'version' => '1.1',
		'uri_param_sep' => '?',
		'trailing_slurp' => 0,
		'ssl_save_info' => 1,
		'normalize_incoming_headers' => 1,
		'ignore_duplicate_headers' => 1,
		'method' => 'GET',
		'uri_prefix' => '',
		'timeout' => 10,
		'ssl_rsacertfile' => undef,
		'MAGIC' => 31339,
		'http_space2' => ' ',
		'ssl' => 1
	},
	'Host' => 'webscantest.com'
};
D:Mon Sep  2 08:54:59 2019 'Result Hash' = {
	'whisker' => {
		'uri' => '/',
		'MAGIC' => 31340,
		'error' => 'opening stream: can\'t connect (connect failed): -536870212'
	}
};
+ No web server found on webscantest.com:80
---------------------------------------------------------------------------
+ 0 host(s) tested
D:Mon Sep  2 08:54:59 2019 T:Mon Sep  2 08:54:59 2019: Ending

**Comment by sullo** [comment]
wfm. my best guess is that installing Nikto however brew does it is messing with operations. Suggest you clone this repo to a new location and try again.

**Comment by aether0011** [comment]
ok will do, will try it out.

**Comment by aether0011** [comment]
all good now. cloned your repo and symlink nikto.pl.
