### ISSUE TITLE
Feature Request: Use Session Cookie from first Request

### ISSUE THREAD

**Issue by cost6** [sullo/nikto#628]
Certain WAFs or webserver have an upper limit for sessions per IP. If multiple request without a session are sent, a new session is generated for each request. This leads to an exhaustion of sessions and the IP is "blocked" till the session pool is cleaned up.

This problem can be solved if the session generated for the first request is used in all subsequent requests.

A flag for for this would be very much appreciated.

**Comment by sullo** [comment]
You can use `-useproxy` to take cookies from responses and add them to the subsequent requests.
