### ISSUE TITLE
If a site returns multiple powered by headers you show ARRAY

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#629]
The site I've just scanned returns two `X-Powered-By` headers:

```
X-Powered-By: PHP/5.6.40
X-Powered-By: ASP.NET
```

When you report on this, the print function assumes a string rather than an array and so prints the string representation of the array:

```
+ Retrieved x-powered-by header: ARRAY(0x562aa46eec08)
```

**Comment by iasdeoupxe** [comment]
Looks similar to https://github.com/sullo/nikto/issues/394, https://github.com/sullo/nikto/issues/481 and https://github.com/sullo/nikto/issues/471

**Comment by digininja** [comment]
I definitely like the look of #471 :)

**Comment by payforonlineclass** [comment]
amazing post looking forward to see more from you - [online class help](https://www.payforonlineclasses.com/)
