### ISSUE TITLE
deprecated brace in regexp

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#634]
Just spotted this in the middle of some scan results:

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  'cookie.link.url' | translate }}/ at nikto/program/plugins/nikto_core.plugin line 3247.
```

Sorry, no more info but could probably retry the scan later if you need me to.

**Comment by sullo** [comment]
Seems like something has changed in perl regex matching. 

There were only 3 tests that could have failed this validation, and they are now fixed. So I think this should solve the issue.

**Comment by sullo** [comment]
Note, it didn't trigger on my laptop so likely perl version dependent.
