### ISSUE TITLE
Incorrect SSL info in scan

### ISSUE THREAD

**Issue by archergod** [sullo/nikto#638]
I run `nikto -h https://www.example.com` it shows SSL info for some other site on server [which is apparently the first Virtual host on server]. But it is not showing the SSL info of URL I shared. We are using Let's encrypt SSL for all sites. If I change order in my Virtual Host file and make scan site as first it shows correct. But why Nikto is scanning SSL separately probably based on IP address. Is there any option we can mark for shared hosting?

**Comment by digininja** [comment]
Are you using a single certificate with multiple names in the SAN?

I've just tested it against my box which has that, and Nikto shows the CN
for the certificate which is my primary site but not the SAN list which
includes the second site I scanned.

If this isn't the issue, I'm still going to put in a feature request, show
the SAN values as well as the CN in the SSL Info section.

**Comment by archergod** [comment]
No, we create Virtual Host in Apache, and then when we run `Certbot` it ask to choose site and whenever we put new site we get new SSL, which has different dates for that Domain (or it's alias) so each virtual host get its own certificate.

**Comment by drwetter** [comment]
Reminds me on #573

**Comment by digininja** [comment]
I've not got a box with multiple certs on to test against, but I've just
watched some traffic, and all the TLS client hello messages contain the
correct SNI field so it looks like it is requesting the correct certificate
based on the host name.

This is going way overboard in debugging, but if you fancy having a look in
Wireshark to see what is going on, this is a Client Hello message which
should have the SNI field correctly set to the hostname you are requesting.


[image: image.png]

And then this is the cert that is returned. In my case, the CN isn't what
was requested as the host is in a SAN.


[image: image.png]


Check these out to see if the right certificate is requested and then
returned.

**Comment by archergod** [comment]
@digininja your images didn't come through. I am no expert and didn't exactly know how to run Wireshark. I am running WSL Kali with nikto form my win 10 machine to scan site. We have to provide security report to our customer and hence we are scanning site on live server. I cannot share server details to let anyone scan it. The CN We are getting in nikto output is for different domain, [first in list]

**Comment by archergod** [comment]
I just see `-vhost` option probably this is design for issues like mine, but apparently it is not working for my case.

**Comment by digininja** [comment]
Here are the images.

![image](https://user-images.githubusercontent.com/117081/69326499-cb37df00-0c43-11ea-9688-804d54070492.png)


![image](https://user-images.githubusercontent.com/117081/69326509-d0952980-0c43-11ea-8574-5017662087e9.png)

Fire up Wireshark, get it sniffing on the main network interface

Filter it to just show the IP that you are scanning with a filter of 

```
ip.addr == 1.2.3.4
```

Start the scan and then stop it as soon as the SSL info is shown.

Scroll up to the top of the capture and look for a Client Hello message.

Expand that out and you should see something like the first screenshot.

Look down a few packets and you should then see a Certificate packet. Expand that out and you'll see the second screenshot.

The two packets marked in black in this screenshot are the two you want to look for.

![image](https://user-images.githubusercontent.com/117081/69326714-2d90df80-0c44-11ea-871f-0f856078277b.png)

**Comment by archergod** [comment]
Okay, I got wireshark running and capture for `Client Hello` and it doesn't have "extension: server_name" line in there for `Client Hello`. I am using default Kali Linux's Nikto 2.1.6 as stated there. if that make difference.

**Comment by digininja** [comment]
That will be the problem then. Without an SNI field, the web server doesn't know which site the connection is for so will return the default vhost.

Make sure the Kali box is fully up to date and pull the latest Nikto from Github and try that.

My guess is an old version of OpenSSL, or some other library which doesn't support SNI, is being used somewhere.

**Comment by tautology0** [comment]
I put in a couple of SNI patches to libwhisker about a year ago. Bearing in mind how poor Kali's patching is, I strongly suspect that they haven't been rolled upstream.

I seriously don't recommend using Kali's packaged tools.

**Comment by archergod** [comment]
Thanks for information, the problem is understood and I need to prepare other machine to test it out, so it might be a while for me to test. Thanks for information.

**Comment by digininja** [comment]
Just try with the latest version from here, the changes @tautology0 put in place may be the ones you need.

**Comment by archergod** [comment]
First, I was able to run with correct SSL info been displayed. 

Now, few things I notice (probably other thread should be created but anyways:)
1. I try to install using Docker instruction on my windows machine that has docker install, I get powershell to download git and build using docker command, but then `docker run --rm sullo/nikto` gives error that `' : no such file or directory` just that.

2. I try to use "release" package but it doesn't work for some Plugin error

3. I use the GIT clone on ubuntu then and have to install Perl SSL and then it works just fine. but on kali machine it still give same old certificate and I am not sure how to change Open SSL anyother lib there, but at least I have one workable solution. 

Thanks for @digininja for your encouragement and clear guidance.

**Comment by digininja** [comment]
Glad you got it working.

**Comment by sullo** [comment]
I’m not sure why it would do that by default—I’ll have to look. In the meantime try -Vhost to see of that helps to work as expected.

**Comment by sullo** [comment]
Or ignore me since I’m late to this party.

**Comment by archergod** [comment]
@sullo I already tried vhost option and it doesn't work, and your reply on close thread does means a lot as you been the author. I can now trust more on Nikto :).
