### ISSUE TITLE
x-mag header

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#641]
This header is set by NetIQ and is only supposed to be enabled for debugging.

```
+ Uncommon header 'x-mag' found, with contents: C11109C7B11D11111;13f9c111;4111118;FPE->0;, C11119C7B33D1111;13f9c111;4127387;usrLkup->0;usrBase->0;getPRBefFind->0;getPRBefFind->0;PRAfterFind->0;MyESPService;publicURL->0;MyEspService;default;SH;FF1End->0;FP2->0;WS=10448ed2;default;FP4->15;
```

I don't know what the individual fields mean, but it shouldn't be enabled in production systems so would be good to alert on.

https://www.netiq.com/documentation/netiqaccessmanager32/accessgatewayhelp/data/agsglobaladv.html

**Comment by digininja** [comment]
Looks like I'm not the only one writing code on new years eve.

Happy New Year!

**Comment by sullo** [comment]
Cheers!
