### ISSUE TITLE
Metasploit Format 

### ISSUE THREAD

**Issue by fluo75** [sullo/nikto#642]
Hi,
Thanks for your great work.

A quick question, i can't find the format "msf+", is it still available?

Thanks,

David

**Comment by sullo** [comment]
No that was deprecated a while ago when there were msf changes and there didn’t seem to be much demand for it. Best bet would be to use xml and convert to what you need. Or maybe sql. 

>

**Comment by fluo75** [comment]
Thank you very much for your help.
I can't find the SQL schema, where could I find it please?

Thanks again and have nice time for the next few days.

David

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by sullo** [comment]
If I recall (not at a computer) it’s in the head of the output file or you can find it in the templates directory.

**Comment by fluo75** [comment]
Thanks again Sullo but is still can't find it.... 
Neither in the head of output file or in the template directory.
It must have passed it 3000 times but I still can't find it :)

**Comment by digininja** [comment]
You could try this from the project root if the file contains the actual
SQL to create the tables.

```
find . -type f - exec grep -ih "create table" '{}' \;
```

**Comment by fluo75** [comment]
Thank you to both of you?
The previous command returned me 2 files: 
-  documentation/sections/options.xml
- program/plugins/nikto_report_sqlg.plugin

From these files, the command the SQL schema for the table is:
`create table nikto_table (testid varchar(6) not null, ip varchar(15), hostname text, port int(5), usessl tinyint(1), osvdb int, httpmethod text, uri text, message text, request blob, response blob);`

I will try to make a small python script to call metasploit with the result of Nikto. 

Thanks again ;)

**Comment by sullo** [comment]
I added a doc/nikto_schema.sql file in 0330d62862a99ff6a6908ceecc6868eee5589fd3 to make it easier for people to find.

**Comment by fluo75** [comment]
Thank you very much.

Do you have any recommendations for automating nikto and metasploit? In which version did you take the option away? I would quite like to see it running. :)
I will try building a simple script to link the two together next week.

Thanks again!

Have a great new year's eve.



Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
De : sullo <notifications@github.com>
Envoyé : mardi 31 décembre 2019 à 22:11
À : sullo/nikto
Cc : David; State change
Objet : Re: [sullo/nikto] Metasploit Format (#642)


I added a doc/nikto_schema.sql file in 0330d62<https://github.com/sullo/nikto/commit/0330d62862a99ff6a6908ceecc6868eee5589fd3> to make it easier for people to find.
