### ISSUE TITLE
Nikto location?

### ISSUE THREAD

**Issue by SnXe** [sullo/nikto#643]
I'm new to docker and haven't had much time to figure everything out so I'm wondering why nikto is stored in home dir and why I can run it w/o using container. I thought it was stored elsewhere, and would only be able to run within a container.

**Comment by fluo75** [comment]
If I am not mistaken, if you have cloned the repository, you can run in from the nikto/program directory.
`perl nikto.pl`

**Comment by NicolasCARPi** [comment]
This can be closed.
