### ISSUE TITLE
Drupal headers

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#650]
Any way we could get these recognised so you can say Drupal is installed? Maybe pull the version as well if that is written in a consistent way.

```
+ Uncommon header 'x-generator' found, with contents: Drupal 7 (https://www.drupal.org)
+ Uncommon header 'x-drupal-cache' found, with contents: HIT
```

**Comment by sullo** [comment]
Related: #7

**Comment by sullo** [comment]
Added to 2.5.0 branch
