### ISSUE TITLE
False positive on Mailman

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#652]
Got a false positive on this finding:

```
OSVDB-3233: /mailman/listinfo: Mailman was found on the server.
```

The page returns a 404. Mailman is mentioned a couple of times in the response, but only as part of URLs built from the page URL.

**Comment by sullo** [comment]
I'm sure you don't have access longer, but it is possible "mailing list" was in the 404 body? That's the only way this *should* trigger.

**Comment by digininja** [comment]
I know which client it was but have deleted the scan files unfortunately. They usually have a yearly scan so may come back round to this next February!

**Comment by iasdeoupxe** [comment]
@sullo A suggestion from my side to get such info directly in the initial report without requiring to ask for it at some point in time later: https://github.com/sullo/nikto/pull/680
