### ISSUE TITLE
Duplicate file hits

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#653]
This was scanning a Drupal 7 box, there are duplicate hits for all these, is something running twice that shouldn't?

```
+ Entry '/INSTALL.mysql.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/INSTALL.pgsql.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/INSTALL.sqlite.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/install.php' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/LICENSE.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/MAINTAINERS.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/UPGRADE.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/xmlrpc.php' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/INSTALL.mysql.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/INSTALL.pgsql.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/INSTALL.sqlite.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/install.php' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/LICENSE.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/MAINTAINERS.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/UPGRADE.txt' in robots.txt returned a non-forbidden or redirect HTTP code (200)
+ Entry '/xmlrpc.php' in robots.txt returned a non-forbidden or redirect HTTP code (200)
```

**Comment by tautology0** [comment]
You got some debug stuff (e.g. a "-D v -Plugins robots" would do)? All I can think is that maybe it's running on both http and https for some reason.

**Comment by digininja** [comment]
I've got the save file, would that help?

If not, I could run it again with those parameters.

**Comment by tautology0** [comment]
Yeah that would; are the entries for each finding the same in the save file?

**Comment by digininja** [comment]
I should have thought of this before, the entries are duplicated in the robots.txt file, that is why you've reported on them twice. Once for the user agent Googlebot, once for the generic `*`.

So, changing the issue slightly, should you de-duplicate the robots.txt file before requesting its contents.

**Comment by tautology0** [comment]
Ah, that makes sense; I hadn't planned to badly written robots.txt files when I did the plug in!

**Comment by digininja** [comment]
Technically it isn't badly written, you can have sections for as many
different bot user agents as you want so could repeat the same entries lots
of different times.
