### ISSUE TITLE
make better Dockerfile

### ISSUE THREAD

**Issue by port22** [sullo/nikto#656]
I wonder why the provided Dockerfile is that unnecessarily complicated. 
Since it's perl app, why don't use the official perl image? It also already contains the preferred package manager cpanm, rather than installing possibly outdated ssleay from alpine repos.

```
FROM perl:5
ENV  PATH=${PATH}:/nikto
COPY ["program/", "/nikto"]
RUN cpanm --force -n Net::SSLeay
ENTRYPOINT ["nikto.pl"]
```

btw I also don't see any disadvantages in just using root since it's run as a capsuled binary under control.

**Comment by sullo** [comment]
I am not a docker user so I can't really comment much on how it works or what is a better way. @drwetter @felipenazario ?

Generally speaking, principle of least privilege should always apply.

**Comment by drwetter** [comment]
I don't know the perl image. There somebody either needs to speak up or investigate how it's like.

Second point as @sullo indicated, your @port22 ) suggestion doesn't contain a nikto user+group.

**Comment by felipenazario** [comment]
Supposing we adopt this image perl:5, it has 319.35 MB (Debian Linux with Perl), if we change to the correspond minimal version perl:5.30.1-slim-buster, it comes with 125 MB (Debian Linux Minimal with Perl).

Today alpine image with Perl comes with 42.3 MB and the final image has 47.3 MB, this corresponds to 14.81% of the perl:5 image. Even the proposed solution contains less instruction to the build phase, the final size implies more disk space and download time to the final user. I believe that doesn't worth the trade-off.

**Comment by drwetter** [comment]
> I believe that doesn't worth the trade-off.

agree

**Comment by drwetter** [comment]
this should be closed
