### ISSUE TITLE
Nikto Vulnerability Scan Returning Disallowed HTTP Methods

### ISSUE THREAD

**Issue by oyekanmiayo** [sullo/nikto#659]
Hi @sullo, 

I'm using Nikto to scan a Spring application and it is returning HTTP methods I have specifically disallowed. 

<img width="773" alt="Screen Shot 2020-03-11 at 12 14 47 PM" src="https://user-images.githubusercontent.com/26260543/76411477-2d9f2180-6392-11ea-90f2-0eadb9dfc3b4.png">

It is my understanding that ```nikto -h <hostname>``` makes an OPTIONS request to the application (reference: http://attrition.org/pipermail/nikto-discuss/2011-December/000428.html)

Using curl to scan instead to make the OPTIONS request, I don't see these allowed methods. This is the response:
<img width="625" alt="Screen Shot 2020-03-11 at 12 18 47 PM" src="https://user-images.githubusercontent.com/26260543/76411684-971f3000-6392-11ea-8272-542b49d3d4bd.png">

Please help, what is the fix for nikto to stop showing disallowed methods? it's super important for a deployment. 

Thank you.

**Comment by digininja** [comment]
Curl is getting a redirect but Nikto doesn't seem to see seeing that.

Run with -Save and look at the request that is being made to retrieve the
methods result. You can then try replaying that with either netcat or
something like Burp.

**Comment by oyekanmiayo** [comment]
Hi @digininja,

Thanks for your response. 

Turns out that Nikto is, in fact, seeing the redirect as seen in the response in the picture below:

<img width="1440" alt="Screen Shot 2020-03-11 at 2 07 27 PM" src="https://user-images.githubusercontent.com/26260543/76421018-54198880-63a3-11ea-828f-d2c95b98bc7a.png">

<img width="1440" alt="Screen Shot 2020-03-11 at 2 07 30 PM" src="https://user-images.githubusercontent.com/26260543/76420757-e8372000-63a2-11ea-919c-e1ae79c72cc1.png">

But I'm wondering where the ```Allowed HTTP Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS ``` is coming from. It doesn't look like it's in the response body and **that's my main problem**.

Also, please could you give a bit more detail about how I could use Burp or Netcat for this, never used either. (Looks like Burp isn't a free tool)

**Comment by digininja** [comment]
From that output, it does look like there might be a bug but I'll defer to @sullo on that.

I've just tested it on one of my sites which does a redirect from the root and doesn't return any methods and it didn't report anything so it isn't a general bug affecting everything.

There is a free version of Burp, but if you don't know how to use it, it is probably too much for this.

For netcat, just copy the request, with the blank lines at the end, into a file, then do something like:

```
nc my_request | nc localhost 9000
```

That will manually make the request and you'll see the reply. It should match the one Nikto is showing, but might not.

**Comment by tautology0** [comment]
Is it possible to see the output of a
```
nikto.pl -host blah -Plugins httpoptions -D d
```

**Comment by sullo** [comment]
Closing due to lack of response.
