### ISSUE TITLE
Double <niktoscan> tag in xml output

### ISSUE THREAD

**Issue by microidz** [sullo/nikto#670]
Hi guys,

It seems like the XML output file structure changed since earlier version which now includes a "second set" of <niktoscan> tags:

```
<niktoscan> 
<!DOCTYPE niktoscan SYSTEM "/var/lib/nikto/docs/nikto.dtd">
<niktoscan hoststest="0" options="-h http://scanme.webscantest.com/ -o scanme_nikto -Format xml" version="2.1.6" scanstart="Thu Apr 16 16:14:47 2020" scanend="Wed Dec 31 19:00:00 1969" scanelapsed=" seconds" nxmlversion="1.2">
...  
</niktoscan> 
</niktoscan>
```

In the past, the file structure was like this: https://github.com/dradis/dradis-nikto/blob/master/spec/fixtures/files/localhost.xml

So as this requires to manually modify the xml output before it can be ingested by Dradis, I would like to know if this "double tags format" will be the one used from now on. If that's the case, I'll put in a request to the Dradis folks so they can modify the parser.

Thanks!

**Comment by tautology0** [comment]
The top level tag seems to be in error - it definitely shouldn't be before the DOCTYPE.

**Comment by tautology0** [comment]
Just tried this with trunk and I can't reproduce the problem - which version are you using?

**Comment by microidz** [comment]
Hi, here's the Nikto command I'm using to perform the scan: nikto -h http://scanme.webscantest.com/ -o scanme_nikto -Format xml

I'm running nikto version 2.1.6

I've also joined the output file from Nikto.

**Comment by tautology0** [comment]
This is a wee bit more complex to fix than it should be - looks like our DTD is a tad out of date as well.

**Comment by rachkor** [comment]
> The top level tag seems to be in error - it definitely shouldn't be before the DOCTYPE.
@tautology0 I'm with the Dradis support team. Based on this response, my current plan is to not update our Nikto upload plugin and to wait for a Nikto update to remove the second set of `niktoscan` tags. Does that make sense with your plans?

**Comment by sullo** [comment]
The updated XML format is only slightly different than before. TLDR; The outermost `<niktoscan>` elements have been updated as `<niktoscans>`.  This required the order of report opening to change. 

The new schema is, essentially:
```
  <niktoscans>			# Wrapper for this invocation of Nikto
    <niktoscan>			# Scan of one host (ip+name+port+protocol); multiple allowed
      <scandetails>		# Details of the scan
      <item></item>		# Scan item (finding); mulitple allowed
      </scandetails>		# Closing Details of the scan
    </niktoscan>		# Closing Scan of one host 
  </niktoscans>			# Closing the Wrapper for this invocation of Nikto
```

Also tagging #467 for closure
