### ISSUE TITLE
strange positives, again

### ISSUE THREAD

**Issue by francoisstark333** [sullo/nikto#674]
Very similar issue to this: https://github.com/sullo/nikto/issues/340

I am testing an apache server running in AWS ELB. It is returning these headers:
server: Apache
status: 200
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block

But this is the result from Nikto:
- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          xxx.xxx.xxx.xxx
+ Target Hostname:    xxx.xxx.com
+ Target Port:        443
---------------------------------------------------------------------------
+ SSL Info:        Subject:  /CN=*.xxx.com
                   Ciphers:  ECDHE-RSA-AES128-GCM-SHA256
                   Issuer:   /C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
+ Start Time:         2020-05-19 00:00:05 (GMT2)
---------------------------------------------------------------------------
+ Server: awselb/2.0
+ The anti-clickjacking X-Frame-Options header is not present.
+ The X-XSS-Protection header is not defined. This header can hint to the user agent to protect against some forms of XSS
+ The site uses SSL and the Strict-Transport-Security HTTP header is not defined.
+ The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type
+ All CGI directories 'found', use '-C none' to test none
+ Server is using a wildcard certificate: *.xxx.com
+ 26152 requests: 0 error(s) and 5 item(s) reported on remote host
+ End Time:           2020-05-19 05:24:33 (GMT2) (19468 seconds)

So I can deduce the following:
- Nikto is using ssl and getting the ssl certificate
- It is not seeing any of the headers returned from the site

**Comment by iasdeoupxe** [comment]
> It is not seeing any of the headers returned from the site

As the responses are showing it looks that the server is answering differently (`server: Apache` vs. `Server: awselb/2.0`) to the requests done by Nikto (maybe a different vhost / hostname or similar?).

**Comment by tautology0** [comment]
Nikto will highlight the missing header if it sees a request without the header. As @iasdeoupxe states; it is likely one of the tests will go to a different back server.

Doing a -Save outdir will show you exactly what is being requested for this finding.

**Comment by francoisstark333** [comment]
Thanks for clearing that up.

The awselb is not a server, it is the AWS Application Loadbalancer and only passes requests through to the Apache worker instances.  

The AWS Loadbalancer does decrypt the SSH and adds its own cookies to the responses from our worker instances.

The AWS Loadbalancer also includes a WAF firewall, and thus rejects many of the nikto requests as malicious without forwarding it to our php back ends. This would explain why some responses are marked as coming from awselb, and these requests would not include all the headers as reported by Nikto.

However, none of the 2xx or 3xx responses would be missing the headers reported.  Only 4xx responses would miss those headers.

So is this a security vulnerability?  Should Nikto be mentioning it? Should Nokto be splitting the reporting between 2xx, 3xx, 4xx and 5xx responses?  It is hackable?

**Comment by sullo** [comment]
Sorry I never really read this thread. 

This could potentially be a problem in a situation where the ALB sets, unsets, or changes a header that the backend has created. I can't think of a case where this would be a serious security risk off the top of my head, but based on your headers above something like this could happen:

- Backend sets this on a request to / : `strict-transport-security: max-age=31536000`
- ALB sets this on any 404: `strict-transport-security: max-age=5000`

Contrived example, but it might be possible to have an issue like that. I don't think that's likely in most scenarios, and I doubt it's useful in any that exist.
