### ISSUE TITLE
False positive HTTP header 

### ISSUE THREAD

**Issue by drwetter** [sullo/nikto#677]
cmd:

``./nikto.pl   -useragent 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0' -host https://<REDACTED>  x469 -Display E4 -output <whatever>.html``

```
--------------------------------------------------------------------------
+ Server: Apache
+ Expect-CT is not enforced, upon receiving an invalid Certificate Transparency Log, the connection will not be dropped.
[..]
```

wget:

```
prompt> wget  --no-check-certificate --no-proxy -S -O /dev/null https://<REDACTED>
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Fri, 29 May 2020 17:49:29 GMT
  Server: Apache
  Content-Language: de
  Cache-Control: private, no-store
  Content-Security-Policy: frame-ancestors 'self'; upgrade-insecure-requests
  Expect-CT: max-age=86400, enforce
  X-Content-Type-Options: nosniff
  Referrer-Policy: same-origin
  Strict-Transport-Security: max-age=15768000
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: SAMEORIGIN
  Vary: User-Agent
  Upgrade: h2
  Connection: keep-alive, Keep-Alive
  Accept-Ranges: bytes
  X-UA-Compatible: IE=edge
  Keep-Alive: timeout=15, max=256
  Transfer-Encoding: chunked
  Content-Type: text/html; charset=utf-8
prompt> git log | head -1 
commit 46df35c7a4ca8569e750b309f04a557a48812502
prompt> 
```

Apache Config (for **any** vhost):

``Header always set Expect-CT "max-age=86400, enforce"``

Probably see also  #674

**Comment by drwetter** [comment]
https://httpwg.org/http-extensions/expect-ct.html

**Comment by iasdeoupxe** [comment]
Probably just the `^` in `unless($result->{'expect-ct'} =~ /^enforce/) {`:

https://github.com/sullo/nikto/blob/2a146a1f19ff752d2776396802c6b4e80a824545/program/plugins/nikto_headers.plugin#L228

**Comment by tautology0** [comment]
@iasdeoupxe: good find - that's most likely it - I'll get this patch when I've got my other laptop booted up so I can test it (will likely be tomorrow).

**Comment by drwetter** [comment]
> up so I can test it 

Can confirm @iasdeoupxe suggestion works for me to get rid off the fp. To get this off the table I can do a PR but I think it's better if the person who found the fix gets the attribution -->  @iasdeoupxe  :-)

**Comment by iasdeoupxe** [comment]
TDB: In general i don't care about any attribution or mention :-)

Feel free to create a PR if you like, would be faster because currently i can't do any additional tests / verification of the change.

**Comment by sullo** [comment]
Fixed, no PR needed. Thanks for reporting and tracking it down!
