### ISSUE TITLE
OPTIONS showing as a finding?

### ISSUE THREAD

**Issue by jhedlund** [sullo/nikto#679]
New user to nikto here, I'm wanting to setup some automated monitoring using nikto and I've gotten rid of all the issues it shows except this one:

URI  /
HTTP Method OPTIONS
Description Allowed HTTP Methods: HEAD, GET, POST, OPTIONS

Is this an informational message that shows up as a finding, maybe as a warning in case someone doesn't want OPTIONS as an allowed method?

I could look to create a PR to add an option to skip this vulnerability for the httpoptions plugin, unless that's not something that would be desirable to be added.  I have another way around it, but figured it might make sense to have that option.

**Comment by sullo** [comment]
Sorry I never replied to this. This is an informational message for testers. We don't know what methods are good or should be allowed for a host, so we just report what OPTIONS * and OPTIONS / return and a human can decide if they need to take action.
