### ISSUE TITLE
nikto update problems

### ISSUE THREAD

**Issue by 0plan** [sullo/nikto#681]
hi,

at first i installed nikto from the debian 10 repo.
it seems that the function:

nikto -update

doesn't works. the same problem is with nikto from git.

this is the output:

root@XXXXX:/home/XXXXX/nikto/program# ./nikto.pl -update
-update is deprecated in git versions of Nikto; please pull directly from git.
+ ERROR (404): Unable to get cirt.net/nikto/UPDATES/2.1.6/versions.txt

is it a bug?

cheers

**Comment by digininja** [comment]
As the message says:

```
-update is deprecated in git versions of Nikto; please pull directly from git.
```

In other words, don't use update, pull from git to get the latest version.

**Comment by 0plan** [comment]
okay. it is a little bit confusing with this sentence in the usage and manpage:

usage:
**       -update             Update databases and plugins from CIRT.net

manpage:
       -update
           Update the plugins and databases directly from cirt.net.


without the notice "deprecated"

cheers

**Comment by digininja** [comment]
man pages and documentation are rarely up to date, always believe the code.

**Comment by jamesdeluk** [comment]
How does this relate to nikto installed through apt-get?

**Comment by digininja** [comment]
I think the general recommendation is not to install through any package
management system, just use the latest repo code. Repo versions are always
behind the current version.

**Comment by tautology0** [comment]
The ones that we've seen munged into an apt package (especially the ones on Kali) seem to have been buggered about with so much that we can't really support them.
