### ISSUE TITLE
Bug: Shellshock requests not getting sent out

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#686]
### Expected behavior
Shellshock requests to be sent out correctly

### Actual behavior
I'm watching traffic in Burp, I see a request to `../../../../../../../../../../../../etc/shadow` sent out, and then nothing. Nikto finally gives up with an error limit reached message.

Running Nikto in debug mode, the requests it is failing on are all shellshock based, it claims to be sending them out and shows the request with all the data but then gives this as the response:

```
D:Thu Jul 16 04:13:30 2020 'Result Hash' = {
	'whisker' => {
		'MAGIC' => 31340,
		'lowercase_incoming_headers' => 1,
		'http_data_sent' => 1,
		'error' => 'error reading HTTP response',
		'data' => '',
		'uri' => '/cgi-bin/count.cgi'
	}
};
```

I don't see any of these requests in Burp so I'm guessing that it isn't actually sending them for some reason.

I've tried this from two different boxes, one direct to the site, one through Burp.

The site is HTTP only, no HTTPS.

### Steps to reproduce

1. Run this
```
./nikto.pl -host http://client.net/ -useragent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0" --Save client_save -output client.txt
```

2. Wait a while then get this error:

```
+ ERROR: Error limit (20) reached for host, giving up. Last error: error reading HTTP response
```

3.

### Nikto version

Both boxes just pulled from GitHub.

```
./nikto.pl -Version
---------------------------------------------------------------------------
Nikto Versions
---------------------------------------------------------------------------
File                               Version      Last Mod
-----------------------------      --------     ----------
Nikto main                         2.1.6
LibWhisker                         2.5
db_404_strings                     2.003        
db_content_search                  2.000        
db_dictionary                      1.0          
db_dir_traversal                   2.1.6        
db_domino                          2.1.6        
db_drupal                          1.00         
db_embedded                        2.004        
db_favicon                         2.010        
db_headers                         2.008        
db_httpoptions                     2.002        
db_multiple_index                  2.005        
db_outdated                        2.017        
db_parked_strings                  2.001        
db_realms                          2.002        
db_server_msgs                     2.006        
db_tests                           2.021        
db_variables                       2.004        
nikto_apache_expect_xss.plugin     2.04         
nikto_apacheusers.plugin           2.06         
nikto_auth.plugin                  2.04         
nikto_cgi.plugin                   2.06         
nikto_clientaccesspolicy.plugin    1.00         
nikto_content_search.plugin        2.05         
nikto_cookies.plugin               2.05         
nikto_core.plugin                  2.1.5        
nikto_dictionary_attack.plugin     2.04         
nikto_dir_traversal.plugin         2.1.6        
nikto_dishwasher.plugin            2.20         
nikto_docker_registry.plugin       2.20         
nikto_domino.plugin                2.1.6        
nikto_drupal.plugin                1.00         
nikto_embedded.plugin              2.07         
nikto_favicon.plugin               2.09         
nikto_fileops.plugin               1.00         
nikto_headers.plugin               2.11         
nikto_httpoptions.plugin           2.10         
nikto_ms10_070.plugin              1.00         
nikto_msgs.plugin                  2.07         
nikto_multiple_index.plugin        2.03         
nikto_negotiate.plugin             2.00         
nikto_origin_reflection.plugin     2.01         
nikto_outdated.plugin              2.09         
nikto_parked.plugin                2.00         
nikto_paths.plugin                 2.00         
nikto_put_del_test.plugin          2.04         
nikto_report_csv.plugin            2.07         
nikto_report_html.plugin           2.06         
nikto_report_json.plugin           2.00         
nikto_report_nbe.plugin            2.02         
nikto_report_sqlg.plugin           2.00         
nikto_report_text.plugin           2.05         
nikto_report_xml.plugin            2.06         
nikto_robots.plugin                2.06         
nikto_shellshock.plugin            2.01         
nikto_siebel.plugin                1.00         
nikto_sitefiles.plugin             2.00         
nikto_ssl.plugin                   2.01         
nikto_strutshock.plugin            2.01         
nikto_tests.plugin                 2.04         
```

Run:

```
./nikto.pl -Version
```

and paste the output here.

### Further technical info

Will add the debug file when it finishes running.

It has been running fine against other sites I'm scanning this week. I've just ran it against my site on HTTP and HTTPS and it completed fine so I've not broken the install.

Nothing special about the site, its a 5 page brochure site. No protections running on it. It doesn't fall over and is still accessible from the scanner host while the scanner is failing.

I've seen it bail with this error before but never dug into it, so this may have happened in the past and I've just ignored it.

**Comment by digininja** [comment]
I've stripped the requests up to where it starts failing. You see the directory traversal for shadow, the no more requests make it to Burp

[nikto_shellshock_debug.txt](https://github.com/sullo/nikto/files/4929512/nikto_shellshock_debug.txt)

**Comment by digininja** [comment]
Stand down, my mistake, Burp Flow extension doesn't show request that don't get a reply and the proxy was hiding them. I've found the missing requests.

**Comment by sullo** [comment]
Any idea why they were dropped? I ask because if there's some identifier somewhere on the site/app we can use to ignore those non-responses on the counter it might be good to look at it.

**Comment by digininja** [comment]
Don't know off hand. As it's http I'll have a go at sniffing traffic and
see what comes back.

**Comment by sullo** [comment]
Maybe a WAF. Nbd was just curious.

**Comment by digininja** [comment]
Two Wireshark dumps of me replaying one of the requests from Burp. This one is going direct to the server. The server just completely stops responding after the GET.

![image](https://user-images.githubusercontent.com/117081/87738493-7863f680-c7d5-11ea-80ff-b206b7783031.png)

This is through Squid, the connection is gracefully handled but still no HTTP response from the server.

![image](https://user-images.githubusercontent.com/117081/87738505-7dc14100-c7d5-11ea-804c-88852bc60847.png)

The server is Apache, the client think it is being patched, but the site hasn't been actively maintained for years and the business unit who own it have almost abandoned it, so I doubt it has any fancy WAF or protections as there aren't any on any other site I'm testing, including the client's main site which.

**Comment by drwetter** [comment]
Am 17. Juli 2020 03:40:00 MESZ schrieb Robin Wood <notifications@github.com>:
>Two Wireshark dumps of me replaying one of the requests from Burp. This
>one is going direct to the server. The server just completely stops
>responding after the GET.

But that sounds like you hit something.

It doesn't have to be fancy. Could be fail2ban. 





-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by digininja** [comment]
I can still see the site with normal requests so I'm not banned, it is just
ignoring those requests.

I don't know how mod_security would handle that type of request, it could
be that doing the work.
