### ISSUE TITLE
False Positive/Negative: wsman/server-status/server-info/siteserver admin

### ISSUE THREAD

**Issue by pixelicous** [sullo/nikto#689]
### Output of suspected false positive / negative

> /SiteServer/admin/: Site Server components admin. Default account may be 'LDAP_Anonymous', pass is 'LdapPassword_1'. see http://www.wiretrip.net/rfp/p/doc.asp/i1/d69.htm
> + /wsman/: Windows Remote Management is enabled
> + /server-status: Apache server-status interface found (protected/forbidden)
> + /server-info: Apache server-info interface found (protected/forbidden)

### Debug output

The response is 403 for all these paths.
However i am getting:

> Reason:   	Response Code Match

or

> Reason:   	Response Code Match - Match 1 (Or)

after saving the false_positive logs

I do not have apache installed, only nginx, none of these folders exist at the root web folder

**Comment by iasdeoupxe** [comment]
Looks like this is expected, the test for all three pages are only looking for 200 , 403 and / or 401 status codes:

```
"006709","0","b6","/wsman/","GET","200","403","","","","Windows Remote Management is enabled","",""
"007018","0","b","/server-status","GET","401","403","","200","","Apache server-status interface found (protected/forbidden)","",""
"007019","0","b","/server-info","GET","401","403","","200","","Apache server-info interface found (protected/forbidden)","",""
```

**Comment by iasdeoupxe** [comment]
Looks like the actual 403 was added in https://github.com/sullo/nikto/pull/277 with the rationale provided in https://github.com/sullo/nikto/pull/277#issuecomment-137301427

**Comment by pixelicous** [comment]
@iasdeoupxe forgot about this long ago as there was no response for quite some time.. Will check. Thanks
