### ISSUE TITLE
Feature Request: Sensitive Files

### ISSUE THREAD

**Issue by mubix** [sullo/nikto#690]
Via: https://twitter.com/bad_packets/status/1146635999167991808

If found, all of these are considered interesting files:
```
/.env
/.ftpconfig
/.remote-sync.json
/.vscode/ftp-sync.json
/.vscode/sftp.json
/deployment-config.json
/ftpsync.settings
/sftp-config.json
```
I know `.env` is already detected, but I wanted to preserve the integrity of the original poster's list.

**Comment by mubix** [comment]
Also, there is only two formats, bug and false positive report. Not sure what feature requests would go under

**Comment by sullo** [comment]
Added checks/templates in ffc7efe436d9816ec92e36b69506dd1be3242822
