### ISSUE TITLE
Strange behaviour when using nikto within a shell "while read"...

### ISSUE THREAD

**Issue by carmoflavio** [sullo/nikto#697]
Hi,

I have seen and struggled with this "behaviour" for years and never got time to confirm what was weird about it until now. It might be just some stupid thing on my part, but here it goes.

The short description is that whenever we try to use nikto within a "while read" output, somehow the nikto execution messes up the variable reading, as shown below:
I noticed the same behaviour with "dash" as well as "bash" and "sh".

**#### REPRODUCING THE ISSUE ####**
NOTE: CHECK THE SECOND ITERATION IP
```
$ nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP"; /tools/bin/nikto -host $IP -maxtime 2s -timeout 1; echo "### IP: $IP"; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.128:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.128

### IP: 92.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 92.168.0.129:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 92.168.0.129

### IP: 92.168.0.130
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 92.168.0.130:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 92.168.0.130

```
**###################################################################**

Note that after the second iteration onwards, the "IP" value read is missing the first character. I am pretty sure I have seen variations of this as well, missing the first two, or even the entire first octet.

This can be easily circumvented by using a for loop in the exact same way, and everything seems to work fine. 
I guessed that the issue was with the perl subprocess, but doing some tests with simple perl scripts I couldn't identify the issue.

**##### USING FOR LOOP - NO ISSUE HERE #########**
```
$ for IP in $(nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}'); do echo -e "\n### IP: $IP"; /tools/bin/nikto -host $IP -maxtime 2s -timeout 1; echo "### IP: $IP"; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.128:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.128

### IP: 192.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.129:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.129

### IP: 192.168.0.130
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.130:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.130

```
**##############################################################**

**Comment by sullo** [comment]
You appear to be running on Kali, which we do not support due to how the
program is distributed on the file system.

First step I would recommend is to clone the Nikto repo and try again:
https://github.com/sullo/nikto

Second, I'm not sure why you have -maxtime 2s and -timeout 1s there--I
would be concerned Nikto can't establish that the site is there before
timeout. For testing commands I'd recommend removing or increasing to
several seconds.

Lastly, Based on the output it looks like the IP error is somewhere between
nmap and the awk, because when it prints "### IP: 92.168.0.129" it has
already lost a character, and that is before nikto ever sees it.

Hope that helps.

**Comment by carmoflavio** [comment]
Thanks for your reply...

I am indeed running it on Kali, but the nikto version is cloned from the github.
The -maxtime and -timeout are just there to speed up the outputs, I can't see any difference in this behaviour if with our without any different options in nikto command line.


```
root@kali-WSL: /tools/nikto# git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
root@kali-WSL: /tools/nikto# nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP"; program/nikto.pl -host $IP -maxtime 2s -timeout 1; echo "##
# IP: $IP"; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.128:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.128

### IP: 92.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 92.168.0.129:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 92.168.0.129

```

**nmap** was just used to make it easier to reproduce, the issue happens either way, as shown below:


```
root@kali-WSL: /tools/nikto# nmap -n -sL 192.168.0.128/29 | awk '/report/{print $NF}' > ips
root@kali-WSL: /tools/nikto# cat ips
192.168.0.128
192.168.0.129
192.168.0.130
192.168.0.131
192.168.0.132
192.168.0.133
192.168.0.134
192.168.0.135
root@kali-WSL: /tools/nikto# git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
root@kali-WSL: /tools/nikto# cat ips | while read IP; do echo -e "\n### IP: $IP"; program/nikto.pl -host $IP -maxtime 2s -timeout 1; echo "### IP: $IP"; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 192.168.0.128:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 192.168.0.128

### IP: 92.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
+ [20b] No web server found on 92.168.0.129:80
---------------------------------------------------------------------------
+ 0 host(s) tested
### IP: 92.168.0.129

### IP: 92.168.0.130
- Nikto v2.1.6
---------------------------------------------------------------------------
^C### IP: 92.168.0.130

### IP: 92.168.0.131
- Nikto v2.1.6
---------------------------------------------------------------------------
^C### IP: 92.168.0.131

### IP: 92.168.0.132
^C
root@kali-WSL: /tools/nikto# ^C

```

**Comment by digininja** [comment]
I've managed to reproduce this but couldn't say what is causing it.

Running with Nikto in the list of things to run, the leading 1 is missed off the IP address that is echo'd out after the first itteration:

```
nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP" ; ~/tools/web/nikto/program/nikto.pl -host $IP    ; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
### IP: 92.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
### IP: 92.168.0.130
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
### IP: 92.168.0.131
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
```

But if I run it without calling Nikto the 1 isn't removed.

```
$ nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP"   ; done

### IP: 192.168.0.128

### IP: 192.168.0.129

### IP: 192.168.0.130

### IP: 192.168.0.131

### IP: 192.168.0.132
```

Echoing `$IP` before and after Nikto, it is truncated after as well as before, but not on the first itteration.

```
 nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP" ; ~/tools/web/nikto/program/nikto.pl -host $IP  ; echo -e "\nSecond call: $IP\n"    ; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
Second call: 192.168.0.128


### IP: 92.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
^C
Second call: 92.168.0.129
```

But again, without Nikto, `$IP` isn't affected.

```
nmap -n -sL 192.168.0.128/28 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP"  ; echo -e "\nSecond call: $IP\n"  ; done

### IP: 192.168.0.128

Second call: 192.168.0.128


### IP: 192.168.0.129

Second call: 192.168.0.129


### IP: 192.168.0.130

Second call: 192.168.0.130
```

No idea why, but I'm really curious!

**Comment by carmoflavio** [comment]
Yes, that is exactly the issue.

Note that the issue happens only if nikto successfully process the command line. 
For instance, if you call "nikto -h" or "nikto -foo" (which will cause an error), the issue doesn't happen either.

This might turn out to be some kind of bug (leftover character?) when handling stdout/stdin, missing a flush on input/output buffer manipulation whilst printing the tool output.

I'd guess there aren't many ways for the child process to affect the parent input reading.

**Comment by digininja** [comment]
In case anyone wants to play along, I've got close to what is causing the problem, currently looking around lines 2470 of /program/plugins/nikto_core.plugin . If I mess with the code around there, I can get it to strip the first two character off the IP!

```
nmap -n -sL 192.168.0.128/30 | awk '/report/{print $NF}' | while read IP; do echo -e "\n### IP: $IP" ; ~/tools/web/nikto/program/nikto.pl -host $IP  ; echo -e "\nSecond call: $IP\n"    ; done

### IP: 192.168.0.128
- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on 192.168.0.128:80
---------------------------------------------------------------------------
+ 0 host(s) tested

Second call: 192.168.0.128


### IP: 2.168.0.129
- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on 2.168.0.129:80
---------------------------------------------------------------------------
+ 0 host(s) tested

Second call: 2.168.0.129


### IP: 2.168.0.130
- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on 2.168.0.130:80
---------------------------------------------------------------------------
+ 0 host(s) tested

Second call: 2.168.0.130
```

**Comment by carmoflavio** [comment]
Just some additional background on the differences between "for" and "while read", that might help we understand the issue:

```

root@kali-WSL: /tools/nikto# for i in $(echo test; sleep 1; echo test2; sleep 1; echo test3; sleep 1); do date; done
Tue Sep 15 14:18:10 -03 2020
Tue Sep 15 14:18:10 -03 2020
Tue Sep 15 14:18:10 -03 2020
root@kali-WSL: /tools/nikto# (echo test; sleep 1; echo test2; sleep 1; echo test3; sleep 1) | while read i; do date; done
Tue Sep 15 14:18:49 -03 2020
Tue Sep 15 14:18:50 -03 2020
Tue Sep 15 14:18:51 -03 2020
root@kali-WSL: /tools/nikto#


```


As expected, the for loop will wait all sleeps, and the "while" will execute each second.

**Comment by digininja** [comment]
I've got it!

in the nfetch function, there are checks done on `$CLI` which, according to the comment is to check for input:

```
    # check for keyboard input
```

If I chop all of the references to `$CLI` out of the script, nothing is removed and it works as expected.

I guess that `$CLI` is eating the first character of the input from the loop as keyboard input.

I don't know enough about Perl to fix it, hopefully you can take it from here @sullo

**Comment by tautology0** [comment]
I was just going to say it's because nikto hooks onto stdin for debugging, just like nmap. As the while builtin uses stdin in the pipeline it messes it about.

IMO you should always use the for builtin for shell loops (as it works in memory and doesn't mess with std(in|out)), e.g.
`for i in $(nmap -sL -n 192.168.0.128/28 | awk '/report/ {print $NF}');do echo ${i};nikto -url ${i};done`

I suppose we could add a switch to nikto, such as -no-interact

**Comment by digininja** [comment]
Adding a switch may help, or maybe just documenting it (if it isn't
already). I think someone who is able to write something in one loop style
would probably be able to rewrite it with a for loop. The main issue would
be spotting it in the first place and then being able to understand why it
is happening.

**Comment by carmoflavio** [comment]
Workaround is to call nikto with the "-nointeractive" parameter. This will prevent the check input call and fixes the issue, apparently.


A real fix might be a pain if you can't discriminate from key press vs. input buffer from pipe...


Thanks guys, I learned something cool today with this :)..

**Comment by digininja** [comment]
@tautology0 looks like you already have the switch with almost the name you suggested!

**Comment by carmoflavio** [comment]
> I was just going to say it's because nikto hooks onto stdin for debugging, just like nmap. As the while builtin uses stdin in the pipeline it messes it about.
> 
> IMO you should always use the for builtin for shell loops (as it works in memory and doesn't mess with std(in|out)), e.g.
> `for i in $(nmap -sL -n 192.168.0.128/28 | awk '/report/ {print $NF}');do echo ${i};nikto -url ${i};done`
> 
> I suppose we could add a switch to nikto, such as -no-interact

Yes, most of the time using "while read" is quite uncommon.. 
I found it out because I have the habit of running nmap on "tee" and parsing output to trigger nikto scans on the fly.. 
So nmap is writing output and a tail -f with "while read" is detecting "http" services and firing up nikto scans... 

As I said, it is all fixed with the -nointeractive flag and everything works as expected.
