### ISSUE TITLE
Feature: Display progress indicator for routine

### ISSUE THREAD

**Issue by ComradeLV** [sullo/nikto#709]
### Description
For me, as a user, it will be nice to have an option to see, how much tests are performed yet, and how much tests are still in queue. Currently there is nothing shown at the last line in terminal, while program is running, and user cannot be sure, if tests are still performing.

Please correct me, if i just missed option like this somewhere in documentation.

**Comment by sullo** [comment]
You can press the spacebar while running to see status. Note it polls for keyboard input every 10 requests, so if a scan is moving slowly you might have to wait. 

See this for more info on other interactive commands:
https://cirt.net/nikto2-docs/usage.html#id2741122

**Comment by ComradeLV** [comment]
Thanks for the response! I think this feature can be mentioned in the README of project repository
