### ISSUE TITLE
Feature: 404 detection when server responds with 200

### ISSUE THREAD

**Issue by BustedSec** [sullo/nikto#710]
### Description
Some servers have custom 404 pages that are served with a 200 response codes and show the 404 as an image along with some text to the user. This confuses nikto and leads to tons of false positives, especially when enumerating plugins. 

One solution put out by Blackhills is below, Rather than redirecting traffic through a local proxy and using a script to rewrite 404s as 200's when they match text in the body of a document I suggest adding native implementation of this into nikto.

having a switch like -rewrite404 that accepts a regex or just simple keyword as a parameter to search for within the body tag.  

### Links/Info
https://www.blackhillsinfosec.com/nikto-oh-where-oh-where-have-my-404s-gone/

**Comment by iasdeoupxe** [comment]
Please correct me if i'm wrong but isn't this already possible since longer time (even before the linked blog post) with the following option of Nikto:

> -404string         Ignore this string in response body content as negative response (always). Can be a regular expression.

originating from #169 / f9cadbe9ea7755851eb2501737348f83db63b2bb / e114edfa969ee62eb200eb292ccf721b00034f67

**Comment by BustedSec** [comment]
Aww crap I had no idea that this string existed I must have not seen it
when looking over the man page
