### ISSUE TITLE
Bug: fix "Uncommon header" detection

### ISSUE THREAD

**Issue by jcvignoli** [sullo/nikto#713]
### Expected behavior
Nikto should report on true Uncommon header detected
### Actual behavior
Nikto reports Uncommon header for legitimate headers, such as:
nel
report-to
permissions-policy

### Nikto version
Nikto 2.1.6

**Comment by sullo** [comment]
Thanks for the tips. I went ahead and started printing the urls from the report-to header as well.

**Comment by jcvignoli** [comment]
Hi,

The report-to is still reported as uncommon header with the latest git version.
