### ISSUE TITLE
Bug: remove "The site uses SSL and Expect-CT header is not present."

### ISSUE THREAD

**Issue by jcvignoli** [sullo/nikto#714]
### Expected behavior

Expect-CT header is gonna be deprecated very soon. It shouldn't be reported by Nikto as missing.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

### Actual behavior

Should the website not include the header, Nikto reports "The site uses SSL and Expect-CT header is not present."

**Comment by sullo** [comment]
Thanks, good call!
