### ISSUE TITLE
The 404code option terminates nikto early, skipping most tests

### ISSUE THREAD

**Issue by karelklic** [sullo/nikto#715]
When `nikto -host xxx -404code 404` is executed, nikto runs a lower number of tests than what's run without the `-404code` option. Nikto seems to terminate on the first test returning 404.

There is a loop over all tests in the `nikto_tests.plugin` file. One section in this loop checks the return code from test request and compares it with the list provided via `-404code` command-line option:
```
# If user puts a @CODE= string in db_404_strings, let it take precedence
foreach my $code (keys %{ $VARIABLES->{'ERRCODES'} }) {
   if ($res =~ /$code/) {
       return;
   }
}
```

If `res` matches, `return` is called which terminates the whole loop with all tests.
Perhaps `next` should be used here instead to skip a single test.

**Comment by tautology0** [comment]
Oh heck, good find - that bug's probably been in there since I moved it from nikto_core to a separate plugin!

**Comment by karelklic** [comment]
Nikto with this patch seems to work fine:
```patch
--- a/program/plugins/nikto_tests.plugin
+++ b/program/plugins/nikto_tests.plugin
@@ -59,7 +59,7 @@ sub nikto_tests {
         my @urilist = change_variables($TESTS{$checkid}{'uri'});
 
         # Now repeat for each uri
-        foreach my $uri (@urilist) {
+        URI: foreach my $uri (@urilist) {
             return if $mark->{'terminate'};
             my %headrs;
             my %flags;
             # If user puts a @CODE= string in db_404_strings, let it take precedence
             foreach my $code (keys %{ $VARIABLES->{'ERRCODES'} }) {
                 if ($res =~ /$code/) {
-                    return;
+                    next URI;
                 }
             }
 ```

**Comment by sullo** [comment]
Thanks for the patch, and indeed a good catch.
