### ISSUE TITLE
Bug: "report-to" still reported as "Uncommon header"

### ISSUE THREAD

**Issue by jcvignoli** [sullo/nikto#717]
Hi,

Follow-up of a previous [bug report](https://github.com/sullo/nikto/issues/713)

The report-to is still reported as uncommon header with the latest git version.

Thanks.

**Comment by iasdeoupxe** [comment]
Looks like t his was added but commented out here:

https://github.com/sullo/nikto/commit/77895860140094fbf2a32a6282de0d47f117141a#diff-48a05067821a2beb273da897a2ee5883127a99b5f1d18a1ac7c9c05898c25c28R81

Maybe @sullo can shed some light on the reason why it is commented out?

**Comment by sullo** [comment]
I was testing the functionality in the headers plugin, which now reports the report-to URIs, I think.

**Comment by jcvignoli** [comment]
I reopen the bug. I still get 

````
Uncommon header 'report-to' found, with contents: {"group":"nel","max_age":31536000,"endpoints":[{"url":"https://whatever"}]}, {"group":"csp","max_age":31536000,"endpoints":[{"url":"https://whatever"}]}
````

With nikto 2.1.6

**Comment by jcvignoli** [comment]
I've no idea how to reopen it. Gonna open a new ticket.

**Comment by iasdeoupxe** [comment]
https://github.com/sullo/nikto/issues/735#issuecomment-894772474
