### ISSUE TITLE
Feature: Provide/use URI path

### ISSUE THREAD

**Issue by darkspirit510** [sullo/nikto#723]
### Description

I'd like to pass an URI including a subdirectory or give one as additional parameter so nikto will search for vulnerabilities at the given page (and everything it finds linked there :-))

### Links/Info

I'm currently testing several open source tools against https://github.com/OWASP/Benchmark/. This tool serves a tomcat at `https://[server|localhost]:8443/benchmark/` and contains several thousand vulnerabilities. Using nikto like `./nikto.pl -h https://server:8443/benchmark/ -o nikto.json` does not find any issue. I guess it'll just use the root path but does not go to /benchmark.

**Comment by darkspirit510** [comment]
The actual result of the given command looks like:

```
{
  "host": "server",
  "ip": "192.168.1.123",
  "port": "8443",
  "banner": "",
  "vulnerabilities": [
    {
      "id": "999993",
      "OSVDB": "0",
      "method": "GET",
      "url": "/benchmark/",
      "msg": "Hostname 'server' does not match certificate's names: OWASP"
    },
    {
      "id": "500670",
      "OSVDB": "39272",
      "method": "GET",
      "url": "/benchmark/favicon.ico",
      "msg": "/benchmark/favicon.ico file identifies this app/server as: owasp.org"
    },
    {
      "id": "999990",
      "OSVDB": "0",
      "method": "OPTIONS",
      "url": "/benchmark/",
      "msg": "Allowed HTTP Methods: OPTIONS, GET, HEAD, POST "
    }
  ]
}
```

**Comment by sullo** [comment]
Nikto is properly making the request to the specified subdirectory `/benchmark/` but it is not finding any issues. This may be expected behavior. While Nikto checks for many files and vulnerabilities, it doesn't crawl and test input fields in the way something like Burpsuite does, which is where these vulnerabilities lie.

I'm going to close this issue but if I am misunderstanding please reopen.

**Comment by darkspirit510** [comment]
Okay, i really expected nikto to somehow crawl for any link in the page and not just for "well-known paths". I wonder how nikto does detect
```
[...]
4     Injection (XSS/Script/HTML)
[...]
8     Command Execution / Remote Shell
9     SQL Injection
```
then?
