### ISSUE TITLE
SSL not supporting in Termux

### ISSUE THREAD

**Issue by 3i3eye** [sullo/nikto#725]
Coz of it Termux users have no benefit of nikto...
Please add ssl in nikto.conf  or tell me how to do it

**Comment by sullo** [comment]
Try setting the perl ssl library manually. You may actually need to install one of the required perl modules (which may in turn require installing OpenSSL). I don't plan to support Termux directly so I'm going to close the issue.

from nikto.conf:
# Choose SSL libs:
# SSLeay        - use Net::SSLeay
# SSL           - use Net::SSL
#                 (SSLeay wins if both are available)
LW_SSL_ENGINE=auto

**Comment by StringManolo** [comment]
In case anyone has same question, here is how i made it work for me:

Installing "perl-net-ssleay" without editing nikto.conf or reinstalling anything worked for me.

I used Alpine in Termux proot-distro. 
```bash
apk add nikto
apk add perl-net-ssleay

mv /usr/bin/nikto.pl /usr/bin/nikto

nikto -h example.com
```
