### ISSUE TITLE
Scrub is broken

### ISSUE THREAD

**Issue by tautology0** [sullo/nikto#729]
At some point scrub got broken out into a function which doesn't have the correct parameters passed to it. The function does too different things and gets both of them wrong:
- It scrubs on dump_var - but in this content it doesn't have a $mark object
- It scrubs on nprint - where it should know about $mark but it isn't passed to the call

The quickest solution is to create scrub_var and scrub functions which will do each job.

**Comment by tautology0** [comment]
This cases nikto to fatal error if it has a cert with altnames:

`
![image](https://user-images.githubusercontent.com/3503697/123843342-b9cbb400-d909-11eb-92ec-8482d3800437.png)
`

**Comment by sullo** [comment]
@tautology0 was this in 2.5.0 branch? I reworked a lot of things.

For example, every call to dump_var() should pass things like IPs, hostnames, etc so they can be sent to scrub().

**Comment by tautology0** [comment]
It was in trunk; I'll give it a go in 2.5.0 when I have a laptop with a working perl booted.

**Comment by tautology0** [comment]
Yep; it's fine in 2.5.0; broken in master for 2.1.6; happy to close as WONTFIX.
