### ISSUE TITLE
Bug: "report-to" still reported as "Uncommon header"

### ISSUE THREAD

**Issue by jcvignoli** [sullo/nikto#735]
I reopen the bug. I still get 

````
Uncommon header 'report-to' found, with contents: {"group":"nel","max_age":31536000,"endpoints":[{"url":"https://whatever"}]}, {"group":"csp","max_age":31536000,"endpoints":[{"url":"https://whatever"}]}
````

With nikto 2.1.6

**Comment by iasdeoupxe** [comment]
> With nikto 2.1.6

Only master (d27173173bebac29fa89ef3a493febab16594a12) and nikto 2.5.0 (d427fbd23cf1ff3abf1a03cc3fa32ca2a2d23a06) contains the fix, not 2.1.6 so this can be closed.

**Comment by jcvignoli** [comment]
My bad. Thanks for pointing it out.
I updated and everything works perfectly.

**Comment by tautology0** [comment]
I've closed the issue - if it is still a problem I can reopen the original one.
