### ISSUE TITLE
X-XSS-Protection is Deprecated

### ISSUE THREAD

**Issue by obi-jon** [sullo/nikto#743]
### The X-XSS-Protection Header is deprecated

X-XSS-Protection is no longer supported by the "big" three (Chrome/Firefox/Edge)

Mozilla is recommending Content-Security-Policy implementation
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection] 

Might keep the nikto tool relevant to update the headers it looks for.

**Comment by digininja** [comment]
Don't know what the current output from the plug-in is, but I'd suggest
still detecting it and updating the message to say it is deprecated.

Doesn't hurt to have it.

**Comment by sullo** [comment]
This was removed in the 2.5.0 branch #705

https://github.com/sullo/nikto/issues/705

**Comment by obi-jon** [comment]
just pulled 2.5.0 and it still shows the 
**X-XSS-Protection header has been set to disable XSS Protection. There is unlikely to be a good reason for this.**

**Comment by digininja** [comment]
That seems like a good answer to me. The fact the old protection has been
turned off indicates that something bad is going on.

**Comment by sullo** [comment]
```
╰─± grep -i x-xss `find . -type f`
./databases/db_headers:"x-xss-protection"
```

The x-xss string only exists in the database, so it would be unable to print this.

**Comment by tautology0** [comment]
Just to add - if the OP is using Kali, then uninstall the nikto package  and just use it from git - as the Kali package makes an /etc/nikto.conf, this overrides the nikto.conf.default in the programs directory so you end up using nikto 2.5.0, but it uses the nikto 2.1.6 plugins and databases.

Not that I got really confused by this in the past, oh no.
