### ISSUE TITLE
False Positive/Negative:  Potentially interesting archive/cert file found

### ISSUE THREAD

**Issue by obi-jon** [sullo/nikto#744]
### Output of suspected false positive / negative

It appears that Nikto is only looking for Status OK or Redirection responses to identify potentially interesting archives/certs.  Applications that redirect the user to a log in/home page will cause all these "interesting" files to be false positives.

Maybe consider comparing the responses to ensure that they aren't all pointing to the exact same path.

**Comment by adi928** [comment]
I traced it down to `plugins/nikto_sitefiles.plugin`
for now, if you rename this file to something else, it will not be used during the scan.

**Comment by sullo** [comment]
Duplicate of #728.
