### ISSUE TITLE
Add word and line filter

### ISSUE THREAD

**Issue by BustedSec** [sullo/nikto#754]
### Description
Nikto has issues when it scans sites that have improper HTTP status code responses, such as 302 being returned rather than 404 for a non-existent resource. There are multiple issues open regarding this, but there has not been a solution found yet, despite some very good sugguestions from the community in the issue comment area. 

There is a fuzzing tool called ffuf that is able to work around this issue by allowing the usage of filters - such as the -fw and -fl  to filter based on the number of words on a page and the number of lines on the page. A similar functionality added to nikto could provide a relatively easy fix for when this issue is present. That way, if a page returns the wrong code it could be corrected during scan time and not affect results thus reducing false positives. 

I know ffuf is written in GO and your tool is written in perl, if I was a better programmer I'd attempt to port the feature myself, but my experience is limited with perl.

**Comment by sullo** [comment]
Please check out the `-404code` and `-404string` command line options:
https://github.com/sullo/nikto/wiki/Annotated-Option-List

**Comment by BustedSec** [comment]
> Please check out the `-404code` and `-404string` command line options: https://github.com/sullo/nikto/wiki/Annotated-Option-List

The two refereneced command line switches do not always work well, and more often than not do not work at all when sites are configured in a certain way or use many popular WAFs.  Please consider adding in the requested feature. Thank you

**Comment by sullo** [comment]
If those command line options aren't working in some cases please open tickets with as much detail as you can provide. 

As for the requested feature, could you explain in more detail how that works?
