### ISSUE TITLE
Bug: HTTP Basic Auth not working

### ISSUE THREAD

**Issue by sschroep** [sullo/nikto#762]
I have a website which is using header based http basic auth. Unfortunately nikto is not sending any authorization headers.

I'm running 
`nikto -h https://HOST/ -id ID:PASSWD -useproxy https://127.0.0.1:8080/ -ssl -Display D`
On Port 8080 i have a mitmproxy through which i want to record the traffic.

The nikto debug output gives me the following:

<pre>D:Thu Feb 24 17:10:44 2022 &apos;Request Hash&apos; = {
	&apos;whisker&apos; =&gt; {
		&apos;force_open&apos; =&gt; 0,
		&apos;uri&apos; =&gt; &apos;/&apos;,
		&apos;protocol&apos; =&gt; &apos;HTTP&apos;,
		&apos;invalid_protocol_return_value&apos; =&gt; 1,
		&apos;proxy_host&apos; =&gt; &apos;127.0.0.1&apos;,
		&apos;http_eol&apos; =&gt; &quot;\r\n&quot;,
		&apos;require_newline_after_headers&apos; =&gt; 0,
		&apos;uri_param_sep&apos; =&gt; &apos;?&apos;,
		&apos;ignore_duplicate_headers&apos; =&gt; 1,
		&apos;proxy_port&apos; =&gt; 8080,
		&apos;http_space1&apos; =&gt; &apos; &apos;,
		&apos;ssl&apos; =&gt; 1,
		&apos;MAGIC&apos; =&gt; 31339,
		&apos;ssl_certfile&apos; =&gt; undef,
		&apos;port&apos; =&gt; 443,
		&apos;ssl_save_info&apos; =&gt; 1,
		&apos;host&apos; =&gt; &apos;HOST&apos;,
		&apos;keep-alive&apos; =&gt; 1,
		&apos;ssl_rsacertfile&apos; =&gt; undef,
		&apos;http_space2&apos; =&gt; &apos; &apos;,
		&apos;version&apos; =&gt; &apos;1.1&apos;,
		&apos;method&apos; =&gt; &apos;GET&apos;,
		&apos;uri_postfix&apos; =&gt; &apos;&apos;,
		&apos;normalize_incoming_headers&apos; =&gt; 1,
		&apos;max_size&apos; =&gt; 0,
		&apos;force_close&apos; =&gt; 0,
		&apos;force_bodysnatch&apos; =&gt; 0,
		&apos;trailing_slurp&apos; =&gt; 0,
		&apos;include_host_in_uri&apos; =&gt; 1,
		&apos;uri_prefix&apos; =&gt; &apos;&apos;,
		&apos;retry&apos; =&gt; 0,
		&apos;timeout&apos; =&gt; 10,
		&apos;lowercase_incoming_headers&apos; =&gt; 1
	},
	&apos;User-Agent&apos; =&gt; &apos;Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0&apos;,
	&apos;Host&apos; =&gt; &apos;HOST:443&apos;,
	&apos;Connection&apos; =&gt; &apos;Keep-Alive&apos;
};
D:Thu Feb 24 17:10:44 2022 &apos;Result Hash&apos; = {
	&apos;www-authenticate&apos; =&gt; &apos;Basic realm=&quot;REALM VALUE&quot;&apos;,
	&apos;date&apos; =&gt; &apos;Thu, 24 Feb 2022 16:10:41 GMT&apos;,
	&apos;x-content-type-options&apos; =&gt; &apos;nosniff&apos;,
	&apos;content-length&apos; =&gt; 381,
	&apos;strict-transport-security&apos; =&gt; &apos;max-age=31536000; preload&apos;,
	&apos;x-xss-protection&apos; =&gt; &apos;1; mode=block&apos;,
	&apos;content-type&apos; =&gt; &apos;text/html; charset=iso-8859-1&apos;,
	&apos;server&apos; =&gt; &apos;Apache&apos;,
	&apos;content-security-policy&apos; =&gt; &apos;frame-ancestors \&apos;self\&apos;;&apos;,
	&apos;whisker&apos; =&gt; {
		&apos;protocol&apos; =&gt; &apos;HTTP&apos;,
		&apos;http_space2&apos; =&gt; &apos; &apos;,
		&apos;data&apos; =&gt; &quot;&lt;!DOCTYPE HTML PUBLIC \&quot;-//IETF//DTD HTML 2.0//EN\&quot;&gt;\n&lt;html&gt;&lt;head&gt;\n&lt;title&gt;401 Unauthorized&lt;/title&gt;\n&lt;/head&gt;&lt;body&gt;\n&lt;h1&gt;Unauthorized&lt;/h1&gt;\n&lt;p&gt;This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn&apos;t understand how to supply\nthe credentials required.&lt;/p&gt;\n&lt;/body&gt;&lt;/html&gt;\n&quot;,
		&apos;header_order&apos; =&gt; [
			&apos;date&apos;,
			&apos;server&apos;,
			&apos;x-xss-protection&apos;,
			&apos;content-security-policy&apos;,
			&apos;strict-transport-security&apos;,
			&apos;x-content-type-options&apos;,
			&apos;www-authenticate&apos;,
			&apos;content-length&apos;,
			&apos;content-type&apos;
		],
		&apos;version&apos; =&gt; &apos;1.1&apos;,
		&apos;stats_syns&apos; =&gt; 3,
		&apos;ssl_cipher&apos; =&gt; &apos;TLS_AES_256_GCM_SHA384&apos;,
		&apos;code&apos; =&gt; 401,
		&apos;message&apos; =&gt; &apos;Unauthorized&apos;,
		&apos;http_data_sent&apos; =&gt; 1,
		&apos;ssl_cert_subject&apos; =&gt; &apos;/CN=HOST&apos;,
		&apos;uri&apos; =&gt; &apos;/&apos;,
		&apos;http_space1&apos; =&gt; &apos; &apos;,
		&apos;ssl_cert_issuer&apos; =&gt; &apos;/CN=mitmproxy/O=mitmproxy&apos;,
		&apos;socket_state&apos; =&gt; 0,
		&apos;lowercase_incoming_headers&apos; =&gt; 1,
		&apos;MAGIC&apos; =&gt; 31340,
		&apos;http_eol&apos; =&gt; &quot;\r\n&quot;,
		&apos;stats_reqs&apos; =&gt; 3
	}
};
</pre>

As you can see, nikto is not sending an authorization Header to the server. It seems to me the -id param is simply ignored.
Can somebody help me?

**Comment by sullo** [comment]
which version of Nikto are you running--2.1.6 or 2.5.0 from github?

**Comment by sullo** [comment]
@sschroep can you test this out and make sure it works for you?

**Comment by sullo** [comment]
Closing due to lack of feedback.
