### ISSUE TITLE
Feature: Add support for LocalStorage / Session Storage credentials

### ISSUE THREAD

**Issue by vohai2003** [sullo/nikto#773]
### Description
There're some sites that not save their login credentials in cookies, instead they're in LocalStorage
### Links/Info
![image](https://user-images.githubusercontent.com/63694226/189461679-a841c815-5bcc-4c3b-8be9-58c8f2330a34.png)

**Comment by sullo** [comment]
Because localstorage is set set via JavaScript, with nikto not having no JavaScript engine or parser, it's not something we have visibility into and so wouldn't be able to support.
