### ISSUE TITLE
Bug: Invalid JSON when no web server found

### ISSUE THREAD

**Issue by undergroundwires** [sullo/nikto#774]
### Expected behavior

Valid JSON without extra bracket in the end.

### Actual behavior

```
{"id": "000029","OSVDB": "0","url":"/","msg":"No web server found on **.**.**.**:2053"}}
```
Extra data: line 1 column 89 (char 88)

### Steps to reproduce

1. CLI arguments: ` -Format json -output 'nikto-output.json'`
2. Situation: IP is alive, port exists according to nmap it is HTTPS port, but the browser returns cipher error, probably bad configured.

### Nikto version

2.1.6

**Comment by sullo** [comment]
If 2.1.6: Please perform a git pull as [this change](https://github.com/sullo/nikto/commit/fed0c5cab5ed00c4b8f07a781a8fcde25fe3bce2) may have fixed it. 

I Also recommend running 2.5.0.
