### ISSUE TITLE
Bug:  "id" option wit only user and empty password does not work.

### ISSUE THREAD

**Issue by p4ntek** [sullo/nikto#798]
### Expected behavior
When i put example "-id admin:" it should work.
### Actual behavior
"Requires Authentication for realm..." and when i input random 2 letters its go on, but with wrong auth.
### Steps to reproduce
./nikto.pl -h 192.168.0.1 -id admin:

### Nikto version
2.5.0 (LW 2.5)

**Comment by sullo** [comment]
@p4ntek can you give this another try after doing a pull on the source?

**Comment by p4ntek** [comment]
> @p4ntek can you give this another try after doing a pull on the source?

Now it works. Thx
