### ISSUE TITLE
Bug: Syntax Check:

### ISSUE THREAD

**Issue by Faceless0x1337** [sullo/nikto#800]
Hi, thanks for your such a cool tool. Why am I getting these errors?

### Steps to reproduce
$ perl nikto.pl -dbcheck

### Nikto version
2.5.0
Run:

```
./nikto.pl -Version
```
Nikto 2.5.0 (LW 2.5)

Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_httpoptions
        12 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_embedded
        16 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_headers
        118 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_variables
        38 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_server_msgs
        259 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_realms
        170 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_404_strings
        39 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_domino
        274 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_content_search
        20 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_drupal
        6244 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_dictionary
        1825 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_multiple_index
        35 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_favicon
        361 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_outdated
        1256 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_tests
        6951 entries
Syntax Check: /home/kali/Desktop/face/tools/frameworks/nikto/program/databases/db_parked_strings
        9 entries
Checking plugins for duplicate test IDs

Some (probably) open IDs: 000137, 000154, 000287, 000326, 000407, 000427, 000429

**Comment by sullo** [comment]
Hi! These are not errors. This looks like the output of the `-dbcheck` option, which checks the syntax of the db_* files in the databases folder. It is reporting the total number of entries and no syntax errors. 

This should only happen with `-dbcheck` and not with `-Version`--can you confirm?

Here is my output of `-Version`:
```
perl nikto.pl -Version
Nikto 2.5.0 (LW 2.5)
```

**Comment by Faceless0x1337** [comment]
> Привет! Это не ошибки. Это похоже на результат работы опции `-dbcheck`, которая проверяет синтаксис файлов db_* в папке баз данных. Он сообщает об общем количестве записей и отсутствии синтаксических ошибок.
> 
> Это должно произойти только с `-dbcheck`и не с `-Version`-- можете ли вы подтвердить?
> 
> Вот мой результат `-Version`:
> 
> ```
> perl nikto.pl -Version
> Nikto 2.5.0 (LW 2.5)
> ```

Yes, that’s right, this only happens in -dbcheck, I apologize for the confusion in the question. Thanks, good luck

**Comment by Faceless0x1337** [comment]
> Hi! These are not errors. This looks like the output of the `-dbcheck` option, which checks the syntax of the db_* files in the databases folder. It is reporting the total number of entries and no syntax errors.
> 
> This should only happen with `-dbcheck` and not with `-Version`--can you confirm?
> 
> Here is my output of `-Version`:
> 
> ```
> perl nikto.pl -Version
> Nikto 2.5.0 (LW 2.5)
> ```

Yes, that’s right, this only happens in -dbcheck, I apologize for the confusion in the question. Thanks, good luck
