### ISSUE TITLE
Libwhisker license information 

### ISSUE THREAD

**Issue by xambroz** [sullo/nikto#806]
Hello,
[https://github.com/sullo/nikto/wiki/Nikto-Licensing](https://github.com/sullo/nikto/wiki/Nikto-Licensing)
there is some wrong information published about the embedded libwhisker perl library. 
It is stated that the license is also GPL, but it is actually BSD-2-Clause [the SPDX short name](https://spdx.org/licenses/BSD-2-Clause.html).

I would recommend adding some relevant license file, like COPYING.libwhisker2 , so it can be easily used  by the software packagers.

### Nikto version
2.5.0

**Comment by sullo** [comment]
Thanks for pointing this out. 

I've updated the documentation page and added COPYING.LibWhisker per suggestion.
