### ISSUE TITLE
Feature: Severity or criticality classification of found issues.

### ISSUE THREAD

**Issue by manuel-sommer** [sullo/nikto#815]
### Description
In the JSON output, the criticality of reported issues is missing. Thus, it is sometimes hard to figure out which vulnerability is the most critical one. Could you add some kind of evaluation / classification in the output (JSON) to get some kind of severity? (e.g. Critical, High, Medium, Low)

**Comment by sullo** [comment]
Nikto tests don't have severity recorded, so this wouldn't be feasible without guessing. 

Results should be manually validated to determine if they are legitimate and what risk they pose to the server.
