### ISSUE TITLE
Bug:  /splashAdmin.php: Cobalt Qube 3 admin is running. This may have multiple security problems as described by www.scan-associates.net. These could not be tested remotely.

### ISSUE THREAD

**Issue by anishshahmd** [sullo/nikto#833]
I'm getting this issue after scanning our Webportal 

### Nikto version
2.1.5

command used : 
nikto -h  http://----------.cloudfront.net -output  ./report.txt

Output :  
- Nikto v2.1.5
---------------------------------------------------------------------------
+ Target IP:          <IP>
+ Target Hostname:    d--------.cloudfront.net
+ Target Port:        80
+ Start Time:         2024-07-01 10:52:32 (GMT0)
---------------------------------------------------------------------------
+ Server: CloudFront
+ Retrieved via header: 1.1 3681463337d4e41e1a.cloudfront.net (CloudFront)
+ Uncommon header 'x-xss-protection' found, with contents: 1; mode=block
+ Uncommon header 'x-content-type-options' found, with contents: nosniff
+ Uncommon header 'x-frame-options' found, with contents: SAMEORIGIN
+ Uncommon header 'x-cache' found, with contents: Redirect from cloudfront
+ Uncommon header 'x-amz-cf-id' found, with contents: jibT6qYWR2y7H4rgNpDXPXG8VxJqNAZltePZCk0i9nK65cHlTdLcXw==
+ Uncommon header 'x-amz-cf-pop' found, with contents: IAD89-C3
+ Uncommon header 'referrer-policy' found, with contents: strict-origin-when-cross-origin
+ Root page / redirects to: https://d--------.cloudfront.net/
+ No CGI Directories found (use '-C all' to force check all possible dirs)

+ /splashAdmin.php: Cobalt Qube 3 admin is running. This may have multiple security problems as described by www.scan-associates.net. These could not be tested remotely.
+ /blah_badfile.shtml: Allaire ColdFusion allows JSP source viewed through a vulnerable SSI call.
+ OSVDB-17655: /SiteServer/Admin/commerce/foundation/DSN.asp: Displays all DSNs configured for selected ODBC drivers.
+ /fpdb/shop.mdb: MetaCart2 is an ASP shopping cart. The database of customers is available via the web.
+ /servlet/com.livesoftware.jrun.plugins.ssi.SSIFilter: Allaire ColdFusion allows JSP source viewed through a vulnerable SSI call.
+ /servlet/sunexamples.BBoardServlet: This default servlet lets attackers execute arbitrary commands.
+ /examples/jsp/snp/anything.snp: Tomcat servlet gives lots of host information.
+ /pmlite.php: A Xoops CMS script was found. Version RC3 and below allows all users to view all messages (untested). See http://www.phpsecure.org/?zone=pComment&d=101 for details.
+ /servlet/allaire.jrun.ssi.SSIFilter: Allaire ColdFusion allows JSP source viewed through a vulnerable SSI call, see MPSB01-12 http://www.macromedia.com/devnet/security/security_zone/mpsb01-12.html.

We don't have any services running on our webserver like  /pmlite.php ,  /splashAdmin.php etc 
how to resolve these issues ?

**Comment by sullo** [comment]
Your web server is returning 200 OK for files that aren't there (this is typically a 4xx response). Taking a quick look at the tests in the output, it seems that  they match a 200.

There's nothing to 'fix' after you confirm they are false positives. If there's a string in your 200 "error" response you can try using `-404string` to compensate.

They are alerting because of a weak matcher in Nikto (the 200) and improper (though relatively common) response from the webserver (200)
