### ISSUE TITLE
Nitko always exits with a non-0 exit code.

### ISSUE THREAD

**Issue by Souf149** [sullo/nikto#837]
### Expected behavior
After succesfully running Nitko with no issues a 0 exit code should be given.

### Actual behavior
After seemingly succesfully running Nitko with no issues a non-0 exit code is given.

### Steps to reproduce

1. run this dockerfile with `docker build ./ -t myImage && docker run myImage`
```dockerfile
FROM python:3.11-slim

WORKDIR /app
RUN adduser --disabled-password --gecos '' nonroot
RUN apt update -y && apt-get install -y --no-install-recommends git && pip install httpx
COPY ./client.py ./client.py

RUN git clone https://github.com/sullo/nikto

RUN ./nikto/program/nikto.pl -h example.com -o /tmp/output.json

ENTRYPOINT [ "/usr/local/bin/python", "-m", "client" ]

USER nonroot
```
2. Observe that `RUN ./nikto/program/nikto.pl -h 46.23.85.171 -o /tmp/output.json` exits the dockerfile because it has ran into an error.

### Question
Is there a reason I am not seeing why a non-0 exit code is given? I was not able to find anything about it in existing issues or the documentation

**Comment by digininja** [comment]
I just ran Nikto from the command line against my site and got a return
code of 1. I never normally check but there were no errors so I assume this
is the default return code.

**Comment by Souf149** [comment]
According to [geeksforgeeks](https://www.geeksforgeeks.org/how-to-use-exit-code-to-read-from-terminal-from-script-and-with-logical-operators/) the default (non-error) code should be 0. This makes it an issue when making a service with docker's `RUN` command.

Would it be possible to change this?

**Comment by digininja** [comment]
As a temporary fix you could add a shim which runs nikto and then returns
0. You then have Docker run your script rather than running Nikto directly.

**Comment by digininja** [comment]
That is up to Sullo, I just run the tool and make suggestions.

**Comment by Souf149** [comment]
Thank you for your inputs. 😁

Is Sullo still active?

**Comment by digininja** [comment]
Yes, I'm sure he will be in touch when he has a spare five minutes.

**Comment by sullo** [comment]
Perl's default exit code is 0 as far as I can see. In many places the code is explicitly using 0/1 exit codes (that should be cleaned up to be all locations). 

I think the problem is this bit:
```
    if ($mark->{'total_errors'} > 0 || $mark->{'total_vulns'} > 0) {
        $is_failure = 1;
    }
```
and then the final exit
```
nprint("+ $COUNTERS{'hosts_completed'} host(s) tested");
nprint("+ $COUNTERS{'totalrequests'} requests made in $COUNTERS{'scan_elapsed'} seconds", "v");

send_updates(@MARKS);

nprint("T:" . localtime() . ": Ending", "d");

exit $is_failure;
```

So, if there are _any_ errors OR findings, it will exit with an error code. Seems like the intent was to signal if the _scan_ ran ok rather than the program. I can't think of a good reason for this now. 

I'll whip up a patch; this isn't complicated.

**Comment by sullo** [comment]
@Souf149  that should be resolved with a new `git pull`. please let us know & close if it's resolved.

**Comment by Souf149** [comment]
Thank you for the quick fix! From testing I have learnt that the problem has been fixed. Issue resolved!
