### ISSUE TITLE
Rewriting sensitive portions in a fully memory-safe language

### ISSUE THREAD

**Issue by Ricky-Tigg** [sullo/nikto#840]
Hello. When will the sensitive portions of your code – now in **Perl** – be transitioned to a fully memory-safe programming language, as are **Rust**, **Go**, **Java**? Or ever? That would prevent memory-related issues.

**Comment by digininja** [comment]
It depends, when are you planning to submit the pull request with all the
changes? It can't be that hard for someone of your level to put it together.

**Comment by sullo** [comment]
It's unlikely to be rewritten in a modern language unless someone else does it.
