### ISSUE TITLE
License (once more)

### ISSUE THREAD

**Issue by Ricky-Tigg** [sullo/nikto#841]
Hello. Although it is hard to imagine nowadays what could motivate a programmer to refrain from presenting his product completely, well here we see that it can indeed exist. Unable to guess what you could possibly be trying to achieve by acting in this way. In any case, it persists, as illustrated below regarding the **license**; excerpt from the _[About](https://github.com/sullo/nikto)_-section:

![github com_sullo_nikto_repository](https://github.com/user-attachments/assets/d74f440a-ac37-477e-aeda-d7a9e653d074)

You can still click on the text in its environment.

**Comment by digininja** [comment]
Have you tried looking in the licence section?

**Comment by sullo** [comment]
The COPYING file contains the license for the code except LibWhisker, which has its own license, as well as db files which have their own. Putting it on the repo is just a convenience and it would be inaccurate to choose one license.
