### ISSUE TITLE
Bug: Nikto stopped using ports configured via `-port` flag

### ISSUE THREAD

**Issue by J12934** [sullo/nikto#843]
### Expected behavior

`-port` cli flag is used to tell nikto which port to connect to.

E.g.

`nikto -h foobar.example.com -port 3000`

### Actual behavior

Nikto falls back to the default http port 80.

### Steps to reproduce

1. Run `nikto -h <some target witout port 80> -port 3000`
2. Nikto will fail with the following error:

```bash
$ nikto -h 10.10.33.219 -port 3000
- Nikto v2.5.0
---------------------------------------------------------------------------
---------------------------------------------------------------------------
+ Unable to connect to 10.10.33.219:80.
+ 0 host(s) tested
```

### Nikto version

Nikto 2.5.0 (LW 2.5)

(Build from git commit: 9b1d405760f5a56cc2984ae83ee458d6496e79f6)

### Further info

This seems to be a a regression and worked until some days ago.
When the target is passed using -url nikto still seems to be working.

**Comment by J12934** [comment]
Hi @sullo thank you for the quick fix :)

I now get another issue


When using `-port` it now just directly says no target selected:

```bash
$ nikto -h 10.10.33.219 -port 3000   
- Nikto v2.5.0
---------------------------------------------------------------------------
+ 0 host(s) tested
```


With url it still works as expected:


```bash
$ podman run nikto -url http://10.10.33.219:3000
- Nikto v2.5.0
---------------------------------------------------------------------------
+ Target IP:          10.10.33.219
+ Target Hostname:    10.10.33.219
+ Target Port:        3000
+ Start Time:         2024-09-30 15:46:59 (GMT0)
---------------------------------------------------------------------------
+ Server: No banner retrieved
^C
```

**Comment by sullo** [comment]
I missed a testing case and didn't notice a typo... fixed now. thanks for the reports & patience!

**Comment by J12934** [comment]
Awesome thanks again 👍
Will test again later 😊
