### ISSUE TITLE
Bug: Instagram account 

### ISSUE THREAD

**Issue by Molleyace** [sullo/nikto#845]
### Steps to reproduce

1.
2.
3.

### Nikto version

Run:

```
./nikto.pl -Version
```

and paste the output here.

### Further technical info

E.g. you can obtain Nikto debug output by running `-D D` and redirecting to a file.
You may also scrub the output of hostnames and IPs by specifying `-D DS`.

**Comment by ranaaniket1234** [comment]
haking kase sikhe

**Comment by ranaaniket1234** [comment]
> ### Expected behavior
> ### Actual behavior
> ### Steps to reproduce
> 
> ### Nikto version
> Run:
> 
> ```
> ./nikto.pl -Version
> ```
> 
> and paste the output here.
> 
> ### Further technical info
> E.g. you can obtain Nikto debug output by running `-D D` and redirecting to a file. You may also scrub the output of hostnames and IPs by specifying `-D DS`.

its_simu.001 instgram acount paswerd
