### ISSUE TITLE
Bug: Duplicate "Saving Requests Responses & Replaying" Blank Wiki Page

### ISSUE THREAD

**Issue by cmlh** [sullo/nikto#846]
https://github.com/sullo/nikto/wiki/Saving-Requests-Responses-&amp;-Replaying, i.e. `amp;`, is a blank duplicate of https://github.com/sullo/nikto/wiki/Saving-Requests-Responses-&-Replaying

Please remove https://github.com/sullo/nikto/wiki/Saving-Requests-Responses-&amp;-Replaying from the Wiki?

**Comment by sullo** [comment]
Fixed, thanks for pointing this out!
