### ISSUE TITLE
Nikto hangs when probing HTTPS connection using head

### ISSUE THREAD

**Issue by MrSeccubus** [sullo/nikto#85]
I have a certain server that listens on port 443, accepts connections, but does not replay to any requests sent to it.

Nikto hangs on this config even if a timeout is set:
$ nikto -vhost available.atom86.net -Tuning x -timeout 5 -host                                                                                                                                                              95.142.x.x -port 443 -ssl -Display V
## \- Nikto v2.1.5

V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_msgs
V:Mon Aug 12 13:56:40 2013 - Loaded "Server Messages" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_core
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_httpoptions
V:Mon Aug 12 13:56:40 2013 - Loaded "HTTP Options" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_outdated
V:Mon Aug 12 13:56:40 2013 - Loaded "Outdated" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_ssl
V:Mon Aug 12 13:56:40 2013 - Loaded "SSL and cert checks" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_fileops
V:Mon Aug 12 13:56:40 2013 - Loaded "File Operations" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_cookies
V:Mon Aug 12 13:56:40 2013 - Loaded "HTTP Cookie Internal IP" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_content_search
V:Mon Aug 12 13:56:40 2013 - Loaded "Content Search" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_text
V:Mon Aug 12 13:56:40 2013 - Loaded "Text reports" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_robots
V:Mon Aug 12 13:56:40 2013 - Loaded "Robots" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_embedded
V:Mon Aug 12 13:56:40 2013 - Loaded "Embedded Detection" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_tests
V:Mon Aug 12 13:56:40 2013 - Loaded "Nikto Tests" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_paths
V:Mon Aug 12 13:56:40 2013 - Loaded "Path Search" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_favicon
V:Mon Aug 12 13:56:40 2013 - Loaded "Favicon" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_siebel
V:Mon Aug 12 13:56:40 2013 - Loaded "Siebel Checks" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_subdomain
V:Mon Aug 12 13:56:40 2013 - Loaded "Sub-domain forcer" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_dictionary_attack
V:Mon Aug 12 13:56:40 2013 - Loaded "Dictionary attack" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_parked
V:Mon Aug 12 13:56:40 2013 - Loaded "Parked Detection" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_html
V:Mon Aug 12 13:56:40 2013 - Loaded "Report as HTML" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_xml
V:Mon Aug 12 13:56:40 2013 - Loaded "Report as XML" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_multiple_index
V:Mon Aug 12 13:56:40 2013 - Loaded "Multiple Index" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_csv
V:Mon Aug 12 13:56:40 2013 - Loaded "CSV reports" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_headers
V:Mon Aug 12 13:56:40 2013 - Loaded "HTTP Headers" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_apache_expect_xss
V:Mon Aug 12 13:56:40 2013 - Loaded "Apache Expect XSS" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_put_del_test
V:Mon Aug 12 13:56:40 2013 - Loaded "Put/Delete test" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_msf
V:Mon Aug 12 13:56:40 2013 - Loaded "Report data to Metasploit" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_clientaccesspolicy
V:Mon Aug 12 13:56:40 2013 - Loaded "clientaccesspolicy.xml" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_cgi
V:Mon Aug 12 13:56:40 2013 - Loaded "CGI" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_apacheusers
V:Mon Aug 12 13:56:40 2013 - Loaded "Apache Users" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_auth
V:Mon Aug 12 13:56:40 2013 - Loaded "Guess authentication" plugin.
V:Mon Aug 12 13:56:40 2013 - Initialising plugin nikto_report_nbe
V:Mon Aug 12 13:56:40 2013 - Loaded "NBE reports" plugin.
V:Mon Aug 12 13:56:40 2013 - Getting targets
V:Mon Aug 12 13:56:40 2013 - Target:95.142.x.x port:443
V:Mon Aug 12 13:56:40 2013 - Checking for HTTPS on port 95.142.x.x:443, using                                                                                                                                                              HEAD

The code reaches the LW2.pm file but "hangs" on this line in LW2.PM sub http_do_request

If needed I can give access to this service

**Comment by amjo** [comment]
Sorry to bring light into this again. But i'm having the same issue. i get to run the following:

`perl nikto.pl -ssl -h ominvest.net`

- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          205.186.160.59
+ Target Hostname:    ominvest.net
+ Target Port:        443
---------------------------------------------------------------------------
+ SSL Info:        Subject:  /CN=ominvest.net
                   Altnames: ominvest.net, www.ominvest.net
                   Ciphers:  ECDHE-RSA-AES256-GCM-SHA384
                   Issuer:   /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
+ Start Time:         2019-06-06 04:24:35 (GMT-4)
---------------------------------------------------------------------------
+ Server: nginx
+ Retrieved ms-author-via header: DAV
+ Uncommon header 'ms-author-via' found, with contents: DAV
+ The site uses SSL and Expect-CT header is not present.
^Z
[3]+  Stopped                 perl nikto.pl -ssl -h ominvest.net

Eventually i had to stop it after an hour. Does it usually take more than that? (first time user)

**Comment by sausthavnegi** [comment]
Hi , bringing again this issue into the light.

Nikto v2.1.6

was ruuning some basic scan on a website 
nikto -h (websit address).

but after returning some value it got stuck and eventually i have to stop it.

Any help/advice would be appreciated (first time user)

**Comment by sullo** [comment]
@sausthavnegi can you provide some details from running `-D V` or `-D DV` ? At what point does it hang?
