### ISSUE TITLE
Bug: - ***** TLS/SSL support not available (see docs for SSL install) ***** - Nikto v2.5.0

### ISSUE THREAD

**Issue by Corzine82** [sullo/nikto#852]
I have Nikto v.2.5.0 installed on my Mac (sequoia 15.1.1) - i installed it from brew.

when i use the simple command nikto -h website.com (replacing website.com with the actual site i am hitting) i get the following statement right away:

- ***** TLS/SSL support not available (see docs for SSL install) *****
- Nikto v2.5.0

- when i run this on a lesser version of Nikto on the webserver it detects just fine that there is SSL.

I looked online and found no documentation about this SSL thing.  Also there hasn't been much updating in this repository lately - can anyone confirm if they have v.2.5.0 working on their mac with option -h for testing SSL?

**Comment by sullo** [comment]
All of the (arguably limited) development is done on a Mac using perl v5.34.1. So it should work fine. 

Nikto relies on the underly perl modules Net::SSLeay or Net::SSL. It will default to use SSLeay if both are available. You can install/validate install by running:
`perl -MCPAN -e 'install Net::SSLeay'`

Also, in nikto.conf.default (just copy it to nikto.conf to make changes) is this section:
```
# Choose SSL libs:
# SSLeay        - use Net::SSLeay
# SSL           - use Net::SSL
# auto          - automatically choose what's available
#                 (SSLeay wins if both are available)
LW_SSL_ENGINE=auto
```

Where you can experiment with forcing one vs the other. More info on this can be found [in the docs](https://github.com/sullo/nikto/wiki/Config-Variables).

Hope that helps. If not post what you tried and the results and we can try to figure out what's happening.

**Comment by Corzine82** [comment]
When I type that command in terminal on my MAC i got an error.

perl -MCPAN -e 'install Net::SSLeay'
Can't locate object method "install" via package "Net::SSLeay" at -e line 1.

Also, I am running a newer version of perl than that not sure if it makes a difference.

perl -v 

This is perl 5, version 40, subversion 0 (v5.40.0) built for darwin-thread-multi-2level

**Comment by sullo** [comment]
The Perl module install may have changed that version. Please look up those
instructions to do a proper install.

**Comment by Corzine82** [comment]
Running the command: cpan Net::SSLeay does successfully run the install for module 'Net::SSLeay'

this script fails every time at t/local/32_x509_get_cert_info.t line 273.

othername: ***@***.***’

got: ***@***.***, URI:http://intermediate-ca.net-ssleay.example, DNS:intermediate-ca.net-ssleay.example, Registered ID:1.2.0.0, IP Address:192.168.0.1, IP Address:FD25:F814:AFB5:9873:0:0:0:1, othername: ***@***.***'
#     expected: ***@***.***, URI:http://intermediate-ca.net-ssleay.example, DNS:intermediate-ca.net-ssleay.example, Registered ID:1.2.0.0, IP Address:192.168.0.1, IP Address:FD25:F814:AFB5:9873:0:0:0:1, othername: ***@***.***'

#   Failed test 'X509V3_EXT_print nid=85	extended-cert.cert.pem:8'
#   at t/local/32_x509_get_cert_info.t line 273.
#          got: ***@***.***, URI:http://johndoe.net-ssleay.example, DNS:johndoe.net-ssleay.example, Registered ID:1.2.3.4, IP Address:192.168.0.2, IP Address:FD25:F814:AFB5:9873:0:0:0:2, othername: ***@***.***'
#     expected: ***@***.***, URI:http://johndoe.net-ssleay.example, DNS:johndoe.net-ssleay.example, Registered ID:1.2.3.4, IP Address:192.168.0.2, IP Address:FD25:F814:AFB5:9873:0:0:0:2, othername: ***@***.***'
# Looks like you failed 2 tests of 746.

kinda weird - it looks like its expecting IP address 192.168.0.2 instead of 192.168.0.1….

**Comment by sullo** [comment]
You'll have to work with the Net::SSLeay devs or other resources to resolve that one, or try the other module. I'm going to close this issue, but if after you get perl's SSL configuration working if you still have trouble reopen or create a new issue.
