### ISSUE TITLE
Updating Nikto from Git Repo

### ISSUE THREAD

**Issue by darksheer** [sullo/nikto#99]
Nikto is throwing an error of :

perl nikto.pl -update
- ERROR (404): Unable to get www.cirt.net/nikto/UPDATES/2.1.6/versions.txt

Is this actually a bug?  or are all the plugs already latest version since its coming directly from git?

**Comment by mcnightstricker** [comment]
sullo , please tell me , how to do it exactly ? i mean i am just new to this , i am using kali linux 2018.3
64 bit , where i can find nikto folder and how can i update it with git ? please help
thank you

**Comment by sullo** [comment]
@mcnightstricker its tricky because it's on Kali and their packaging breaks ours. You can do one of two things:

1. download the files from git and replace the ones in the databases directory (the code may have changed to)
2. download the package (or git clone) and keep it updated with 'git pull'
